#   -*- mode: org; fill-column: 60 -*-
#+TITLE: TL:DR
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/deploy/deploy-tldr.org
  :Created:   2017-06-03T18:26@Prek Leap (11.642600N-104.919210W)
  :ID:        198d96e2-74f3-4c37-a3cd-c113f0c04a90
  :VER:       549761253.297109630
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:NAT1-3171
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Cover

Chenla
TL;DR 

by Brad Collins


2017

Chenla Scopic Press
Prek Leap


* Title Page

Chenla Scopic Press

        &

The Chenla Institute Center for Distributed Civilization

Prek Leap, Cambodia

&copy; 2017 The Chenla Institute

* Contents

  [ *Contents* ] 

* Preface

 - Chenla TL;DRs
 - Scopic Presses

* Revolutionary Cycles

 - Centralized
 - Decentralized
 - Distributed

Technological revolutions break up centralized systems into a
distributed system where the power is at the edge of the networks.
Over time, consolidation occurs into a decentralized network made up
of a large number of medium sized organizations.  Finally these
mid-sized organizations consolidate into a handful or even a single
organization that monopolizes the network.

As networks consolidate into decentralized and then centralized
systems, innovation slows down, creating a power-wealth-value
imbalance that is not sustainable.

In 2017 the Internet & The Web, which started as a distributed
network, consolidated to the point where the number of players can
almost be counted on one hand.

We are at the beginning of no less than five revolutions; artificial
intelligence, robotics, nanotech, distributed trustless networks
(based on cryptography, merkle trees and distributed ledgers) and a
biological revolution based on genetic gene splicing technologies like
CRSPR. 

Any one of these technologies alone would contitute change at the same
scale as Gutenberg's Press, The Industrial Revolution, The Computer
and Internet Revolutions.  Taken together each of these revolutions
will amplify, and reinforce each other.  The next 5-20 years will
fundamentally reshape business, finance, manufacturing,
transportation, energy, agriculture, medicine, education, government
and the world order.  Simply put, we are seeing changes that will
transform human civilization to the point that is can be called a
Singularity; a future that we can not predict or even imagine today.

* A New Distributed Network Layer 

* Interplanetary File System

* Cryptocurrencies

* Neural Nets

* Missing Pieces

- Identity Model
- Fnords: acertaining certainty
- Codex.d: distributed publication
- Sneaker Net of Things (SNOT)

* Saltmine (our implementation)
  
 - hoards
 - horcruxes
 - maps
 - duck tests
 - guilds

* Opportunities

* Towards a Distributed Civilization

* Primer

 - Descriptive
 - Proscriptive
 - Tools
 - Materials

* The Chenla Institute


Establishing the institute

A distributed (as MIT MediaLab puts it) anti-disciplinary
research institute incorporated in Singapore, Germany and
France ??? with it's first campus located at Prek Leap
National College of Agriculture in Cambodia.

The Institute's mandate is to develop, document and deploy
the descriptive and proscriptive information, code, designs,
and ideas needed to establish a highly distributed
civilization for Mankind.

The Institute will work with governments, NGOs and industry
to to understand and adapt to the radical changes that will
reshape our civilization in the coming decades, and to spin
off commerical and non-profit organizations and companies
that will implement the technologies developed at the
Institute.

The Institute is commited to openess and transparency.  All
works will be released under open source/content/design
licences.


  - organization & legal
    - Administrative office
    - Centre for Distributed Civilization
    - b>i Research Group
    - Chenla Scopic Press

  - facilities: 
    - viz centre : collaboration and conference space
    - Fab Lab : tool & machine fabrication
    - Map Lab : content & code
    - Wet Lab : Gene Splicing & Agricultural Biotech

  - people:
    - faculty 
    - sabbatical program
    - fellowship program
    - internship program

  - Conferences, Symposia, & Summits

  - Sponsorship
    - Commercial Sponsors
    - Endowments
    - Network Membership
