#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Gods
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/deploy/deploy-gods.org
:Created:   2017-08-26T16:14@Prek Leap (11.642600N-104.919210W)
:ID:        76555829-9bc2-4d8d-aac4-92faaf82f280
:VER:       557010923.697237659
:GEO:       48P-491193-1287029-15
:BXID:      proj:TCS4-1753
:Class:     deploy
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

If everything is a story, and we use our stories to collectively
create maps of the world and contexts that we use to go about our
lives and live and cooperate with each other then Gods in our new
civilization will be a narrative layer on top of complex technological
processes.

These systems will eventually be largely autonomous

** Demiurge

Since all gods are made by men, and men bestow not only life but power
to them, and to some extent deed them limited clearly defined power
over us, then there must be a master entity that keeps the gods
honest.

A god can only be created by a demiurge which is a sort of
constitutional god -- that is, itself created with clear rule sets
that embody the compact that collectively binds a community and a
civilization's members together.  In modern terms these would be
simular to a constitution and a bill of rights.  A demiurge is nothing
more or less the keeper and holder of this compact.  All gods within
the dominion of the demiurge can not do anything that violates that
compact and the demiurge is constantly monitoring that the gods it has
dominion over adheres to that compact.  If the compact is violated the
demiurge ultimately can over override and even shut down or destroy a
god either because the god has been tampered with and is not doing
what it is supposed to, or people are trying to compromise the god in
ways beyond its control.
