#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Social Structures
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/deploy-social.org
  :Created: 2017-03-28T11:19@Prek Leap (11.642600N-104.919210W)
  :ID: 2ec9e76f-ed84-4b0f-82bd-e09326c6afd2
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

#+begin_quote
For if society lacks the unity that derives from the fact
that the relationships between its parts are exactly
regulated, that unity resulting from the harmonious
articulation of its various functions assured by effective
discipline and if, in addition, society lacks the unity
based upon the commitment of men's wills to a common
objective, then it is no more than a pile of sand that the
least jolt or the slightest puff will suffice to scatter.

— Émile Durkheim
  quoted in [[https://en.wikipedia.org/wiki/%C3%89mile_Durkheim#cite_note-23][Émile Durkheim]] | Wikipedia
#+end_quote

#+begin_quote
Here's what we want as a society: We want fairness in how
people treat us. We want respect. And we want
dignity. That's it! It's not a big deal. This seems so
simple. Forget the law for a minute that /requires/ common
decency and treatment of passengers. Just treat us with
respect make us feel like you really care.

-- Thomas Demetrio
   [[https://www.youtube.com/watch?v=VPCvyBJjmVk][Dr. David Dao's Lawyers Speak to the Press]] | YouTube
#+end_quote


It's clear that modern technological society is rapidly
becoming disfunctional as the social institutions and
structures that evolved to make the industrial revolution
possible crumble around us.  

We don't have any functional family structures left, no
concept of /home/ that provides an anchor from which
everything else is founded on.  Instead we invent
"identities" which are little more than cultural fads.  The
nation state continues to reinforce a sense of national
identity, but States are now too big for such identities to
be very useful.  Increasingly there is little more to
collectively identify with other than sports teams, which
originaly were tools to build a shared identity around
something else, a state, a town, a school, a company... but
increasingly the teams that people are supposed to rally
around have become unmoored, becoming consumer brands, and
moving from place to place according to the financial whim
of the owners.  The team and sport have become identities in
their own right, no longer an activity that brings together
a community.


** division of labor

  - [[https://en.wikipedia.org/wiki/%C3%89mile_Durkheim][Émile Durkheim]] | Wikipedia
  - [[https://en.wikipedia.org/wiki/The_Division_of_Labour_in_Society][The Division of Labour in Society]] | Wikipedia

The model that I've using for quite some time now
goes something like this:

The industrial revolution produced more goods, more
efficiently than could be consumed by markets.  People
bought what they needed, so once everyone had bought
something demand dropped and limited growth for large
companies even in very large markets.

Consumerism was industry's answer to this problem.  It
encouraged people to purchase things for egocentric rather
than utilitarian reasons and for goods to be made to fail or
wear out predictably, so that they would have to be replaced
with different models that appealed to the individual's ego.

This model still holds up, but it is not the only way of
looking at the problem.  The French sociologist Émile
Durkheim saw the problem from a different perspective.

#+begin_quote
In Durkheim's view, traditional religions often provided the
basis for the shared values which the anomic individual
lacks. Furthermore, he argued that the division of labor
that had been prevalent in economic life since the
Industrial Revolution led individuals to pursue egoistic
ends rather than seeking the good of a larger community.

-- [[https://en.wikipedia.org/wiki/Anomie][Anomie]] | Wikipedia, accessed <2013-02-03>
   The article text has changed since I quoted it in 2013.
#+end_quote

If different "social functions" are in contact with each
other, then when something changes, those changes propagate
through out the entire system.  But when that contact is
broken communication between the parts only large changes
get transmitted.

#+begin_quote
Since a body of rules is the definite form which
spontaneously established relations between social functions
take in the course of time, we can say, a priori,that the
state of anomy is impossible wherever solidary organs are
sufficiently in contact or sufficiently prolonged. In
effect, being contiguous, they are quickly warned, in each
circumstance, of the need which they have of one another,
and, consequently, they have a lively and continuous
sentiment of their mutual dependence. For the same reason
that exchanges take place among them easily, they take place
frequently; being regular, they regularize themselves
accordingly, and in time the work of consolidation is
achieved. Finally, because the smallest reaction can be felt
from one part to another, the rules which are thus
formulated carry this imprint; that is to say, they foresee
and fix, in detail, the conditions of equilibrium. But, on
the contrary, if some opaque environment is interposed, then
only stimuli of a certain intensity can be communicated from
one organ to another.  Relations, being rare, are not
repeated enough to be determined; each time there ensues new
groping.

-- The Division of Labor in Society,
   [[https://en.wikipedia.org/wiki/%C3%89mile_Durkheim][Émile Durkheim]], The MacMillan Co. 1933, Free
   Press edition, 1964
#+end_quote

In effect, the amount of information that is transfered
between the parts is not only decreased but is far less
detailed.  This makes the system less responsive and
efficient.

Durkheim argued that when production was located in the same
place as consumption there was a feedback loop that kept
production and consumption in equilibrium.

#+begin_quote
This is what happens in the cases we are discussing. In so
far as the segmental type is strongly marked, there are
nearly as many economic markets as there are different
segments. Consequently, each of them is very
limited. Producers, being near consumers, can easily reckon
the extent of the needs to be satisfied.  Equilibrium is
established without any trouble and production regulates
itself. On the contrary, as the organized type develops, the
fusion of different segments draws the markets together into
one which embraces almost all society. This even extends
beyond, and tends to become universal, for the frontiers
which separate peoples break down at the same time as those
which separate the segments of each of them.  The result is
that each industry produces for consumers spread over the
whole surface of the country or even of the entire
world. Contact is then no longer sufficient. The producer
can no longer embrace the market in a glance, nor even in
thought. He can no longer see its limits, since it is, so to
speak, limitless.  Accordingly, production becomes unbridled
and unregulated. It can only trust to chance, and in the
course of these gropings, it is inevitable that proportions
will be abused, as much in one direction as in another.
From this come the crises which periodically disturb
economic functions. The growth of local, restricted crises
which result in failures is in all likelihood an effect of
the same cause.  As the market extends, great industry
appears. But it results in changing the relations of
employers and employees. The great strain upon the nervous
system and the contagious influence of great agglomerations
increase the needs of the latter. Machines replace men;
manufacturing replaces hand-work. The worker is regimented,
separated from his family throughout the day. He always
lives apart from his employer, etc.  These new conditions of
industrial life naturally demand a new organization, but as
these changes have been accomplished with extreme rapidity,
the interests in conflict have not yet had the time to be
equilibrated.

-- The Division of Labor in Society, [[https://en.wikipedia.org/wiki/%C3%89mile_Durkheim][Émile Durkheim]], The
   MacMillan Co. 1933, Free Press edition, 1964
#+end_quote




** the doomed

#+begin_quote
Dr. Hunter S. Thompson: Hi sir, it's Harris from the
Post. Can I get you anything sir?

Candidate: How's the family Harris?

Dr. Hunter S. Thompson: Oh the family, well that's bad
news. The screwheads finally came and took my daughter
away. Let me ask you a question sir, what is this country
doing for the doomed? There are two kinds of people in this
country, the doomed and the screwheads. Savage tribal thugs
who live off their legal incomes, brow deep out there; no
respect for human dignity. They don't know what you and I
understand, you know what I mean.

Candidate: You ever play football, Harris?

Dr. Hunter S. Thompson: Yes sir, thank you sir. I played in
college, and they're gonna get your daughter too sir. I've
heard their rallies, they like Julie but Tricia... and they
really hate you sir. You know that one and a half of the
State Senate of Utah are screwheads. You know I was never
really frightened by the bopheads and the potheads with
their silliness never really frightened me either, but these
goddam screwheads, they terrify me. And the poor doomed, the
young, and the silly, the honest, the weak, the
Italians... they're doomed, they're lost, they're helpless,
they're somebody else's meal, they're like pigs in the
wilderness.

Candidate: Come here Harris, come here. Fuck the doomed! 

-- [[https://en.wikipedia.org/wiki/Where_the_Buffalo_Roam][Where the Buffalo Roam]] | Conversation between Hunter
Thompson and Richard Nixon in public rest room.

#+end_quote



The present generation or two is likely lost, people can
only change so much over a lifetime and what we are asking
of people is beyond the cognitive capability for most
people.  I am /not/ saying these people are dumb, but they
were dealt a shitty hand.  This has happened over and over
throughout history, and there has never been a recorded
instance where the majority of these doomed generations are
able to escape their fate.

This doesn't mean we don't try to reach as many people as
possible, even as we rethink what it means to have the
minimal education in a technologically advanced civilization
in order to live a productive and meaningful life.

This doesn't address how we can help the doomed to live at
least a comfortable life.  This is not the place to go into
these kinds of scenarios, but the robotics revolution
together with AI will not only put the doomed out of work,
but will also provide the wealth needed to provide the
doomed with a univeral basic income and a hopefully less
destructive consumer lifestyle to the end of their days.
This is no Utopia, because humans suck at executing on
things that are in their collective interest.

And as anyone who has watched /any/ science fiction film
will know, that this risks an elite class emerging who will
have opportunities and advantages over the doomed.  We do
not want Nanny States, no matter how safe they may be, it
only makes things worse, makes people feel trapped and when
people feel frightened or trapped they turn violent.  At the
same time we can't simply try to keep them sated and docile.
Perhaps that will work for some but it's a terrible waste of
life.

Clay Shirky wrote of how each technological revolution
created a /cognitive surplus/ of free time.

The first of these revolutions resulted in at least one
generation drinking themselves to death.

#+begin_quote
An examination of the Gin Acts and crime would be incomplete
without reference to poverty and the role poverty played in
exacerbating the problems that arose in London related to
gin consumption. Most people who drank gin were among the
citys working class poor. Since the poor were small,
malnourished, and lived in an unsanitary environment, they
were ill equipped to metabolize the large quantities of
alcohol gin delivered.23 Gin provided refuge and comfort
from the harsh realities of daily London life.24 Gin helped
relieve the pains of adaptation to unfamiliar and
increasingly industrialized work routines and to unhealthy
living conditions in a city that had few recreational
outlets beyond the gin-shop.25 Evidently, the infrastructure
of the day was inadequate to meet the complex challenges
posed by a modern city life characterized by an increasingly
heterogeneous population26 and the dislocation of the
industrial revolution served to heighten the social and
medical problems of excessive gin-drinking.

-- [[https://web-beta.archive.org/web/20080202074611/http://culturalshifts.com/archives/168][The Gin Craze: Drink, Crime & Women in 18th Century London]] | Cultural Shift(s)
#+end_quote


#+begin_quote
in beginning the Gin Craze; as the price of food dropped and
income grew, consumers suddenly had the opportunity to spend
excess funds on liquor.

-- [[https://en.wikipedia.org/wiki/Gin_Craze][Gin Craze]] | Wikipedia
#+end_quote


The second was the Sitcom where generations sat every
evening eyes glazed in front of televisions.  I was a part
of that generation, and spend an astonishing amount of time
sitting with my parents and sister every night watching the
television from after dinner until it was time to go to
sleep.  I was lucky enough to break away from the cycle in
high school and spent more time reading and writing (outside
of school assignments and homework) than in front of the TV.
And in daylight hours I did everything from raise chickens
and sell eggs, to setting up a logging company.

Now it's Facebook -- but facebook is far more problematic,
and potentially more destructive than Gin.

Shirky saw this as a positive thing and that the Internet is
giving people the means of production.  This is true to a
point, but it does not give people the tools to think that
provide people with the discipline and responsibility that
comes with the means of production.  It's that tired tag
line from Spiderman, "with great power comes great
responsibility."  And the Internet is handing everyone that
power without telling them that it comes at a cost,
sometimes a terrible cost that, for many people, if they
knew what that cost was, wouldn't want to pay.

Having one without the other is a recipe for disaster.

In his 2017 annual speech at SXSW, Bruce Sterling outlined a
number of different scenarios of what this might look like,
and it's not all bad.  Not all good either, but there is
hope of a kind for a meaningful life for the doomed who are
left behind.

  - [[https://soundcloud.com/officialsxsw/the-future-history-that-hasnt-happened-yet-sxsw-2017][The Future: History that Hasn’t Happened Yet]] | SXSW 2017 | SoundCloud
  - [[https://www.wired.com/beyond-the-beyond/2017/03/bruce-sterling-speech-sxsw2017/][Bruce Sterling speech at SXSW2017]] | WIRED

Sterling's Univeral Basic Income (UBI) Scenarios:

   1. Reservations -- ala American Indian Reservation
   2. Prison Systems and Labor Camps -- liquidate entire social classes 
   3. Refuge Camps -- $1,200 per person per year
   4. The Armed Forces -- you get a job, barracks, a uniform,
      orders.  People are in shape, they have meaningful work etc.
   5. Retirement Villages -- 
   6. Universties -- not conventional economies but people
      are busy
   7. Religion -- monasteries & nunneries
   8. Hospitals & Spas -- people concentrate on health and
      well being
   9. Intentional Rural Communes -- romantic and never works
  10. Dropout Urban Bohemia -- lifestyle isn't
      self-supporting, 
  11. Enlightenment -- roam the earth -- can't really raise
      children

Sterling is very much a part of the technosphere as a sci fi
writer and futurist.  So he may not see that there might be
another way...

We don't really have a word for today's family unit.  A few
decades ago we had the 'nuclear' family, but this seems to
be breaking up to the point where there is no atomic unit
beyond individuals who have relationships at different
points in their lives.

The nuclear family a child of the industrial revolution.
Factories drew the young, ambitious and educated from rural
towns and villages to work in centralized factories and
business districts.  This broke up the extended family
which was a large unweildly construct that basically
consisted of everyone related to each other, productive or
otherwise.  The nuclear family was only possible if there
was a 'breadwinner' in the family who could support a spouse
and children, and perhaps support a parent or two from a
distance.  The breadwinner was basically on their own --
they could not fail or the family would fail.  No one helped
the breadwinner make money, the wife (the breadwinner was
almost always male in nuclear households) tended the house
and children who lived in a fake pastoral area outside of
the industrial or business areas, which had no opportunities
to do much of anything other than raise children.

Before suburban hell became the norm for the middle class,
it was single women who were the first to leave the villages
to work in factories.  The men at first stayed home, because
they were deemed to be too valuable to keep the family
enterprises going.  But eventually, the men followed as
well, emptying the villages of the young and able.

Compare this to a family owned farm, where most people
helped out in the family enterprise.  The school calendar
was arranged around plantings and harvests.  These family
enterprises provided for the productive and unproductive,
from infants to the sick and disabled to the elderly and
infirmed.  Nuclear families couldn't do any of this.  The
system excluded anyone who was not productive, or providing
a support system for productive people.

The extended family had some significant limitations as
well.  Large families who had many children who survived
found it difficult to start up their own family enterprises
because of their bonds to their extended family.  People
didn't travel or move very far.  This made families
inflexible and it was common for family members to pass on
opportunities because of their family bonds.

This kept villages inbred and stagnant.  Small towns work on
many levels, but they reward gossip, infighting and are
terrible places for people who are creative, or highly
intelligent who need different kind of support structures
and communities to realise their potential.

Family businesses are traditionally passed on to the eldest
son in a family along with the property and most of the
wealth as the torch is passed from generation to
generation.  But not all eldest sons have the talent, skills
or disposition to fill their father's shoes.

Perhaps we can evolve a new kind of extended family that can
resolve this contradiction, by providing a stable
cradle-to-grave group that will care for everyone in the
group, but also make it possible for people to be able to
travel, have access to broader communities and opportunities
at the same time.

Japan had an interesting take on family businesses.  If
there was not a suitable son to take over a family business,
then someone from outside of the family not only married
into the family but was adopted by the family -- taking
their name as well.  This has made possible some of the
longest running businesses in the world -- businesses that
are 500 years old are not the norm in Japan, but they do
exist.

The Japanese innovation is the 'salary man' -- employees who
in effect are adopted by a company and stay for life, with
the understanding that they will be taken care of for life
-- not just until they retire but life.  But again, there is
no flexibility or room for growth -- which has led to
corporate Japan becoming slow and inflexible.  In many ways
it's the same trap as the village and extended family.


** a robotic cottage industrial fabric

I'm thinking along the lines that shops (not all) could be
the equivilant of both an extended family and a japanese
corporation.  Each shop is owned by a small group of
extended families which the shops support for life.  This
requires *very* productive shops to be able to do this.  And
this is where automation, robotics and AI come in, so that a
small group of productive people, with a larger group of
semi-productive people and a lot of robots could do just
this.

But rather than each family (or collective or whatever)
relying on one shop, different members of the family will
belong to different and often overlapping shops -- some
primary full time, other will be secondary, seasonal,
part-time shops.

Leverage networks to coordinate transactions (and contracts),
communications, knowledge, supply chains, logistics and
orders.

And the thing is, that the more positive of scenarios on
Sterling's list could still be available as options for
people at different times in their lives.  Most would
eventually be pulled back into their family's orbits, and
those who aren't suited could wander the earth, or be weird
or join monastaries or armies or whatever....

But I don't think that massive centralized robotic factories
are where this is all going -- disruptive technologies break
up centralized structures and move power to the edges.
Robots will do the same thing -- but perhaps we can forstall
the next cycle of consolidation by moving away from consumer
industrial manufacturing and build stable institutions and
social structures that make sense for at least a few
generations. In a sense it would be a robotic cottage
industrial fabric -- it's not consumer but it's market
driven -- the goal is to give people a good life, healthy,
productive and meaningful -- not focused exclusively on
become rich as an end in its self.  In this kind of
structure, the super rich are not needed -- but this is only
possible if the ability to profit from power is taken away.
The people in power shouldn't want to be in power -- it is a
burden and a duty, not a means of making yourself rich.

Yes, this is a Utopian vision ... that will never be
realised.  But a messy system that mostly works is something
that we can achieve.  And without a big grand vision to
believe in and work towards, things won't get better.

The AI-Robot-Bio-Nano-Whatever tipping point is coming, and
we damn well be ready for it, because if we get this one
wrong it won't be pretty.  And it won't happen with
pitchforks and protests or suicide vests -- it will happen
with education, and conviction and individual commitment to
making a better world.  And if we can give people a sane
alternative to what they have now -- with security, a
future, meaning and purpose, I hope that enough people will
take that chance.  No one has been able to offer the whole
thing before -- everything has been based on voluntary
sacrifice -- the green movement isn't offering anything
attractive to people -- please suffer, even though most
people won't do what you do, to save the planet.  People
need education for their children and healthcare and a sane
standard of living.  Give them that, in exchange for giving
up consumerism and jobs that will be replaced by robots, and
crumbling infrastructure.  But they will also have to give
up racism, sexism, nationalism (in all forms) and
consumerism. In other words it's the golden rule, everyone
is your brother, and treat your brother as you would want
them to treat you.

  - [[https://en.wikipedia.org/wiki/Golden_Rule][Golden Rule]] | Wikipedia
  - [[http://www.ted.com/talks/karen_armstrong_let_s_revive_the_golden_rule][Karen Armstrong: Let's revive the Golden Rule]] | TED Talk
  - [[https://en.wikipedia.org/wiki/Charter_for_Compassion][Charter for Compassion]] | Wikipedia
  - [[https://www.charterforcompassion.org/][Charter for Compassion]] | Home


The golden rule needs to be one of the core tenants of any
constitution and philosophy of life.



#+begin_verse
You will not be able to stay home, brother.
You will not be able to plug in, turn on and cop out.
You will not be able to lose yourself on skag and
Skip out for beer during commercials,
Because the revolution will not be televised.

...

The revolution will not be right back
After a message about a white tornado, white lightning, or white people.
You will not have to worry about a dove in your
Bedroom, a tiger in your tank, or the giant in your toilet bowl.
The revolution will not go better with Coke.
The revolution will not fight the germs that may cause bad breath.
The revolution will put you in the driver's seat.

The revolution will not be televised, will not be televised,
Will not be televised, will not be televised.
The revolution will be no re-run brothers,
The revolution will be live.

-- Gil Scott-Heron | The Revolution Will Not Be Televised
#+end_verse

That's a lot of promises -- so they can't be promises -- we
have to give it to them on day one -- not a promise for a
bright future for their children after the revolution.
Those promises are never kept, because requiring that kind
of a revolution as a first step is doomed to failure and
misery and collapse.

The American Founding Fathers were big picture people who
planned for human weakness -- they were dreamers, but
practical ones.


---

Perhaps, we need to think of the institutions that make up
civilization to be contradictory ways of looking at the
world.  I don't want to just slot them into the Trivium
subjects here -- we need those contradictions, and to learn
to live with the uncertainty that those contradictions create.

  - executive
  - legislative
  - judiciary
  - watchdog
  - education
  - ...

These are not just providing checks and balances, they are
different perspectives of the world with different maps.  We
tend to think of them as having different priorities, which
is also true, but that may be missing as well -- perhaps
each needs a guiding philosophy that defines that worldview.


* Family

** APL: Family

#+begin_quote
The nuclear family is not by itself a viable social form.

Therefore:

Set up processes which encourage groups of 8 to 12 people to
come together and establish communal
households. Morphologically, the important things are:

  1. Private realms for the groups and individuals that make
     up the extended family: couple's realms, private rooms,
     sub-households for small families.
  2. Common space for shared functions: cooking, working,
     gardening, child care. 3. At the important crossroads
     of the site, a place where the entire group can meet
     and sit together.

                         * * *

Until a few years ago, human society was based on the
extended family: a family of at least three generations,
with parents, children, grandparents, uncles, aunts, and
cousins, all living together in a single or loosely knit
multiple household. But today people move hundreds of miles
to marry, to find education, and to work. Under these
circumstances the only family units which are left are those
units called nuclear families: father, mother, and
children. And many of these are broken down even further by
divorce and separation.

Unfortunately, it seems very likely that the nuclear family
is not a viable social form. It is too small. Each person in
a nuclear family is too tightly linked to other members of
the family; any one relationship which goes sour, even for a
few hours, becomes critical; people cannot simply turn away
toward uncles, aunts, grandchildren, cousins,
brothers. Instead, each difficulty twists the family unit
into ever tighter spirals of discomfort; the children become
prey to all kinds of dependencies and oedipal neuroses; the
parents are so dependent on each other that they are finally
forced to separate.

Philip Slater describes this situation for American families
and finds in the adults of the family, especially the women,
a terrible, brooding sense of deprivation. There are simply
not enough people around, not enough communal action, to
give the ordinary experience around the home any depth or
richness. (Philip E. Slater, The Pursuit of
Loneliness,Boston: Beacon Press, 1970, p. 67, and
throughout.)

It seems essential that the people in a household have at
least a dozen people round them, so that they can find the
comfort and relationships they need to sustain them during
their ups and downs. Since the old extended family, based on
blood ties, seems to be gone - at least for the moment -
this can only happen if small families, couples, and single
people join together in voluntary "families" of ten or so.

In his final book, Island, Aldous Huxley portrayed a lovely
vision of such a development:

   "How many homes does a Palanese child have?"

   "About twenty on the average."

   "Twenty? My God!"

   "We all belong," Susila explained, "to a MAC -a Mutual
   Adoption Club. Every MAC consists of anything from
   fifteen to twentyfive assorted couples. Newly elected
   brides and bridegrooms, oldtimers with growing children,
   grandparents and great-grandparents everybody in the club
   adopts everyone else. Besides our own blood relations, we
   all have our quota of deputy mothers, deputy fathers,
   deputy aunts and uncles, deputy brothers and sisters,
   deputy babies and toddlers and teen-agers."

   Will shook his head. "Making twenty families grow where
   only one grew before."

   "But what grew before was your kind of family. As though
   reading instructions from a cookery book, "Take one
   sexually inept wage slave," she went on, "one
   dissatisfied female, two or (if preferred) three small
   television addicts; marinate in a mixture of Freudism and
   dilute Christianity, then bottle up tightly in a four room
   flat and stew for fifteen years in their own juice. Our
   recipe is rather different: Take twenty sexually
   satisfied couples and their offspring; add science,
   intuition and humor in equal quantities; steep in Tantrik
   Buddhism and simmer indefinitely in an open pan in the
   open air over a brisk flame of affection."

   "And what comes out of your open pan?" he asked.

   "An entirely different kind of family. Not exclusive,
   like your families, and not predestined, not
   compulsory. An inclusive, unpredestined and voluntary
   family. Twenty pairs of fathers and mothers, eight or
   nine ex-fathers and ex-mothers, and forty or fifty
   assorted children of all ages." 
   
   -- (Aldous Huxley, Island,New York: Bantam, 1962, pp. 89-go.)  


Physically, the setting for a large voluntary family must
provide for a balance of privacy and communality. Each small
family, each person, each couple, needs a private realm,
almost a private household of their own, according to their
territorial need. In the movement to build communes, it is
our experience that groups have not taken this need for
privacy seriously enough. It has been shrugged off, as
something to overcome. But it is a deep and basic need; and
if the setting does not let each person and each small
household regulate itself on this dimension, it is sure to
cause trouble. We propose, therefore, that individuals,
couples, people young and old - each subgroup - have its own
legally independent household - in some cases, physically
separate households and cottages, at least separate rooms,
suites, and floors.

The private realms are then set off against the common space
and the common functions. The most vital commons are the
kitchen, the place to sit down and eat, and a garden. Common
meals, at least several nights a week, seem to play the
biggest role in binding the group. The meals, and taking
time at the cooking, provide the kind of casual meeting time
when everything else can be comfortably discussed: the child
care arrangements, maintenance, projects - see COMMUNAL
EATING (147).

This would suggest, then, a large family room - farmhouse
kitchen, right at the heart of the site - at the main
crossroads, where everyone would tend to meet toward the end
of the day. Again, according to the style of the family,
this might be a separate building, with workshop and
gardens, or one wing of a house, or the entire first floor
of a two or three story building.

There is some evidence that processes which generate large
voluntary group households are already working in the
society. (Cf. Pamela Hollie, "More families share houses
with others to enhance 'life style,' " Wall Street
Journal,July 7, 1972.)

One way to spur the growth of voluntary families: When
someone turns over or sells their home or room or apartment,
they first tell everyone living around them - their
neighbors. These neighbors then have the right to find
friends of theirs to take the place - and thus to extend
their "family." If friends are able to move in, then they
can arrange for themselves how to create a functioning
family, with commons, and so on. They might build a
connection between the homes, knock out a wall, add a
room. If the people immediately around the place cannot make
the sale in a few months, then it reverts to the normal
marketplace.

-- A Pattern Language: Family
#+end_quote


* Work

** APL: Scattered Work

#+begin_quote
In modern times almost all cities create zones for "work"
and other zones for "living" and in most cases enforce the
separation by law. Two reasons are given for the
separation. First, the work places need to be near each
other, for commercial reasons. Second, workplaces destroy
the quiet and safety of residential neighborhoods.

But this separation creates enormous rifts in people's
emotional lives. Children grow up in areas where there are
no men, except on weekends; women are trapped in an
atmosphere where they are expected to be pretty,
unintelligent housekeepers; men are forced to accept a
schism in which they spend the greater part of their waking
lives "at work, and away from their families" and then the
other part of their lives "with their families, away from
work."

Throughout, this separation reinforces the idea that work is
a toil, while only family life is "living" - a schizophrenic
view which creates tremendous problems for all the members
of a family.

In order to overcome this schism and re-establish the
connection between love and work, central to a sane society,
there needs to be a redistribution of all workplaces
throughout the areas where people live, in such a way that
children are near both men and women during the day, women
are able to see themselves both as loving mothers and wives
and still capable of creative work, and men too are able to
experience the hourly connection of their lives as workmen
and their lives as loving husbands and fathers.

What are the requirements for a distribution of work that
can overcome these problems?

  1. Every home is within 20-30 minutes of many hundreds of
     workplaces.
  2. Many workplaces are within walking distance of children
     and families.
  3. Workers can go home casually for lunch, run errands,
     work half-time, and spend half the day at home.
  4. Some workplaces are in homes; there are many
     opportunities for people to work from their homes or to
     take work home.
  5. Neighborhoods are protected from the traffic and noise
     generated by "noxious" workplaces.

The only pattern of work which does justice to these
requirements is a pattern of scattered work: a pattern in
which work is strongly decentralized. To protect the
neighborhoods from the noise and traffic that workplaces
often generate, some noisy work places can be in the
boundaries of neighborhoods, communities and subcultures -
see SUBCULTURE BOUNDARY (3); others, not noisy or noxious,
can be built right into homes and neighborhoods. In both
cases, the crucial fact is this: every home is within a few
minutes of dozens of workplaces. Then each household would
have the chance to create for itself an intimate ecology of
home and work: all its members have the option of arranging
a workplace for themselves close to each other and their
friends. People can meet for lunch, children can drop in,
workers can run home. And under the prompting of such
connections the workplaces themselves will inevitably become
nicer places, more like homes, where life is carried on, not
banished for eight hours.

This pattern is natural in traditional societies, where
workplaces are relatively small and households comparatively
self-sufficient. But is it compatible with the facts of high
technology and the concentration of workers in factories?
How strong is the need for workplaces to be near each other?

The main argument behind the centralization of plants, and
their gradual increase in size, is an economic one. It has
been demonstrated over and again that there are economies of
scale in production, advantages which accrue from producing
a huge number of goods or services in one place.

However, large centralized organizations are not intrinsic
to mass production. There are many excellent examples which
demonstrate the fact that where work is substantially
scattered, people can still produce goods and services of
enormous complexity. One of the best historical examples is
the Jura Federation of watchmakers, formed in the mountain
villages of Switzerland in the early 1870's. These workers
produced watches in their home workshops, each preserving
his independence while coordinating his efforts with other
craftsmen from the surrounding villages. (For an account of
this federation, see, for example, George Woodcock,
Anarchism: A History of Libertarian Ideas and
Movements,Cleveland: Meridian Books, 1962, pp. 168-69.)

In our own time, Raymond Vernon has shown that small,
scattered workplaces in the New York metropolitan economy,
respond much faster to changing demands and supplies, and
that the degree of creativity in agglomerations of small
businesses is vastly greater than that of the more
cumbersome and centralized industrial giants. (See Raymond
Vernon, Metropolis,1985, Chapter 7: External Economics.)

To understand these facts, we must first realize that the
city itself is a vast centralized workspace and that all the
benefits of this centralization are potentially available to
every work group that is a part of the city's vast work
community. In effect, the urban region as a whole acts to
produce economies of scale by bringing thousands of work
groups within range of each other. If this kind of
"centralization" is properly developed, it can support an
endless number of combinations between small, scattered
workgroups; and it can lend great flexibility to the modes
of production. "Once we understand that modern industry does
not necessarily bring with it financial and physical
concentration, the growth of smaller centers and a more
widespread distribution of genuine benefits of technology
will, I think, take place" (Lewis Mumford, Sticks and
Stones,New York, 1924, p. 216).

Remember that even such projects as complicated and
seemingly centralized as the building of a bridge or a moon
rocket, can be organized this way. Contracting and
subcontracting procedures make it possible to produce
complicated industrial goods and services by combining the
efforts of hundreds of small firms. The Apollo project drew
together more than 30,000 independent firms to produce the
complicated spaceships to the moon.

Furthermore, there is evidence that the agencies which set
up such multiple contracts look for small, semi-autonomous
firms. They know instinctively that the smaller, more
self-governing the group, the better the product and the
service (Small Sellers and Large Buyers in American
Industry,Business Research Center, College of Business
Administration, Syracuse University, New York, 1961).

Let us emphasize: we are not suggesting that the
decentralization of work should take precedence over a
sophisticated technology. We believe that the two are
compatible: it is possible to fuse the human requirements
for interesting and creative work with the exquisite
technology of modern times. It is possible to make
television sets, xerox machines and IBM typewriters,
automobiles, stereo sets and washing machines under human
working conditions. We mention in particular the xerox and
IBM typewriters because they have played a vital role for
us, the authors of this book. We could not have made this
book together, in the communal way we have done, without
these machines: and we consider them a vital part of the new
decentralized society we seek.

-- A Pattern Language
#+end_quote

** APL: Self-Governing Workshops and Office

#+begin_quote
No one enjoys his work if he is a cog in a machine.

Therefore:

Encourage the formation of self-governing workshops and
offices of 5 to 20 workers. Make each group autonomous -
with respect to organization, style, relation to other
groups, hiring and firing, work schedule. Where the work is
complicated and requires larger organizations, several of
these work groups can federate and cooperate to produce
complex artifacts and services.

                          * * *


   A man enjoys his work when he understands the whole and
   when he is responsible for the quality of the whole. He
   can only understand the whole and be responsible for the
   whole when the work which happens in society, all of it,
   is undertaken by small self-governing human groups;
   groups small enough to give people understanding through
   face-to-face contact, and autonomous enough to let the
   workers themselves govern their own affairs.

   The evidence for this pattern is built upon a single,
   fundamental proposition: work is a form of living, with
   its own intrinsic rewards; any way of organizing work
   which is at odds with this idea, which treats work
   instrumentally, as a means only to other ends, is
   inhuman. Down through the ages people have described and
   proposed ways of working according to this
   proposition. Recently, E. F. Schumacher," the economist,
   has made a beautiful statement of this attitude
   
   -- (E. F. Schumacher, "Buddhist Economics,"
   Resurgence,275 Kings Road, Kingston, Surrey, Volume 1,
   Number 11, January, 1968).

The Buddhist point of view takes the function of work to be
at least threefold: to give a man a chance to utilize and
develop his faculties; to enable him to overcome his
ego-centeredness by joining with other people in a common
task; and to bring forth the goods and services needed for a
becoming existence. Again, the consequences that flow from
this view are endless. To organize work in such a manner
that it becomes meaningless, boring, stultifying, or
nerveracking for the worker would be little short of
criminal; it would indicate a greater concern with goods
than with people, an evil lack of compassion and a
soul-destroying degree of attachment to the most primitive
side of this worldly existence. Equally, to strive for
leisure as an alternative to work would be considered a
complete misunderstanding of one of the basic truths of
human existence, namely, that work and leisure are
complementary parts of the same living process and cannot be
separated without destroying the joy of work and the bliss
of leisure.

From the Buddhist point of view, there are therefore two
types of mechanization which must be clearly distinguished:
one that enhances a man's skill and power and one that turns
the work of man over to a mechanical slave, leaving man in a
position of having to serve the slave. How to tell the one
from the other? "The craftsman himself," says Ananda
Coomaraswamy, a man equally competent to talk about the
Modern West as the Ancient East, "the craftsman himself can
always, if allowed to, draw the delicate distinction between
the machine and the tool. The carpet loom is a tool, a
contrivance for holding warp threads at a stretch for the
pile to be woven round them by the craftsmen's fingers; but
the power loom is a machine, and its significance as a
destroyer of culture lies in the fact that it does the
essentially human part of the work." It is clear, therefore,
that Buddhist economics must be very different from the
economics of modern materialism, since the Buddhist sees the
essence of civilization not in a multiplication of wants but
in the purification of human character. Character, at the
same time, is formed primarily by a man's work. And work,
properly conducted in conditions of human dignity and
freedom, blesses those who do it and equally their
products. The Indian philosopher and economist C. Kumarappa
sums the matter up as follows:

   "If the nature of the work is properly appreciated and
   applied, it will stand in the same relation to the higher
   faculties as food is to the physical body. It nourishes
   and enlivens the higher man and urges him to produce the
   best he is capable of. It directs his freewill along the
   proper course and disciplines the animal in him into
   progressive channels. It furnishes an excellent
   background for man to display his scale of values and
   develop his personality."

In contrast to this form of work stands the style of work
that has been created by the technological progress of the
past two hundred years. In this style workers are made to
operate like parts of a machine; they create parts of no
consequence, and have no responsibility for the whole. We
may fairly say that the alienation of workers from the
intrinsic pleasures of their work has been a primary product
of the industrial revolution. The alienation is particularly
acute in large organizations, where faceless workers repeat
endlessly menial tasks to create products and services with
which they cannot identify.

In these organizations, with all the power and benefits that
the unions have been able to wrest from the hands of the
owners, there is still evidence that workers are
fundamentally unhappy with their work. In the auto industry,
for example, the absentee rate on Mondays and Fridays is
staggering - 15 to 20 per cent; and there is evidence of
"massive alcoholism, similar to what the Russians are
experiencing with their factory workers" (Nicholas von
Hoffman, Washington Post). The fact is that people cannot
find satisfaction in work unless it is performed at a human
scale and in a setting where the worker has a say.

Job dissatisfaction in modern industry has also led to
industrial sabotage and a faster turnover of workers in
recent years. A new super-automated General Motors assembly
plant in Lordstown, Ohio, was sabotaged and shut down for
several weeks. Absenteeism in the three largest automobile
manufacturing companies has doubled in the past seven
years. The turnover of workers has also doubled. Some
industrial engineers believe that "American industry in some
cases may have pushed technology too far by taking the last
few bits of skill out of jobs, and that a point of human
resistance has been reached" (Agis Salpukis, "Is the machine
pushing man over the brink?" San Francisco Sunday Examiner
and Chronicle, April 16, 1972).

Perhaps the most dramatic empirical evidence for the
connection between work and life is that presented in the
recent study, "Work in America," commissioned by Elliot
Richardson, as Secretary of Health, Education and Welfare
Department, 1972. This study finds that the single best
predictor of long life is not whether a person smokes or how
often he sees a doctor, but the extent to which he is
satisfied with his job.The report identifies the two main
elements of job dissatisfaction as the diminishing
independence of workers, and the increasing simplification,
fragmentation, and isolation of tasks - both of which are
rampant in modern industrial and office work alike.

But for most of human history, the production of goods and
services was for a far more personal, self-regulating
affair; when each job of work was a matter of creative
interest. And there is no reason why work can't be like that
again, today.

For instance, Seymour Melman, in Decision Making and
Productivity,compares the manufacture of tractors in Detroit
and in Coventry, England. He contrasts Detroit's managerial
rule with Coventry's gang system and shows that the gang
system produced high quality products and the highest wages
in British industry. "The most characteristic feature of the
decision-formulation process is that of mutuality in
decision-making with final authority residing in the hands
of the group workers themselves."

Other projects and experiments and evidence which indicate
that modern work can be organized in this manner and still
be compatible with sophisticated technology, have been
collected by Hunnius, Garson, and Chase. See Workers'
Control,New York: Vintage Books, 1973.

And another example comes from the reports by E. L. Trist,
Organizational Choice and P. Herbst, Autonomous Group
Functioning. These authors describe the organization of work
in mining pits in Durham which was put into practice by
groups of miners.

   The composite work organization may be described as one
   in which the group takes over complete responsibility for
   the total cycle of operations involved in mining the
   coal-face. No member of the group has a fixed
   work-role. Instead, the men deploy themselves, depending
   on the requirements of the ongoing group task. Within the
   limits of technological and safety requirements they are
   free to evolve their way of organizing and carrying out
   their task. [The experiment demonstrates] the ability of
   quite large primary work groups of 40-50 members to act
   as self-regulating, selfdeveloping social organisms able
   to maintain themselves in a steady state of high
   productivity. 

   -- (Quoted in Colin Ward, "The organization of
   anarchy," Patterns of Anarchy,Krimerman and Perry, eds.,
   New York: Anchor Books, 1966) pp. 349-51.)

We believe that these small self-governing groups are not
only most efficient, but also the only possible source of
job satisfaction. They provide the only style of work that
is nourishing and intrinsically satisfying.

-- APL: Self-Governing Workshops and Office
#+end_quote

