#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Distributed
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/deploy/deploy-distributed.org
  :Created:   2017-05-14T19:13@Prek Leap (11.642600N-104.919210W)
  :ID:        2ed1c23f-4cc3-456b-980e-68e0ea2b2cec
  :STAMP:     548036082.339342102
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:IMB1-3550
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

The thing is that it's natural to think that this is a zero-sum game
-- that if we break up the centralized web, that you won't be able to
make money.  The opposite is true-- right now VCs are putting money
into the building up existing companies -- that's the shell game they
were meant to play.  Angels are putting money into startups but they
are also small companies who want to be big centralized playas.  

Belong to the network -- and the money you make is amplified.  You
don't need millions -- make hundreds of thousands and the network will
make it functionally the same as millions -- but without the shallow
consumerism, without the brutal hours -- you won't have to be a
corporate employee drone and you won't have to be a wanker scrambling
after a hoard of ducets at the expense of others.  A good life is a
good payout.

It's not a utopia but we can at least shoot for something that is at
least egalitarian.  And those who don't want to, or can't play the
game should at least be able to maintain a basic existence -- with
food, shelter, education and medical care. Because that gives us
stability and a means for people to do different things at different
times in their lives.


* Internet

 - [[http://spectrum.ieee.org/view-from-the-valley/telecom/internet/hbos-silicon-valley-joins-the-push-for-a-decentralized-web][HBO’s Silicon Valley Joins the Push for a Decentralized Web]] | IEEE
   Spectrum
 - [[http://spectrum.ieee.org/view-from-the-valley/telecom/internet/the-fathers-of-the-internet-revolution-urge-todays-pioneers-to-reinvent-the-web][The Fathers of the Internet Revolution Urge Today’s Software
   Engineers to Reinvent the Web]] | IEEE Spectrum
 - [[http://brewster.kahle.org/2015/08/11/locking-the-web-open-a-call-for-a-distributed-web-2/][Locking the Web Open: A Call for a Decentralized Web]] | Brewster
   Kahle's Blog

