#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Preservation
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/deploy-preserve.org
  :Created: 2017-04-24T16:28@Prek Leap (11.642600N-104.919210W)
  :ID: de316670-78e7-4677-9a2d-62d26327e8ff
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

Clay Shirky's SALT talk on preservation

  - [[https://www.youtube.com/watch?v=ujMgQqp8YSY][Making Digital Durable]] | Clay Shirky | SALT | YouTube

Shearing layer problem

  - Power
  - Architecture
  - OS
  - Dependencies
  - Interpreter
  - Format
  - Media


Preservation descisions are made in at the edge of networks.

Classification is about finding things

We label things because you can't see what's inside



* Copyright

#+begin_comment
Doesn't belong here
#+end_comment



People conflate many things with ownership

  sovereignty is not some magical power -- it is a recipricol social
  contract, if there are two countries and one believes it has
  sovereignty and the other doesn't, then there is no sovereignty

Copyright is a social contract that states that all creative and
intellectual works belong to the public commons, (public domain) but
in order to encourage the production of creative works, states grant
temporary monopolies on the right to reproduce or copy those materials
to the parties that hold the copyright on those works.  These
monopolies are not absolute -- and there are exceptions -- fair use is
the most important.  But there are others -- for example, in United
States law, copyright wasn't always automatically added -- it had to
be claimed, and two copies of the work had to be given to the library
of congress.

However, some individuals, and corporations believe that copyright =
absolute ownership and are basically screwing over everyone else by
doing all sorts of evil crap to cheat on the social contract that
gives them the monopoly.
