#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Interfaces
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/deploy/deploy-interface.org
  :Created:   2017-05-19T05:48@Prek Leap (11.642600N-104.919210W)
  :ID:        6da13a89-7693-4aba-b661-da8f47af7454
  :VER:       548419757.751734302
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:WLL5-8440
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction
* Device
* Application
* Descriptive & Proscriptive

 - [[https://craigmod.com/sputnik/as_we_may_read/][As we may read]] | Craig Mod
 - [[https://aeon.co/essays/stagnant-and-dull-can-digital-books-ever-replace-print][Stagnant and dull, can digital books ever replace print?]] | Aeon
   Essays


There is a reason that we switched from the scroll to codex.  The
scroll is a terrible interface and it's no different for physical
scrolls or web pages.  We still don't understand that yet.  Scrolls
really do suck at a lot of very basic things that for the codex is
easy.

Do books have branding on every page of the book, other than the
title?  Is the publisher's logo anywhere to be seen except on the
spine and cover page?  Then why subject us to logos on every web page
of a site?  The same goes for author info, links to other services,
like buttons or any crap in a persistent column.

Ebooks keep the clutter down to what it should be.  The iPad
interface, where you can  tap a page to show navigation and where you
are overall in the text is good (needs to be improved but it's good)

The biggest single factor working against ebooks and web pages is that
they are designed to reflow to fit the container that they are in.
Display device makers don't seem to put /any/ thought about how the
size of a screen effects the content shown on it because the web has
separated form factor from content.  This was not always so.

Plain text email is a case in point.  Email messages are written in
plain text with a monospaced font that is typically composed at about
60 characters per line.  This line length worked well in most
terminals and terminal emulators.


Desktop web browsers can be resized to anything the user wants -- so
we get a lot of people who for some reason think it's a good idea to
maximize every window, even if the display is 30" wide and the content
is only a third of that.  Even worse are web sites that will allow
lines to be infinitely long so you get 50 words to a line.  So you
have this perfect storm where the devices are all different sizes, the
windows on those devices are resized indiscriminately and the content
makers each decide what form factor they design for.  These are
unforced errors -- and it results in really crappy interfaces and
reading experiences.  And most important of all, it makes it nearly
impossible to take advantage of the most powerful features that the
codex gives us.


mobile devices are a round peg in a square hole -- we are trying to
fit things onto tiny screens that don't and won't and can never fit.
people are being told that you can do everything on your mobile device
-- they are wrong in the worst way possible.

** Hypercard

 - [[https://en.wikipedia.org/wiki/Hypercard][HyperCard]] | Wikipedia
 - [[https://arstechnica.com/apple/2012/05/25-years-of-hypercard-the-missing-link-to-the-web/][25 years of HyperCard—the missing link to the Web]] | Ars Technica

The original Mac Hypercard got paging right -- there was no scroll
only pages.  This was largely possible because each screen was
designed to fit in the original Macintoshes tiny display.

** Plain Text Hypertext

The texinfo hypertext interface (and perhaps gopher, but I can't
remember) got a lot of things right that the web did not.

There is /some/ scrolling but there is definately a page model where
text is broken down into small chunks -- you don't get enormous
scrolls.
