#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Ecosystems
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/deploy-ecosystem.org
  :Created: 2017-04-10T18:47@Prek Leap (11.642600N-104.919210W)
  :ID: 2b079fc0-31e1-443b-b103-dc3ffdab1582
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

I was originally going to break this up into /ecosystems/ and
/polyculture/ (can't use the fucking 'P' word now can we).  But in a
larger context, polyculture is simply a more complex means of what
early North American inhabitants did, they managed ecosystems.
European farming is based on monocultures that ignore that they are
part of a larger ecosystem.  Polyculture at its best, integrates 
with and manage local ecosystems.  At worst Polyculture at least
attempts to mimic natural ecosystems and create far more robust
interdependent systems than monocultures do.

Natural systems are certainly not perfect, they are constantly going
in and out of balance as climate and environmental factors change.
Animals and plants succeed, die off and eventually go extinct through
all of this.
