#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Social Structures
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/deploy-social.org
  :Created: 2017-03-28T11:19@Prek Leap (11.642600N-104.919210W)
  :ID: 2ec9e76f-ed84-4b0f-82bd-e09326c6afd2
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

** division of labor

  -- [[https://en.wikipedia.org/wiki/%C3%89mile_Durkheim][Émile Durkheim]] - Wikipedia

#+begin_quote
Since a body of rules is the definite form which
spontaneously established relations between social functions
take in the course of time, we can say, a priori,that the
state of anomy is impossible wherever solidary organs are
sufficiently in contact or sufficiently prolonged. In
effect, being contiguous, they are quickly warned, in each
circumstance, of the need which they have of one another,
and, consequently, they have a lively and continuous
sentiment of their mutual dependence. For the same reason
that exchanges take place among them easily, they take place
frequently; being regular, they regularize themselves
accordingly, and in time the work of consolidation is
achieved. Finally, because the smallest reaction can be felt
from one part to another, the rules which are thus
formulated carry this imprint; that is to say, they foresee
and fix, in detail, the conditions of equilibrium. But, on
the contrary, if some opaque environment is interposed, then
only stimuli of a certain intensity can be communicated from
one organ to another.  Relations, being rare, are not
repeated enough to be determined; each time there ensues new
groping.

-- The Division of Labor in Society,
   [[https://en.wikipedia.org/wiki/%C3%89mile_Durkheim][Émile Durkheim]], The MacMillan Co. 1933, Free
   Press edition, 1964
#+end_quote

#+begin_quote
This is what happens in the cases we are discussing. In so
far as the segmental type is strongly marked, there are
nearly as many economic markets as there are different
segments. Consequently, each of them is very
limited. Producers, being near consumers, can easily reckon
the extent of the needs to be satisfied.  Equilibrium is
established without any trouble and production regulates
itself. On the contrary, as the organized type develops, the
fusion of different segments draws the markets together into
one which embraces almost all society. This even extends
beyond, and tends to become universal, for the frontiers
which separate peoples break down at the same time as those
which separate the segments of each of them.  The result is
that each industry produces for consumers spread over the
whole surface of the country or even of the entire
world. Contact is then no longer sufficient. The producer
can no longer embrace the market in a glance, nor even in
thought. He can no longer see its limits, since it is, so to
speak, limitless.  Accordingly, production becomes unbridled
and unregulated. It can only trust to chance, and in the
course of these gropings, it is inevitable that proportions
will be abused, as much in one direction as in another.
From this come the crises which periodically disturb
economic functions. The growth of local, restricted crises
which result in failures is in all likelihood an effect of
the same cause.  As the market extends, great industry
appears. But it results in changing the relations of
employers and employees. The great strain upon the nervous
system and the contagious influence of great agglomerations
increase the needs of the latter. Machines replace men;
manufacturing replaces hand-work. The worker is regimented,
separated from his family throughout the day. He always
lives apart from his employer, etc.  These new conditions of
industrial life naturally demand a new organization, but as
these changes have been accomplished with extreme rapidity,
the interests in conflict have not yet had the time to be
equilibrated.

-- The Division of Labor in Society, [[https://en.wikipedia.org/wiki/%C3%89mile_Durkheim][Émile Durkheim]], The
   MacMillan Co. 1933, Free Press edition, 1964
#+end_quote




** the doomed

The present generation or two is likely lost, people can
only change so much over a lifetime and what we are asking
of people is beyond the cognitive capability for most
people.  I am /not/ saying these people are dumb, but they
were dealt a shitty hand.  This has happened over and over
throughout history, and there has never been a recorded
instance where the majority of these doomed generations are
able to escape their fate.

This doesn't mean we don't try to reach as many people as
possible, even as we rethink what it means to have the
minimal education in a technologically advanced civilization
in order to live a productive and meaningful life.

This doesn't address how we can help the doomed to live at
least a comfortable life.  This is not the place to go into
these kinds of scenarios, but the robotics revolution
together with AI will not only put the doomed out of work,
but will also provide the wealth needed to provide the
doomed with a univeral basic income and a hopefully less
destructive consumer lifestyle to the end of their days.
This is no Utopia, because humans suck at executing on
things that are in their collective interest.

And as anyone who has watched /any/ science fiction film
will know, that this risks an elite class emerging who will
have opportunities and advantages over the doomed.  We do
not want Nanny States, no matter how safe they may be, it
only makes things worse, makes people feel trapped and when
people feel frightened or trapped they turn violent.  At the
same time we can't simply try to keep them sated and docile.
Perhaps that will work for some but it's a terrible waste of
life.

Clay Shirky wrote of how each technological revolution
created a /cognitive surplus/ of free time.

The first of these revolutions resulted in at least one
generation drinking themselves to death.

#+begin_quote
An examination of the Gin Acts and crime would be incomplete
without reference to poverty and the role poverty played in
exacerbating the problems that arose in London related to
gin consumption. Most people who drank gin were among the
citys working class poor. Since the poor were small,
malnourished, and lived in an unsanitary environment, they
were ill equipped to metabolize the large quantities of
alcohol gin delivered.23 Gin provided refuge and comfort
from the harsh realities of daily London life.24 Gin helped
relieve the pains of adaptation to unfamiliar and
increasingly industrialized work routines and to unhealthy
living conditions in a city that had few recreational
outlets beyond the gin-shop.25 Evidently, the infrastructure
of the day was inadequate to meet the complex challenges
posed by a modern city life characterized by an increasingly
heterogeneous population26 and the dislocation of the
industrial revolution served to heighten the social and
medical problems of excessive gin-drinking.

-- [[https://web-beta.archive.org/web/20080202074611/http://culturalshifts.com/archives/168][The Gin Craze: Drink, Crime & Women in 18th Century London]] | Cultural Shift(s)
#+end_quote


#+begin_quote
in beginning the Gin Craze; as the price of food dropped and
income grew, consumers suddenly had the opportunity to spend
excess funds on liquor.

-- [[https://en.wikipedia.org/wiki/Gin_Craze][Gin Craze]] | Wikipedia
#+end_quote


The second was the Sitcom where generations sat every
evening eyes glazed in front of televisions.  I was a part
of that generation, and spend an astonishing amount of time
sitting with my parents and sister every night watching the
television from after dinner until it was time to go to
sleep.  I was lucky enough to break away from the cycle in
high school and spent more time reading and writing (outside
of school assignments and homework) than in front of the TV.
And in daylight hours I did everything from raise chickens
and sell eggs, to setting up a logging company.

Now it's Facebook -- but facebook is far more problematic,
and potentially more destructive than Gin.

Shirky saw this as a positive thing and that the Internet is
giving people the means of production.  This is true to a
point, but it does not give people the tools to think that
provide people with the discipline and responsibility that
comes with the means of production.  It's that tired tag
line from Spiderman, "with great power comes great
responsibility."  And the Internet is handing everyone that
power without telling them that it comes at a cost,
sometimes a terrible cost that, for many people, if they
knew what that cost was, wouldn't want to pay.

Having one without the other is a recipe for disaster.

In his 2017 annual speech at SXSW, Bruce Sterling outlined a
number of different scenarios of what this might look like,
and it's not all bad.  Not all good either, but there is
hope of a kind for a meaningful life for the doomed who are
left behind.

  - [[https://soundcloud.com/officialsxsw/the-future-history-that-hasnt-happened-yet-sxsw-2017][The Future: History that Hasn’t Happened Yet]] | SXSW 2017 | SoundCloud
  - [[https://www.wired.com/beyond-the-beyond/2017/03/bruce-sterling-speech-sxsw2017/][Bruce Sterling speech at SXSW2017]] | WIRED

Sterling's Univeral Basic Income (UBI) Scenarios:

   1. Reservations -- ala American Indian Reservation
   2. Prison Systems and Labor Camps -- liquidate entire social classes 
   3. Refuge Camps -- $1,200 per person per year
   4. The Armed Forces -- you get a job, barracks, a uniform,
      orders.  People are in shape, they have meaningful work etc.
   5. Retirement Villages -- 
   6. Universties -- not conventional economies but people
      are busy
   7. Religion -- monasteries & nunneries
   8. Hospitals & Spas -- people concentrate on health and
      well being
   9. Intentional Rural Communes -- romantic and never works
  10. Dropout Urban Bohemia -- lifestyle isn't
      self-supporting, 
  11. Enlightenment -- roam the earth -- can't really raise
      children

Sterling is very much a part of the technosphere as a sci fi
writer and futurist.  So he may not see that there might be
another way...

We don't really have a word for today's family unit.  A few
decades ago we had the 'nuclear' family, but this seems to
be breaking up to the point where there is no atomic unit
beyond individuals who have relationships at different
points in their lives.

The nuclear family a child of the industrial revolution.
Factories drew the young, ambitious and educated from rural
towns and villages to work in centralized factories and
business districts.  This broke up the extended family
which was a large unweildly construct that basically
consisted of everyone related to each other, productive or
otherwise.  The nuclear family was only possible if there
was a 'breadwinner' in the family who could support a spouse
and children, and perhaps support a parent or two from a
distance.  The breadwinner was basically on their own --
they could not fail or the family would fail.  No one helped
the breadwinner make money, the wife (the breadwinner was
almost always male in nuclear households) tended the house
and children who lived in a fake pastoral area outside of
the industrial or business areas, which had no opportunities
to do much of anything other than raise children.

Before suburban hell became the norm for the middle class,
it was single women who were the first to leave the villages
to work in factories.  The men at first stayed home, because
they were deemed to be too valuable to keep the family
enterprises going.  But eventually, the men followed as
well, emptying the villages of the young and able.

Compare this to a family owned farm, where most people
helped out in the family enterprise.  The school calendar
was arranged around plantings and harvests.  These family
enterprises provided for the productive and unproductive,
from infants to the sick and disabled to the elderly and
infirmed.  Nuclear families couldn't do any of this.  The
system excluded anyone who was not productive, or providing
a support system for productive people.

The extended family had some significant limitations as
well.  Large families who had many children who survived
found it difficult to start up their own family enterprises
because of their bonds to their extended family.  People
didn't travel or move very far.  This made families
inflexible and it was common for family members to pass on
opportunities because of their family bonds.

This kept villages inbred and stagnant.  Small towns work on
many levels, but they reward gossip, infighting and are
terrible places for people who are creative, or highly
intelligent who need different kind of support structures
and communities to realise their potential.

Family businesses are traditionally passed on to the eldest
son in a family along with the property and most of the
wealth as the torch is passed from generation to
generation.  But not all eldest sons have the talent, skills
or disposition to fill their father's shoes.

Perhaps we can evolve a new kind of extended family that can
resolve this contradiction, by providing a stable
cradle-to-grave group that will care for everyone in the
group, but also make it possible for people to be able to
travel, have access to broader communities and opportunities
at the same time.

Japan had an interesting take on family businesses.  If
there was not a suitable son to take over a family business,
then someone from outside of the family not only married
into the family but was adopted by the family -- taking
their name as well.  This has made possible some of the
longest running businesses in the world -- businesses that
are 500 years old are not the norm in Japan, but they do
exist.

The Japanese innovation is the 'salary man' -- employees who
in effect are adopted by a company and stay for life, with
the understanding that they will be taken care of for life
-- not just until they retire but life.  But again, there is
no flexibility or room for growth -- which has led to
corporate Japan becoming slow and inflexible.  In many ways
it's the same trap as the village and extended family.


** a robotic cottage industrial fabric

I'm thinking along the lines that shops (not all) could be
the equivilant of both an extended family and a japanese
corporation.  Each shop is owned by a small group of
extended families which the shops support for life.  This
requires *very* productive shops to be able to do this.  And
this is where automation, robotics and AI come in, so that a
small group of productive people, with a larger group of
semi-productive people and a lot of robots could do just
this.

But rather than each family (or collective or whatever)
relying on one shop, different members of the family will
belong to different and often overlapping shops -- some
primary full time, other will be secondary, seasonal,
part-time shops.

Leverage networks to coordinate transactions (and contracts),
communications, knowledge, supply chains, logistics and
orders.

And the thing is, that the more positive of scenarios on
Sterling's list could still be available as options for
people at different times in their lives.  Most would
eventually be pulled back into their family's orbits, and
those who aren't suited could wander the earth, or be weird
or join monastaries or armies or whatever....

But I don't think that massive centralized robotic factories
are where this is all going -- disruptive technologies break
up centralized structures and move power to the edges.
Robots will do the same thing -- but perhaps we can forstall
the next cycle of consolidation by moving away from consumer
industrial manufacturing and build stable institutions and
social structures that make sense for at least a few
generations. In a sense it would be a robotic cottage
industrial fabric -- it's not consumer but it's market
driven -- the goal is to give people a good life, healthy,
productive and meaningful -- not focused exclusively on
become rich as an end in its self.  In this kind of
structure, the super rich are not needed -- but this is only
possible if the ability to profit from power is taken away.
The people in power shouldn't want to be in power -- it is a
burden and a duty, not a means of making yourself rich.

Yes, this is a Utopian vision ... that will never be
realised.  But a messy system that mostly works is something
that we can achieve.  And without a big grand vision to
believe in and work towards, things won't get better.

The AI-Robot-Bio-Nano-Whatever tipping point is coming, and
we damn well be ready for it, because if we get this one
wrong it won't be pretty.  And it won't happen with
pitchforks and protests or suicide vests -- it will happen
with education, and conviction and individual commitment to
making a better world.  And if we can give people a sane
alternative to what they have now -- with security, a
future, meaning and purpose, I hope that enough people will
take that chance.  No one has been able to offer the whole
thing before -- everything has been based on voluntary
sacrifice -- the green movement isn't offering anything
attractive to people -- please suffer, even though most
people won't do what you do, to save the planet.  People
need education for their children and healthcare and a sane
standard of living.  Give them that, in exchange for giving
up consumerism and jobs that will be replaced by robots, and
crumbling infrastructure.  But they will also have to give
up racism, sexism, nationalism (in all forms) and
consumerism. In other words it's the golden rule, everyone
is your brother, and treat your brother as you would want
them to treat you.

  - [[https://en.wikipedia.org/wiki/Golden_Rule][Golden Rule]] | Wikipedia
  - [[http://www.ted.com/talks/karen_armstrong_let_s_revive_the_golden_rule][Karen Armstrong: Let's revive the Golden Rule]] | TED Talk
  - [[https://en.wikipedia.org/wiki/Charter_for_Compassion][Charter for Compassion]] | Wikipedia
  - [[https://www.charterforcompassion.org/][Charter for Compassion]] | Home


The golden rule needs to be one of the core tenants of any
constitution and philosophy of life.



#+begin_verse
You will not be able to stay home, brother.
You will not be able to plug in, turn on and cop out.
You will not be able to lose yourself on skag and
Skip out for beer during commercials,
Because the revolution will not be televised.

...

The revolution will not be right back
After a message about a white tornado, white lightning, or white people.
You will not have to worry about a dove in your
Bedroom, a tiger in your tank, or the giant in your toilet bowl.
The revolution will not go better with Coke.
The revolution will not fight the germs that may cause bad breath.
The revolution will put you in the driver's seat.

The revolution will not be televised, will not be televised,
Will not be televised, will not be televised.
The revolution will be no re-run brothers,
The revolution will be live.

-- Gil Scott-Heron | The Revolution Will Not Be Televised
#+end_verse

That's a lot of promises -- so they can't be promises -- we
have to give it to them on day one -- not a promise for a
bright future for their children after the revolution.
Those promises are never kept, because requiring that kind
of a revolution as a first step is doomed to failure and
misery and collapse.

The American Founding Fathers were big picture people who
planned for human weakness -- they were dreamers, but
practical ones.


---

Perhaps, we need to think of the institutions that make up
civilization to be contradictory ways of looking at the
world.  I don't want to just slot them into the Trivium
subjects here -- we need those contradictions, and to learn
to live with the uncertainty that those contradictions create.

  - executive
  - legislative
  - judiciary
  - watchdog
  - education
  - ...

These are not just providing checks and balances, they are
different perspectives of the world with different maps.  We
tend to think of them as having different priorities, which
is also true, but that may be missing as well -- perhaps
each needs a guiding philosophy that defines that worldview.


