#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Structures
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/deploy-structures.org
  :Created: 2017-04-03T16:49@Prek Leap (11.642600N-104.919210W)
  :ID: e6e5cf68-ff97-4f81-aee5-5d9bf8ef3a6d
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Scope

* Introduction

Building structures that provide shelter is certainly
nothing unique to our species.  Ants and termites tunnel and
build elaborate colonies, bees build hives.  Birds have been
building nests since they were dinosaurs.  Structures are a
natural extension of basic survival instants.  If there is a
choice of staying out in the rain or in a dry shelter, those
who gravitate for the less hostile environment will have a
better chance of survival.  Most shelters are used primarily
to better the chances of their offspring to survive when
they are young and less able to survive in the open.

Early man was adept at wandering the planet, and the ability
to construct garments which extended environmental extremes
of hot and cold in which man could survive was coupled with
structures that extended that protection even farther and
afforded some protection against predators.

The structures we build are extensions of ourselves as
individuals and culturally as groups.  They play an enormous
role in how we percieve the world around us, and shape what
activities that we are able to conduct from day to day.

It is fair to say that mankind is an indoor species whose
primary activity outside of the structures we build for
outselves is to travel to other structures.  Even
transportation evolved to become essentially moveble
structures, so that some one living in a an extremely hot
and dry climate such as you find in the middle east or
southwest United States spend their days going from an air
conditioned house to an air conditioned car to an air
conditioned shop and back to the air conditioned car and
then to an air conditioned office.  The amount of time spent
out of doors for many people living in cities like Pheonix
or Abu Dabbi is so small that in practice, they might as
well be living in man made habitats on Mars.  You'll still
be able to go outside once in a while, you'll just need a
tad more clothing to survive in antarctic temperatures
and.... a portable pressurized atmosphere.

* What the hell happened in the 20th Century?

For a species that depends so completely on the structures
we live in, it is almost beyond comprehension how fucking
awful we have been at making them for the past hundred
years.

Modernism, which striped any connection that people had with
the nature and our environment, has been responsible for
striping the lives of billions of people bare of their own
culture and humanity.  Modernism is souless, bland,
uncomfortable and far more disfunctional than most people
realise because they have never known anything else.

In the 1990's Hong Kong ran a series of public service
commercials that showed before and after scenarios of life
in Hong Kong.  In the before scenario we see a vibrant
street scene with food carts, and people laughing and joking
and looking pretty happy, though they are packed together in
a way that could only be normal in Hong Kong.  In the after
scenario, the carts and the people are gone, and you see a
single adult holding a child's hand as they walk across an
empty street.  It's so empty, that if it was an American
Western film, you'd see a tumbleweed rolling across behind
them.  The /bad/ scenario had all the things that had made
Hong Kong such a vibrant and alive place to live.  The
/good/ scenario looked more like the empty streets that you
see in Zombie movies just before the undead come streaming
out of the abandoned buildings to feast on your brains.  At
some point, on some unconscious level, the makers of the
commercials must have understood this as well and added in
/dangerous/ things happening in the /bad/ scenario.  The
worst, was a police raid on the pushcarts that forced the
hawkers to flee the scene, splashing hot oil on a little
girl and burning her.  They didn't seem to realise that the
only reason this happened was because of the police trying
to clear the street for the zombies to come.

What the government was really trying to do was to turn Hong
Kong into Singapore who had already, a generation before,
turned their city-state into a sterile /after/ scenario
where any street life is carefully managed and choreographed
in a strange parody of people living in a healthy living
culture.

This same process has since been repeated in countless
cities around the world, sucking the life out of each place
where it has been done.  This has become the new normal, and
again, few people understand how awful it is.

Christopher Alexandar dedicated his entire life's work to
rediscover what had been lost and develop methodoligies for
modern people to build structures that enhanced people's
lives rather than dehumanized them.  The resulting book, /A
Pattern Language/ became one of the largest selling books on
architecture in history.  APL is a singular masterpiece,
that should have sparked an architectural revolution that
changes the direction of modern architecture.  But the
buildings that were building using APL, if anything were as
bad or worse than what he wanted to replace.  People treated
the work as a cookbook of ideas, that they could dip into
here and there and make a building.  It turns out that there
were far deeper things happening in good buildings that
people had forgotten.

Over the next decades Alexandar dedicated to discovering
what those deeper patterns were, and how to create buildinds
that embodied and expressed them.  The result was a
monumental three volume work called "The Nature of Order".
In TNOR Alexandar attempted something astonishing, to not
only discover what we lost in the modern era, which was a
deep emotional and physical connection between ourselves,
our buildings and the world they are part of.  He sought to
take what he discovered out of the realm of /gut feelings/
and put it on an empirical scientific footing.

I believe that Alexandar's work will someday be thought of
as akin to the work of John Hooke's early scientific
achievements.  Like Alexandar, Hooke was the first to
discover a wide range of things without anything to guide
him in what he found.  Everything was new.  So it's not
surprising that the first pass of huge swaths of scientific
enquiry was wildly off the mark.  But Hooke, like Alexandar
laid the groundwork for the hundreds of thousands who would
come afterwords and build on his work.


* ----

#+begin_quote
... the contrast between these two buildings in fact offers
a brilliantly concrete demonstration of the dual premises
that underlie her book. The first is that architecture
possesses what she describes as a profound capacity to "make
a difference"—to exert a fundamental influence on our
quality of life by literally shaping our activities and
experiences. The second is that this capacity is best
understood not in the abstract terms of aesthetics or
history but by looking closely at the actual mechanics of
our daily interactions with buildings; by trying to
understand how we live in and move through them.

- [[http://www.bookforum.com/inprint/024_01/17556][If These Walls Could Talk]] | bookforum.com, Julian Rose, 2017
  book review of You Say to Brick, The Life of Louis Kahn
#+end_quote


#+begin_quote
"You say to brick, 'What do you want, brick?' . . . Brick says to you,
'I like an arch.' If you say to brick, 'Arches are expensive, and I
can use a concrete lintel over an opening. What do you think of that,
brick?' Brick says, 'I like an arch.'"

-- [[https://en.wikipedia.org/wiki/Louis_Kahn][Louis Kahn]] - Wikipedia
#+end_quote

#+begin_quote
Drawing on speeches and letters from Kahn's time in Dhaka supervising
the construction of his design for the National Assembly Building of
Bangladesh, Lesser suggests that he saw the project not merely as
providing a site for the young nation's parliament to meet but as
physically establishing democracy there—as if the spatial
configuration of his building would bear as much responsibility for
good governance as the legal structure of a constitution.

For Kahn, the ultimate source of architecture's power was its ability
to communicate. He believed that buildings are composed of "universal
elements" that have remained essentially unchanged throughout the
ages, and so constitute a kind of ancestral spatial language shared by
all of humanity.

- [[http://www.bookforum.com/inprint/024_01/17556][If These Walls Could Talk]] | bookforum.com, Julian Rose, 2017
  book review of You Say to Brick, The Life of Louis Kahn
#+end_quote

