#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Legibility
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/deploy-legibility.org
  :Created: 2017-05-02T09:52@Prek Leap (11.642600N-104.919210W)
  :ID: bbd1006c-af47-4e03-9c6f-63f3cdec5007
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

 - [[https://en.wikipedia.org/wiki/Seeing_Like_a_State][Seeing Like a State]] | Wikipedia
 - [[https://en.wikipedia.org/wiki/Panopticism][Panopticism]] | Wikipedia

 - [[https://en.wikipedia.org/wiki/Seeing_Like_a_State][Seeing Like a State]] - Wikipedia
 - [[https://www.cato-unbound.org/issues/september-2010/seeing-state-conversation-james-c-scott][Seeing Like a State: A Conversation with James C. Scott]] | Cato Unbound September 2010

 - [[https://en.wikipedia.org/wiki/Census][Census]] | Wikipedia

 - [[https://en.wikipedia.org/wiki/Cellular_democracy][Cellular democracy]] | Wikipedia

Legibility is a term (that may have been) coined by James
Scott, which refers to the mapping of land parcels,
organizations and people for the purpose of making them
knowable by the State.

I will make the argument that in the machine and computer
age making things legible is no longer /only/ an imposition
by States on traditional complex societies, but is something
that needs to be done and used by everyone, and that a
fine-grained, multi-layer, distributed, federated, and
transparent map that provides for a reasonable expectation
(as opposed to absolute) of privacy must become one of the
fundemental cornerstones of a technologically advanced
civilization.  When such maps become the proprietary data
hoards of the state and monster companies like Google and
Facebook, it will inevitably lead to power and wealth
ibalences that can not be corrected short of extraordinary
measures.  In fact, Google and Facebook arguably know more
about us than the state.  It recently was revealed that
Facebook now is selling advertising based on the emotional
state of mind of teens.  Much of this is because it is no
longer enough for institutions to require legible maps, but
every organization and individual needs them as well which
are also legible to all cognitive machine systems.

--- 

As many of the functions of the State are being replaced by
commercial corporate entities, it is interesting to see that
corporations have the same problem of legibility that the
state does.  Companies need to make their production as well
as their customers legible.  So it is not surprising that
companies such as Google and Facebook collect as much
information about their users as the States people live in.
In many respects such recorded surviellance surpasses the
wildest paranoid fantasies of States....




* A broader concept of legibility

Legibility doesn't work at all scales, but then that's sort
of the point.  The pre-industrial state was legible at local
scales, but because there was no standardization across all
locations, it didn't scale at all at the state level.

So legibility is closer to physical paper maps that show
different detail at different scales.  To those wtih an
administrative mind, the ideal is that the same standards
apply across all scales.  But that's where we run into
trouble because we're talking about maps, and maps are as
much about what is left out as they are about what is put
in.

The problem is that the administrative mindset sees the map
as the territory, they ignore what isn't included because
their objectives are narrow and clear.  However, the world
is not narrow and it is not clear and it is always in the
process of becoming something else.  Maps are simplified
snapshots that illustrate patterns.  This is an incredibly
powerful tool.  But again, the map can never be the
territory.  So legibility can not be seen as an end in
itself, it can never be complete, and once you make the
mistake of thinking it is, things start going very wrong.

In the map-territory relation, the map is expressed as
legibility, an overlay of labels over a representation of a
territory.  Man has always had a strong belief that naming
something gives you power over the thing named.  This goes
to the heart of those who crave power, who are often
portrayed pouring over their maps and globes -- as if the
maps themselves game them dominion over the things that they
represent.  This is the very essence of the concept of
sovereignty of ownership that binds together all of those
who will do violence on their behalf.  But all the soldiers,
police, jackboots, thugs, mandarins and civil servants as
well as the ships, planes, artilery, factories, cities and
the subjects that man or inhabit them are just abstract
statistics to those at the top.  For them, all there is, is
their maps and the whispers of what their sovereign leader
should see in the map.

#+begin_quote
The cadastral map is an instrument of control which both
reflects and consolidates the power of those who commission
it.... The cadastral map is partisan: where knowledge is
power, it provides comprehensive information to be used to
the advantage of some and the detriment of others, as rulers
and ruled were well aware in the tax struggles of the 18th
and 19th centuries. Finally, the cadastral map is active: in
portraying one reality, as in the settlement of the new
world or in India, it helps obliterate the old.

-- Roger J. P Kain and Elizabeth Baigent, The Cadastral Map
   quoted in Seeing Like A State
#+end_quote

The contradiction between map and territory goes to the
heart of administration -- when an administrator begins to
see their maps as tools for control.

Ideologies and dogmatic religious belief systems are always
loosing sight of this.  They have stopped seeing the world
around them and only look at the map -- at the flickering,
flattering reflection in the pond, or the tiny image in the
viewfinder before the shot it snapped, and frozen and
instantly is a misrepresentation of the present, because the
world has already moved on and become something else.

This is the curse of the observer -- observations are only
true in the moment of observation, even as the shearing
layers are ripping it all apart into a new fleeting
configuration.

#+begin_quote
The cadastral map is very much like a still photograph of
the current in a river. It represents the parcels of land as
they were arranged and owned at the moment the survey was
conducted. But the current is always moving, and in periods
of major social upheaval and growth, a cadastral survey may
freeze a scene of great turbulence. Changes are taking
place on field boundaries; land is being subdivided or
consolidated by inheritance or purchase; new canals, roads,
and railways are being cut; land use is changing; and so
forth. Inasmuch as these particular changes directly affect
tax assessments, there are provisions for recording them on
the map or in a title register. The accumulation of
annotations and marginalia at some point render the map
illegible, whereupon a more up-to-date but still static map
must be drawn and the process repeated.

-- Seeing Like A State | Scott
#+end_quote


In the end, I believe that the problem of legibility
demonstrates how large something can scale before those at
the top are hopelessly out of touch with those at the
bottom.  These are very real cognitive boundries -- we can
only relate to people a few degrees of separation from us at
most.  Once you have passed beyond two to three levels the
system has lost its humanity.  We need to recognize and
organize ourselves at human scales.  This is not just true
of states, but of corporations, and institutions.

* State Legibility

As Scott lays out, in meticulous detail, legibility is all about
States and how they levy taxes, conscript soldiers

To do this they create cadastral maps that indicate property
boundries.  Each property is then entered into a land registry which
is used to levy taxes.  

The second tool is registration and taking regular census of the
population.

Since taxation and suppression of regime change is the only real
purpose for land and population registration.

For this to work, the State needed a number of things we take for
granted today but are actually only historically recent in many parts
of the world:

  - surnames: given names were often chosen from a small set of names.
    The Christians had names used in the old and new testaments etc.
    Surnames were often based on occupation, and or where someone
    lived, or based on a nickname that was given from a particular
    incident or proclivity or attribute.  Charles the Fat, Vlad the
    Impaler (:)).  But these were not official, and it was commong for
    people to be known by multiple names.  In some places in the world
    just as Jamaica, it is thought that knowing someone's true name
    gave magical power over that person, so it was common for people
    to be known by a nickname, so that in some cases you might know
    someone your whole life and never know that person's real name.
    My father is a case in point.  He was the baby of a large New
    England farm family, who named him George, because of family
    politics.  But no one in the family liked the name.  So his father
    took to calling him "Bud" which is short for "Buddy" which during
    Depression and World War II Era America was the equivilient of the
    term "Dude" in recent decades.  I never heard my mother or any of
    his family or friends refer to him as anything else than Bud
    Collins.  And to my cousins, he was always "Uncle Buddy".  After
    teaching at a school in Massachusetts for 20 something years, a
    phone call came through for my father (this is before mobile
    phones, so a primary school might have no more than 1-2 telephone
    lines).  When the secretary came into the teachers room she said
    "There is a call for George Collins".  My father stood up and one
    of the teachers, looking incredulous said, "his name is not George
    it's Bud!".  In a simular way, my first name is James, which was
    given to me because of family politics, but my father wanted to
    call me Bradford, which became my middle name and everyone who
    knows me, knows me only as Brad.  Many people assume it is short
    for the more common name Bradley.  Children who are given their
    father's name often are known by most people by a knickname.  A
    recent famous example of this are the father-son American
    Presidents, George Bush and his somewhat challenged son, George W
    Bush.  Most people who know him call him Dubya [fn:1] based on the
    Texas pronunciation of the letter 'W'.

  - measurement : this is a biiiiiig topic [which we will expand (to
    use a Trumpism, Bigly] -- but paying taxes were often based on
    percentges of what say a farmer produced.  So if the tax was 10
    baskets of wheat.  How big are the baskets? Are they heaped or
    leveled flat.  Are they filled by pouring from the waste or from
    the shoulder etc.  Measurement pretty much touches on every aspect
    of life from distances, to the age of a child (when a child is one
    year old is defined differently in different cultures), to how big
    a pint of lager is.  What is a pinch of salt, a dash of sherry,
    how tall is knee-high by the fourth of july?  When does a day
    begin or end?  At dawn and sunset?  Or by the amount of time the
    planet takes to rotate once?  What is a day on mars?  Or if you
    are living in a hollowed out rock in the asteroid belt, or on the
    moon?  How do you express how far something is?  Scott mentioned
    that in parts of Malaysia a village might be refered to as "three
    rice cookings" away.  And these non-precise measurements should
    not be dismissed out of hand -- they often communicate information
    that is far more useful than it would be using the standard metric
    system.  And our precious /precise/ measuring standards are often
    still expressed relative to and based on concepts no longer used
    any more.  We still refer to car engines in terms of multiples of
    /horse power/.  The english pound was originally calculated by
    weighing a pound of penny coins.  These are very human ways of
    relating to and understanding the world -- which still are
    important, and for good reason.  But as we will see later, it will
    be difficult to render such measurement systems machine legible
    unless AI advances to the point where such fungible measurements
    can not only be translated into metric standards, but the range of
    information that such measurements encompass.

  - citizenship : which is an attempt to make the very subjective
    concept of who belongs in a place and or as part of a group and
    who does not.  This is a very difficult and complex metric to pin
    down.  Does a woman who came from Harbin, who moved and married a
    man in Guangzhou belong in Harbin or Guangzhou?  Before or after
    she's bourne children?  How many years must you live in Kyoto
    before Kyoto people accept you as /being/ from Kyoto.  I was once
    told by a person who had lived in Kyoto 25 years that he was
    amazed that people there almost treated him the same as someone
    born in Kyoto....  In almost every place on the planet, the color
    of your skin, and often your religion are major factors in being
    accepted or not.  I was born in Germany where my parents had been
    working as teachers for the United States army.  My father's
    family was on the first ship of settlers that founded Plymouth
    Colony over 300 years ago.  And yet, because my passport gives my
    place of birth as Germany, I have been told that I was not a
    /real/ American by immigration and American consulate staff on
    multiple occasions.  I've been also asked when I became an
    American citizen.  And yet, if I obtained German citizenship, no
    German would ever mistake me, or my family name, as being German.
    Concepts like citizen, resident, tourist etc are highly simplified
    legible labels that only express a very small subset of how people
    are accepted and become part of different societies and different
    cultures around the planet.  The nation state has now been with
    us for two centuries (more if you count back to Westphalia) but
    the legible system that has now become the norm for nation-states
    still falls far short of the range of ways that people identify
    themselves and how others identify others.  


** mapping to stages of life

In [[https://en.wikipedia.org/wiki/The_New_Science][Scienza Nuova]] (The New Science) Giambattista Vico argued that
history could be seen as a cyclical in nature:

#+begin_quote
Giambattista Vico (1668-1774) is the author of /Principi di Scienza
Nuova/ (The New Science), in which is expounded his theory that a
common cyclical pattern identifies the histories of diverse nations.
The cycle consists of (i) the age of the gods, represented in
primitive society by the family life of the cave, to which God's
thunder had driven man; (ii) the age of heroes, characterised by the
continual revolutionary movements of the plebians against the
patricians; (iii) the age of people, the final consequence of the
leveling influence of revolutions.  The three ages are typified by the
institutions of birth, death, marriage and burial...

-- [[./bib:mchugh:1980annotations][Anotations to Finnegans Wake]] pg.v. | Roland McHugh
#+end_quote

States strive to make people legible by documenting the different
stages of people's lives: birth, coming of age, marriage, and death.

Birth certificates are used as a marker of when a new person enters
the world, the registered name of the newborn, date and time of the
birth, the place of the birth and the parents of the newborn.  In this
way, everyone in the state becomes legible at the moment of birth
which is recorded in a registry, often with some additional
information such as biometric hand and foot prints.  Religious
institutions also keep their own registry of newborn children through
devices such as batismal registries.  Before birth registries became
ubiquitious, it was common for the only record of birth to be kept by
the Church.

Coming of age rituals are not strictly speaking, registered by the
state because they are often defined in law to be a statutory age that
grants them the rights and obligations of an adult.  For the state
this is the point when people are expected to pay taxes and are
subject to conscription.  However, there are a number of orthoganal
registrations that are important to the state.  In modern states the
two most important of these are institutional educational diplomas,
certificates and degrees, which are meant to allow the state to know
what level of education and or skills an individual has.  The second,
is the driver's licence (and or id card).  In industrial societies
these were needed to determine if people where qualified to work in
factories or offices.  Religions /do/ have formal coming of age
rituals, that are also registered and mark the age when a person
enters adulthood.  The ages that these rituals take place were set in
previous ages when human lifespans were far shorter than  today, so
that they often take place sometime after the onset of puberty.
Modern states have extended childhood to well after puberty, and don't
give people full adult rights as late as 21 or 22 in the case of being
allowed to purchase and consume alcohol.  Though the minimum age for
conscription is still at a younger age.

Marriage certificates are also registered with both States and
Religious institutions.  The chief reason for a State's interest in
marriage is that it is customary for a person to change their name
after marriage, so that the State needs to map the change of a
person's name from before they were married to their new married name.

Finally comes the death certificate, which quite literally closes out
the person from the State system, and is needed for managing the
transfer or wealth and goods that had been left at the time of death.
Just as importantly, it limits liability from being transfered from
the person who died to a spouse or children.  There are many societies
throughout history who believe that acts of the parent are passed on
to their children.  In fact, the entire Hebrew and Christian religion
is based on this strange concept.  That everyone alive to day, is
responsible for the actions of the first man and woman.  Sin is
inherited, even after thousands of years have passed.  The chirstians
are certainly not alone in holding such strange beliefs which are
still very strongly held even today and show up in concepts like
/honor killings/ in India, to inter-clan multigenerational feuds and
vendettas from the Appalachias to Cebu.


** pooh-bah legibility

#+begin_quote
Marauders can instead be what Mancur Olson called “stationary bandits”
— powerful pooh-bahs or other officials who (for whatever reason)
enjoy the allegiance of organized groups of men specialized in using
physical force. (These specialized groups are indeed overwhelmingly
made up of men — mostly young men.) Each stationary bandit, be it an
individual or a team, relies upon these groups to gather resources
from the population and to suppress insurrection. The more synoptic
are the names of roads, bridges, valleys, villages, and the like, the
better able are stationary bandits and their troops to keep the local
population in line.

-- [[https://www.cato-unbound.org/2010/09/10/donald-j-boudreaux/promiscuous-productive-ideas][Promiscuous, Productive Ideas]] | Cato Unbound
#+end_quote


J. Bradford DeLong makes the argument that :

#+begin_quote
Thus when James C. Scott speaks of how local knowledge and local
arrangements having the ability to protect the people of civil society
from an overmighty, blundering state, I say “perhaps” and I say
“sometimes.”

-- [[https://www.cato-unbound.org/2010/09/16/j-bradford-delong/perhaps-sometimes][Perhaps. And Sometimes.]] | Cato Unbound
#+end_quote

When there are are parts of a state which are illegible, it is not
uncommon for bad actors to move in and ride roughshod over the
population.

#+begin_quote
A state that makes civil society legible to itself cannot protect us
from its own fits of ideological terror, or even clumsy
thumb-fingeredness. A state to which civil society is illegible cannot
help curb roving bandits or local notables. And neither type of state
has proved terribly effective at constraining its own functionaries.

-- [[https://www.cato-unbound.org/2010/09/16/j-bradford-delong/perhaps-sometimes][Perhaps. And Sometimes.]] | Cato Unbound
#+end_quote

** Insane State Legibility

It shouldn't be forgotten that state legibility has been the hallmark
of many of the most horrific state atrocities in modern history.

  - Hitler
  - Stalin
  - Mao
  - Pol Pot
  - Suharto ?
  - The Inquisition
  - Pinoche ?

  - Central America ?
  - Stazi
  - Cuba ?

  - J. Edgar Hoover
  - McCarthy's list

  - USA's no-fly list, and watch-list 

This seems to be standard practice for nationalist, extreme religious,
and racist groups.

The act of documentation seems to be an important psychological
crutch, that by putting down someone's name, and taking a picture, in
a list of 'enemies' that you have justified in your mind what you do
to them.   After all, they must have done /something/ otherwise they
wouldn't have been on the list....

But in all of these cases, legibility was not just justification, it
was part of a pathological logic and drive to be thorough and
complete.  They weren't crazy, their methods were proof of that....

What's also interesting is that many groups who later come to believe
the same things that had led to all of these horrors desperately try
to deny that these things had happened before, or that they are
advocating such actions.


** causal legibility

In many respects, legibility is not far more important to non-state
institutions and then to the state.  States still don't need much more
legibility today than they did during the industrial revolution taxes,
conscription and repressing insurrection are still pretty much the
same.

Repressing insurrection has now been largely combined with control of
borders and repelling invading forces who wish to conquer the state.
And this is where things become interesting.  It has only been very
recently that states have felt the need to make individuals from other
States as legible as their own citizens.  Percieved existential
threats to a state may take the form of small bands of indivduals who
are responsible for removing wealth from a country without paying
taxes, importing banned goods, and ideas into a state, and intentional
violent acts on citizens and organizations from a state both inside
and outside the state.  In a word, surveillance.

Mapping the causal chains of what people do, has now become standard
practice for both states and private organizations.

* Transactional Legibility

That transactions need to be legible, unstrusted,
transparent, and, public.  but since there are any number of
roles in our lives which are not public in the large,
transactions in these domains have a reasonable expectation
of privicy -- this is the panopticon problem.





* Machine Legibility

To machines, the world is pretty much completely illegible
beyond the /very/ simple vocabulary and base knowledge that
it has to work with.

* Human Legibility

* Agro/Eco Legibility

* Community Legibility

* Private Legibility

* Footnotes

[fn:1]  Grimes, David (1 Feb 2001). "Dubya's nickname could be
worse". The Oklahoma City Journal Record. Retrieved 25 Mar 2010.

Cited by : [[https://en.wikipedia.org/wiki/List_of_nicknames_of_Presidents_of_the_United_States#cite_note-Grimes-117][List of nicknames of Presidents of the United States]] | Wikipedia
