#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Production
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/deploy-production.org
  :Created: 2017-04-30T14:34@Prek Leap (11.642600N-104.919210W)
  :ID: 0127e6e3-1307-43f3-903c-03a7af67a44c
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction



 - Industrial Revolution
 - Transport Revolution 1840-1890
 - Science Revolution 1860-1930

 - Cybernetic Revolution
 - 

- learning curve
 - experience curve

Peter Drucker -- flexible manufacturing

#+begin_quote
In manufacturing, affordable choice has taken a long time to
evolve. It has passed through four distinct stages, and is
now in a fifth. The different stages have always been based
on a balance between two approaches – customization and
standardization – and whether goods are made in small or
large amounts.

The /first/ of these phases was ‘low-volume customization’.
The period coincided with early glass-making. It involved
the first rudimentary processes to make products from other
materials such as wood, clay and metals. For the sake of
simplicity, this era can be said to have started with the
beginning of the Iron Age. It lasted for nearly 3,000 years,
until roughly 1500 ce.

....  the /second/ phase of manufacturing processes:
‘low-volume standardization’.  The period enabled production
workers to start making their goods on more of a repeatable,
consistent basis. Starting in 1500 in the Venice shipyard,
the era continued for 400 years. In interchangeable parts
production, groups of components are divided into
families. Inside each family, parts are identical.
Components made in this way are easier to assemble into a
product than parts made in a non-standard fashion. Parts of
this kind also lend themselves – at least in theory – to use
in production systems, permitting a lot of variation.

.... ‘high-volume standardization’ – the /third/ key stage for
manufacturing processes. The period lasted from 1900
to 1980.

.... Drucker’s term of flexible mass production means the
same as ‘high-volume customization’. This is the name given
to the process that features in the /fourth/ phase of
manufacturing. It started in 1980, a few years after Drucker
published his book. High-volume customization is also
sometimes referred to as ‘lean production’, or ‘mass
customization’. /The Machine That Changed the World/, a book
about the automotive industry, concen- trates on lean
production, a term coined in 1988 by Massachusetts Institute
of Technology researcher John Krafcik.18 In the book, Jim
Womack and his fellow authors define lean production as
combining ‘the advantages of craft production and
[inflexible] mass production, while avoiding the high cost
of the former and rigidity of the latter’. Lean production,
they say, employs ‘teams of multi-skilled workers at all
levels of the organization and [uses] highly flexible,
increasingly automated machines to produce volumes of
products in enormous variety’.19 A key concept is to
eliminate waste in terms of unnecessary stocks of spare
parts or complete products. Instead of having buffer
supplies of components throughout the process, parts ‘flow’
through the system – either by automated transfer mechanisms
or (more commonly) through people moving the components
around.20 They arrive at specific produc-

-- [[bib:marsh:2012new][The New Industrial Revolution]] | Peter Marsh (2012)
#+end_quote

 - /The Machine That Changed the World/ | Jim Womack
 - [[https://en.wikipedia.org/wiki/Lean_production][Lean manufacturing]] - Wikipedia
 - [[https://en.wikipedia.org/wiki/Just-in-time_manufacturing][Just-in-time manufacturing]] | Wikipedia

Of course, just-in-time is nearly the polar opposite of
anti-fragile -- but how to reconcile?  We have to rethink
how materials and goods are cached in the network.  Bangkok
floods disrupted subassemblies going to Japan, and final
products in the flood region.  It also cut off transport to
the provinces.  The network needs to somehow provide
inventories, that can last when something is disrupted, but
also be a futures market that orders and purchases in
advance.

#+begin_quote
Sepheri provides a list of methodologies of JIT
manufacturing that "are important but not exhaustive":[40]

 - Housekeeping – physical organization and discipline.
 - Make it right the first time – elimination of defects.
 - Setup reduction – flexible changeover approaches.
 - Lot sizes of one – the ultimate lot size and flexibility.
 - Uniform plant load – leveling as a control mechanism.
 - Balanced flow – organizing flow scheduling throughput.
 - Skill diversification – multi-functional workers.
 - Control by visibility – communication media for activity.
 - Preventive maintenance – flawless running, no defects.
 - Fitness for use – producibility, design for process.
 - Compact plant layout – product-oriented design.
 - Streamlining movements – smoothing materials handling.
 - Supplier networks – extensions of the factory.
 - Worker involvement – small group improvement activities.
 - Cellular manufacturing – production methods for flow.
 - Pull system – signal [kanban] replenishment/resupply systems.

-- [[https://en.wikipedia.org/wiki/Just-in-time_manufacturing][Just-in-time manufacturing]] - Wikipedia
#+end_quote

This is actually a good list -- which we can apply to
small-volume distributed manufacturing.

But this essentially needs to be handed over to AI and
robots.

I like Supplier networks -- extensions of the factory...

 - Sepheri, M. (1986). How kanban system is used in an
   American Toyota motor facility. Industrial Engineering,
   17(2), 50–56.


#+begin_quote
Generally the production of any good or service shows the
experience curve effect. Each time cumulative volume
doubles, value added costs (including administration,
marketing, distribution, and manufacturing) fall by a
constant percentage.
#+end_quote
   

#+begin_quote
Machines with interchangeable parts can now be constructed
with great economy of effort . . . [A radio set] is made by
the hundred million, tossed about in packages, plugged into
sockets – and it works! Its gossamer parts, the precise
location and alignment involved in its construction would
have occupied a master craftsman of the guild for months;
now it is built for thirty cents. The world has arrived at
an age of cheap, complex devices of great reliability; and
something is bound to come of it.

-- Vannevar Bush, ‘As we may think’, The Atlantic, July 1945.
#+end_quote

#+begin_quote
What constitutes a successful manufacturer is also being
redefined. Up to about 1990, production was considered by
far the most important part of the work of a manufacturing
business. Parcelling this out for other companies to take
care of was rarely contemplated. But in the early years of
the twenty-first century, the realization grew that making
products is just one part of the ‘value chain’ of company
operations. Others include design and development, and the
way products are maintained or ‘serviced’ after
installation. To be considered a great manufacturer, compa-
nies do not now need to make anything, even though they will
almost certainly know a lot about what this
entails. Increasingly, elements of the value chain are being
left to a variety of businesses in different countries.  The
management of this mix is becoming a highly prized skill.
In many product areas, opportunities are opening up as a
result of

-- [[bib:marsh:2012new][The New Industrial Revolution]] pg17 | Peter Marsh (2012)
#+end_quote

The important word here is skill -- companies like Apple
Computer don't do their own production any longer.  They
design products and then piece together the supply and
production chains.

What if what Tim Cook does effectively becomes a utility?


   [[https://en.wikipedia.org/wiki/Experience_curve_effects][Experience curve effects]] | Wikipedia]
   [[https://www.bcgperspectives.com/content/classics/corporate_finance_corporate_strategy_portfolio_management_the_experience_curve_reviewed_history/][The Experience Curve—Reviewed (Part II)]] | bcg.perspectives
   [[bib:marsh:2012new][The New Industrial Revolution]] | Peter Marsh (2012)

What I am concerned about is how we change the relationship
between the customer and production.

Retail is a terrible system -- and buying through Amazon is
even worse.  Amazon doesn't and can't understand the content
of what it is selling to.  At the moment all of that is the
responsibiility of the buyer -- to know what they need, and
what will solve their requirements and needs.  There are no
relationships any more between seller and buyer.  This is in
large part because mass production and mass retailing has
had economies of scale in their favor dropping prices and
providing access to a larger variety of goods than the old
local shop ecosystem was able to do.

But the amount of goods produced now outstrips the needs for
those goods, so consumer product cycles of deliberately
making goods that only last a few years, to force people to
replace them on a regular basis has become the norm.  This
is terrible for us as a species and as a planet.

I keep wondering -- if we returned to production of durable
goods that last -- how much we would save in terms of
resources and impact on the carrying capacity of our planet?

We have to bake this into our distributed system -- and do
it in a way that there is an incentive to do it this way,
and abandon consumer production models.

When we go to mars we can not use the model we are using today.

* Multiplying Workers


#+begin_quote
The plant, a two-hour drive southwest of Vienna, will need
just 14 employees to make 500,000 tons of robust steel wire
a year—vs. as many as 1,000 in a mill with similar capacity
built in the 1960s. Inside the facility, red-hot metal
snakes its way along a 700-meter (2,297-foot) production
line. Yet the floors are spotless, the only noise is a
gentle hum that wouldn’t overwhelm a quiet conversation, and
most of the time the place is deserted except for three
technicians who sit high above the line, monitoring output
on a bank of flatscreens.

....

Alongside a small creek on the valley floor, the €100
million ($111 million) plant turns 3-ton beams of steel
forged in Voestalpine’s blast furnaces next door into thick
wire used to make components such as shock absorbers and
piston cases in BMW, Mercedes-Benz, and Audi factories
across the border in Germany. While about 300 other workers
in Donawitz carry out support roles such as shipping
logistics and running the internal rail system, the rolling
mill itself will be operated by just over a dozen people.

-- [[https://www.bloomberg.com/news/articles/2017-06-21/how-just-14-people-make-500-000-tons-of-steel-a-year-in-austria][How Just 14 People Make 500,000 Tons of Steel a Year in
   Austria]] | Bloomberg
#+end_quote

Many of those support roles can eventually be automated as
well, as a lot of the front office work will become part of
the network. The article talks about plans to fully automate
another plant that has 2,500 workers.

Heavy industry is where traditional industrial techniques
that have been automated will become the norm.

The same will happen with any kind of industrial system --
but they will be making mass production products sold
through channels like Walmart and Amazon.  Cookie cutter
disposable goods.

What is needed is to take this kind of automation and apply
it to small scale production, so that production, supply and
logistitcs become distributed.

Steel will likely never be cost effective at small scales --
so the system will be a mix of large and small production.

There is production of materials like steel and then there
are machines that produce machines which then make consumer
goods.


We can't take away the means of production of material life
out of people's hands.  We are tool makers -- when we are
not making tools, and using them, we start to fall apart.  A
life of leisure is not for us, we get fat, lazy and fighting
amongst ourselves.  We need to shape our own world -- it is
not a matter of work, or even survival, it is how we make
sense of the world around us and find where we fit into it.
Work is purpose -- work without purpose is a waste of a life
just as a life with no work or purpose is just as worthless,
no matter how much money you have.


