#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Principles
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/deploy-principles.org
  :Created: 2017-04-01T19:37@Prek Leap (11.642600N-104.919210W)
  :ID: 0e2b6678-3aa1-445e-912d-e6944add9d61
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

This file may not belong in deploy....


* Introduction

Principles are sort of cardinal patterns

** Design

*** Distributed

Centralized is when all nodes point back to a single parent
node.  All roads lead to Rome.

It should be pointed out that there are no centralized
systems in nature, and even when systems in nature depend on
a single point of failure -- that will become one of the
most important causes of failure.  The heart is a good example.

Centralized systems are the easiest way to do things because
you only have to maintain a single set of things.  It's easy
to keep consistent and there is no problem with propagation.
Change something once, it's changed everywhere.  It's no
surprise that centralized systems are favored by those who
prize absolute control.  Ideologies are centralized, they
maintain a single set of facts and beliefs that everyone
must follow.  The same applies to monotheism -- if there is
only a single all powerful god, and that god is believed to
be absolutely good, then how to reconcile pain, suffering,
injustice and other evils in the world.  All sorts of
explanations abound in every monotheistic belief system, and
all of them strain credibility.  So by and large the
contradictions and paradoxes that emerge from monotheistic
belief systems are usually not thought about too much,
because when they are, bad things tend to happen and they
are used to justify some really terrible behavior.  The
chiristian concept of original sin has been used to demean
and repress women in more ways than could every be
documented.  But for original sin to work, the concept that
bad deeds are passed on, like genes from one generation to
another.  This is a wide spread belief throughout human
history.  The sins of the father are passed on to become the
sins of the son.  This is in direct contradiction with the
whole Christian belief that man was given free will.  Free
will means that everyone starts with a clean slate and it is
up to them to do good or bad.  It's never explained how the
sins of Adam and Eve are a curse on all descendents of Adam
and Even, which is everyone.  No one has a clean slate, and
so there are limits to free will - it is not absolute.  The
ancient Greeks would have had no problem with this --
because of their belief in fate -- what happens to us is
determined by outside forces we have no direct means of
knowing about.  But fate was not determined by a single god,
but through the complex and often capricious interaction of
many gods.  It was possible to seek help from one god,
even if another had it in for you.  So fate was not
absolute, and it was possible to influence your fate though
not become in control of it.  The universe is complex and
chaotic to the point where deterministic outcomes are a
matter of probability, which even the gods are subject to.
In many respects the decentralized Greek pantheon of gods is
a better fit with empirical reality than the monotheistic
systems.  But monotheism provides a simple model of the
world and that simplicity is far more comforting than the
messy reality TV shows that are going on on Olympus, or
Valhallah or wherever the Gods are supposed to reside.  It
is a rejection of complexity and contradiction.  It is a
binary system that doesn't reflect the world we experience,
no matter how comforting it may be.  Some of the aspects of
polytheism have hung on in all monothesistic belief systems
in the form of Saints, Angels and Demons.

Decentralized is when there are multiple centralized
networks, with each sub network pointing to a single node.
Decentralization is only slightly better than centralized
systems, because failure of any one sub net results in a
large number of dependent local nodes being cut off.  So
instead of a monopoly you get a duopoly or more.
Decentralized systems are more difficult to maintain than
centralized systems becuase each subnet has to be kept
consistent with the other subnets.  This is how civilization
has worked from the very beginning.  Until late last
century, there were always multiple civilizations on the
planet.  Each was a centralized system in its own right. But
becuase each civilization was largely isolated from the
others they could not provide the stability of a slower
layer that worked across all civilizations -- so when
cataclysms happened, the local effect was existential, but
typically didn't have much impact on other civilizations.
And after the collapse of a civilization, there was a vacuum
that other civilization would eventually fill.  This is
exactly when happened in North America when small pox killed
some 90% of the population on the continent.  After the
collapse, European civilizations moved in an established
themselves, and never allowed the survivors to rebuild their
civilizations.

This is good and bad -- it's good that those other
civilizations existed to rebuild, but the loss of those
civilizations and most of the knowledge and advances
that they had made were lost forever.  And for a significant
part of the species, the collapse was indeed existential.

Distributed is where every node can connect to any other
node and the knowledge is duplicated and distributed
throughout all nodes.  There is no single point of failure.
So even if a large part of the network is destroyed, the
rest of the network will continue on with little effect.
The network then only has to start rebuilding nodes to
restore the network that was there before.  It won't be
exactly the same network, but the loss is not existential.

The problem with distributed is that it is very different to
keep all nodes in sync with each other -- and at any given
time N number of nodes will not be in sync with each other.
This introduces errors which need to be identified and
corrected.  This is difficult to say the least.  But the
benifits are substantial.

In distributed systems there is no one in charge, so
consistency needs to be maintained through consensus.  And
everyone knows consensus is hard.  The danger is that nodes
or groups of nodes will fall so far out of sync with the
rest of the network that they end up breaking away from the
network to become a separate network, which defeats the whole
point of a distributed system.  Nature is made of a hodge
podge of centralized, decentralized and distributed systems,
some evolve to be stronger, others collapse and are replaced
by others.

The most desirable distributed system is an antifragile
system, which I suppose can be thought of as a healthy
distributed network, that responds to failures of individual
nodes and parts of the the network by learning from those
failures and becoming stronger -- and fixing those
weaknesses.  Weak and failed nodes, therefore actually make
the network stronger.  This requires a strong feedback
system and the ability for nodes to fix themselves and the
more more sucessful improvements propagating throughout
the entire network, making it stronger than it was before.

In a sense, this is what Life does through evolution.
Though the mechanism is messy and far from linear it is
clear that DNA is an antifragile system that uses randomness
to improve itself and become more robust.  This requires
time scales that are non-trivial timescales that are
significant parts of the age of the universe.  But, in fact,
our definition of dna based electro-chemical life is an
extension of everything that has happened since the big bang
-- the evolution of the universe made life possible.

***  
  - human readable
  - homoiconographic
  - gracefully degrade
  - standardized parts
  - modular (as in unix pipes)
  - repairable
  - upgradable
  - longevity (as a design principle)
** Social
  - golden rule



* They Used To Last 50 Years

 - [[https://recraigslist.com/2015/10/they-used-to-last-50-years/][They Used To Last 50 Years]] | ReCraigslist.com

