#   -*- mode: org; fill-column: 60 -*-
#+TITLE: 
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/deploy-markets.org
  :Created: 2017-04-03T17:18@Prek Leap (11.642600N-104.919210W)
  :ID: fbeea25d-d050-4ca1-9ff7-45fd28210a04
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

#+begin_comment
from: NOTES <2013-01-17 Thu 09:28> A supermarket free of consumerism
#+end_comment


Packaged food and the modern supermarket has turned food from a
commodity into a consumer product.

We must eat food to live.  It's one of the pillars of Maslov's
hierarchy of needs.

As Braudel pointed out, it's also true that historically, that diet
has been monumentally monotonous.  This was in large part because food
for the poor has been a matter of survival.

This changed in the 20th century, when dropping food prices was
matched up in countries like the United States with a wholesale
abandonment of traditional food markets and grocery stores which were
replaced by supermarkets.  This has gone so far that people had to
reinvent the word for the traditional wet market which were typically
outside markets with stalls selling fresh produce, meat and seafood.
They are now called "farmer's markets" because they were originally
billed as places where farmers could sell their produce directly to
the public.

The old system was actually not too bad.  You had grocers, a word that
came from Middle English for "a person who sold things in the gross".
Which were typically small family run affairs.  Then you had morning
and afternoon/evening markets.  The morning markets would sell
different things from the afternoon and evening markets. In south east
asia, you see morning and afternoon markets selling produce and meat
for cooking that day's meals.  Evening markets focused more on fruit
and cooked food.  You would by fresh noodles, yellow or red curry
paste from big tubs, you would get coconut milk from a stall with a
machine that would rim out the coconut in front of you, and press the
milk out into one bag, give you a second bag of water and a third of
the coconut meat.  You didn't have to buy prepackaged sizes, you could
buy by price or weight and ask for 10 baht of red chilies, or 1 kilo
of pork.

So in the evening you would buy fried chicken, hargao (a type of
chinese pork or prawn dim sum).

I think the name of the game here is to move production as close to
where it is sold as possible, and to leverage logistics and collective
purchasing and logistics using the network.  This will make them
collectively competitive with the supermarket, while improving the
quality of food, and life.

So a supermarket becomes not only a place for the individual to
purchase food for their cooking, but a collective for people producing
cooked and prepared foods to purchase raw materials and then, in turn,
have a place where they can sell their goods.

Eliminate all branded food -- and push people to use
reuseable-containers when purchasing.  So you would have two oil
bottles.  When you need oil you bring in the empty one and fill it up
from a barrel.  Hell, the place could even clean the one you bring in
first.

Move, whenever possible, vegitables and fruit sales back outside, and
get people to start having a relationship with the people they
purchase from.  Bakeries, butchers, fish mongers, bakers and dairies
are all good things.  The supermarket has robbed us of that and
replaced it with plastic wrapped mass market crap.

But none of this will work in a car-centric culture where you spend a
large part of your life driving from one place to another.  America
has zoned itself into hell and requires you to own a car to get from
one zone to another.

When you have to spend an hour or more to get to a job in a
centralized office or factory that runs on strict hours you don't have
time to go to the market before, or after work.  You have to do your
shopping at a supermarket where you can park your car and buy
everything for the week in one place.


** functional requirements

  - ban vehicles in the market, especially motorbikes except for an
    hour before the market opens.

    Instead create
    a delivery system to get goods from a loading area to the shops.
    ideally this should be automated -- robots!

  - most shops will be part-time enterprises, in mornings and
    afternoons and then special weekend markets.  The same location
    can be used for all, by creating multiple sets of storage lockers,
    so that one person could do the morning market, another the
    evening market and then another still for the weekend night
    market.

  - lot's of natural light, shade and cooling
  - good supplemental artifical light 
  - drainage drainage drainage
  - toilets and showers
  - stainless steel for surfaces that have food
  - refrigeration
  - air-pumps for seafood
  - network access, and docking stations for each booth
  - displays for each booth
  - weights & measures inspection and standards for all scales and
    measures
  - store value payment or cash
  - secure parking
  - security & measures against thieves and pickpockets
  - high-pressure cleaning between markets
  - discourage corruption
    - rents and fees paid at town centre
    - clear rent agreements
    - rent control
    - stalls rented by lottery
 - ensure that the markets are for local people first and always --
   keep from going up market, selling luxury goods or selling to
   tourists.

 - dry goods
 - cooked food
 - meat and fish
 - vegetables & fruit
 - restaurants

* 大 排 檔 (Dai Pai Dong)

  - [[https://en.wikipedia.org/wiki/Dai_pai_dong][Dai pai dong]] | Wikipedia


#+begin_quote
Features:

  - One can order tailor-made dishes.
  - It is customary to have to share tables with complete strangers
    when there is a shortage of seating.
  - Unlike cha chaan teng, most dai pai dong do not provide set meals.
  - "Cross-stall ordering" is possible: for instance, when one is
    sitting and eating in a stall selling noodles, he or she can order
    a cup of milk tea from another stall, which may be several stalls
    away.
  - The stalls can be roughly divided into those operating in daytime
    and those doing business at night. The dai pai dong which operate
    at night usually sell seafood and other more costly dishes: one
    dish usually costs from HKD$40–70. The day-time dai pai dong, on
    the contrary, provide cheap food including:
    - Congee and youtiao (aka yau cha kwai);
    - Milk tea, toasts, sandwiches and instant noodles with ham, egg,
      luncheon meat or sausage;
    - rice or noodles with siu mei (燒味 roasted meats);
    - fried rice and dip tau fan (碟頭飯 rice plates);
    - Chiuchow-style noodles (潮州粉麵).

-- [[https://en.wikipedia.org/wiki/Dai_pai_dong][Dai pai dong]] | Wikipedia
#+end_quote





* APL: Market of Many Shops

#+begin_quote
It is natural and convenient to want a market where all the different
foods and household goods you need can be bought under a single
roof. But when the market has a single management, like a supermarket,
the foods are bland, and there is no joy in going there.

Therefore:

Instead of modern supermarkets, establish frequent marketplaces, each
one made up of many smaller shops which are autonomous and specialized
(cheese, meat, grain, fruit, and so on). Build the structure of the
market as a minimum, which provides no more than a roof, columns which
define aisles, and basic services. Within this structure allow the
different shops to create their own environment, according to their
individual taste and needs.

                                 * * *

It is true that the large supermarkets do have a great variety of
foods. But this "variety', is still centrally purchased, centrally
warehoused, and still has the staleness of mass merchandise. In
addition, there is no human contact left, only rows of shelves and
then a harried encounter with the check-out man who takes your money.

The only way to get the human contact back, and the variety of food,
and all the love and care and wisdom about individual foods which
shopkeepers who know what they are selling can bring to it, is to
create those markets once again in which individual owners sell
different goods, from tiny stalls, under a common roof.

As it stands, supermarkets are likely to get bigger and bigger, to
conglomerate with other industries, and to go to all lengths to
dehumanize the experience of the marketplace. Horn and Hardart, for
example, have been contemplating this scheme:

    ##+begin_quote

    ... the customer either drives her car or walks onto a moving
    ramp, is conveyed decorously through the whole store, selects her
    groceries by viewing samples displayed in lighted wall panels (or
    unlocking the cases with a special key or her credit card), and
    chooses her meat and produce via closed circuit TV. She then
    drives around to a separate warehouse area to collect her order,
    paid for by a universal credit card system.... Most of the people
    would be invisible. . . . (Jennifer Cross, The Supermarket
    Trap,New York: Berkeley Medallion, 1971) .

    ##+end_quote

Now contrast this with the following description of an oldfashioned
market place in San Francisco:

   ##+begin_quote

   If you visit the Market regularly you come to have favorite stalls,
   like the one with the pippin and Hauer apples from Watsonville. The
   farmer looks at each apple as he chooses it and places it in the
   bag, reminding you to keep them in a cool place so they will remain
   crisp and sweet. If you display interest, he tells you with pride
   about the orchard they come from and how they were grown and cared
   for, his blue eyes meeting yours. His English is spoken with a
   slight Italian accent so you wonder about the clear blue eyes,
   light brown hair and long-boned body until he tells you about the
   part of northern Italy where he was born.

   There is a handsome black man offering small mountains of melons
   where the stalls end. Tell him you are not enough of an expert to
   choose one you would like to have perfect for the day after
   tomorrow, and he will not only pick one out that he assures you
   will be just right (as it turns out to be), but gives you a lesson
   in choosing your next melon, whether cranshaw, honeydew or
   watermelon, wherever you may happen to buy it. He cares that you
   will always get a good one and enjoy it. ("The Farmers Go to
   Market," California Living,San Francisco Chronicle Sunday Magazine,
   February 6, 1972.)

   ##+end_quote

There is no doubt that this is far more human and enlivening than the
supermarket conveyor belt. The critical question lies with the
economics of the operation. Is there a reasonable economic basis for a
marketplace of many shops? Or are markets ruled out by the
efficiencies of the supermarket?

There do not seem to be any economic obstacles more serious than those
which accompany the start of any business. The major problem is one of
coordination - coordination of individual shops to form one coherent
market and coordination of many similar shops, from several markets,
to make bulk purchase arrangements.

If individual shops are well located, they can operate competitively,
at profit margins of up to 5 per cent of sales ("Expenses in Retail
Business," National Cash Register, Dayton, Ohio, p. 15). According to
National Cash Register figures, this profit margin stays the same,
regardless of size, for all convenience food stores. The small stores
are often undercut by supermarkets because they are located by
themselves, and therefore cannot offer shoppers the same variety at
one stop, as the supermarket. However, if many of these small shops
are clustered and centrally located, and together they offer a variety
comparable to the supermarket, then they can compete effectively with
the chain supermarkets.

The one efficiency that chain stores do maintain is the efficiency of
bulk purchase. But even this can be offset if groups of similar shops,
all over the town, coordinate their needs and set up bulk purchase
arrangements. For example, in the Bay Area there are a number of
flower vendors running their business from small carts on the
street. Although each vendor manages his own affairs independently,
all the vendors go in together to buy their flowers. They gain
enormously by purchasing their flowers in bulk and undersell the
established florists three to one.

Of course, it is difficult for a market of many shops to get started -
it is hard to find a place and hard to finance it. We propose a very
rough and simple structure in the beginning, that can be filled in and
improved over time. The market in the photo, in Lima, Peru, began with
nothing more than freestanding columns and aisles. The shops most of
them no more than six feet by nine were built up gradually between the
columns.

                               IMAGE

A spectacular example of a simple wood structure that has been
modified and enlarged over the years is the Pike Place Market in
Seattle, Washington.

                                IMAGE

-- A Pattern Lanaguage: Market of Many Shops
#+end_quote
