#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Archival Storage
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/deploy/deploy-archival-storage.org
:Created:   2017-11-12T19:13@Prek Leap (11.642600N-104.919210W)
:ID:        077ea172-be43-4c38-9db5-c1e14b572c39
:VER:       563760850.719952527
:GEO:       48P-491193-1287029-15
:BXID:      proj:DYW7-6471
:Class:     deploy
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

 - [[http://www.tvtechglobal.com/post-production/deep-storage-how-to-save-your-data-for-a-billion-years/01278][Deep storage: How to save your data for a billion years]] | TVTechGlobal

 Group 47 has a good [[http://group47.com/challenges-of-archival-storage-of-digital-data/][list]] of links about the challenges of digital storage.

 - error
 - human accident
 - disaster
 - tempory insanity
 - benign neglect
   For other uses of term SEE [[https://en.wikipedia.org/wiki/Municipal_disinvestment][Municipal disinvestment]] | Wikipedia

 - [[https://en.wikipedia.org/wiki/Computer_data_storage][Computer data storage]] | Wikipedia

   - primary storage (memory)
   - Secondary storage (also known as external memory or auxiliary storage)
   - Tertiary storage or tertiary memory

I prefer online, nearline, offline

  - [[https://en.wikipedia.org/wiki/Non-RAID_drive_architectures#MAID][Non-RAID drive architectures]] | Wikipedia


* Rosetta Project

Rosetta was/is a brilliant project that in some ways was doomed to be
a one-off.  It was a bit expensive, used proprietary technology to
encode it and the contents of what was recorded as far as I can tell
is not in the public domain, or even digitized except as images.  So
this was a time-capsule project -- not a living archive that would
have continuity over long time periods.  The second problem is that it
really is like the rosetta stone -- its /just/ a massive bunch of
parallel texts.

 - [[http://rosettaproject.org/blog/02008/aug/20/very-long-term-backup/][Very Long-Term Backup]] | The Rosetta Project

The technology used to make the disk is from Norsam technologies.

 - [[http://www.norsam.com/rosetta.html][Norsam: HD-Rosetta and Related Processes]]

The time-scales for microetched nickle for very long term storage is
very good, but the system doesn't look like it will be feasible as a
solution for large scale distributed archival storage.

* MDISC: Stone DVD 

M-DISC is another billiant technology which leverages DVD and Blu-ray
discs made of stone which have an expected lifespan of up to 1,000
years.

The two problems with this is that they top out at 100GB using BD-XL
Blu-ray.  The chances of blueray players being around for a 1,000
years is problematic -- and because DVD and Blueray were concocted by
the entertainment industry there is all sorts of encoding cruft that
will not age well.

   - [[http://www.mdisc.com/][MDISC Archive Service]]

* DOTS

DOTS uses archvial tape image archival storage system.

 - [[http://blog.longnow.org/02015/12/27/dots-long-term-human-readable-archival-data-storage/][DOTS—Long-Term, Human-Readable Archival Data Storage]] | Long Now
 - [[http://group47.com/what-is-dots/][What is DOTS?]] | Group 47
 - [[https://www.youtube.com/watch?v=7eViN-ixW9I][DOTS Tech-Connect Fast Pitch]] | YouTube
 - [[http://www.group47.com/Group_47-DOTS_Technology_Overview-WEBSITE.pdf][Group_47-DOTS_Technology_Overview-WEBSITE-4-26-17.pptx]]

The system holds 1TB in a cartridge, lasts at least 100 years, it
seems to be tolerant of a wide range of environmental conditions
(except acid -- three hours in Sprite degraded the media).

There is a "leader" at the beginning of each tape that provides
instructions on how to contruct a microscope that can read the images.

The system also incorporates the LTFS file system that makes it easier
for automated systems to retrieve specific frames.

 - [[https://en.wikipedia.org/wiki/Linear_Tape_File_System][Linear Tape File System]] | Wikipedia

* Backblaze

Backblaze is online storage that massively scales.

  - [[https://www.backblaze.com/b2/storage-pod.html][Backblaze Storage Pod]]
  - [[https://www.backblaze.com/blog/vault-cloud-storage-architecture/][Backblaze Vaults: Zettabyte-Scale Cloud Storage Architecture]]
  - [[https://www.backblaze.com/open-source-reed-solomon.html][Reed Solomon Erasure Coding Web Page for downloading files]][[https://www.backblaze.com/open-source-reed-solomon.html][Reed
    Solomon Erasure Coding Web Page for downloading files]] 
  - [[https://en.wikipedia.org/wiki/Reed%E2%80%93Solomon_error_correction][Reed–Solomon error correction]] | Wikipedia

