#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Preservation
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/deploy/deploy-preserve.org
  :Created:   2017-04-24T16:28@Prek Leap (11.642600N-104.919210W)
  :ID:        de316670-78e7-4677-9a2d-62d26327e8ff
  :VER:       551631921.464135610
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:SUR3-7657
  :Class:     deploy
  :Type:      work
  :Status:    wip 
  :Licence:   MIT/CC BY-SA 4.0
  :END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

Clay Shirky's SALT talk on preservation:

  - [[https://www.youtube.com/watch?v=ujMgQqp8YSY][Making Digital Durable]] | Clay Shirky | SALT (2005) | YouTube

Shearing layer problem

  - Power
  - Architecture
  - OS
  - Dependencies
  - Interpreter
  - Format
  - Media


The bulk of the talk concerned classification and tags

Preservation descisions are made in at the edge of networks.

Classification is about finding things

We label things because you can't see what's inside

Information architecture is Social Architecture

hierarchy is a subset of tagging -- if use facets

tagging works when magnitude of the number of time an item has tagged
-- so this works collectively but not individually -- how to apply
outside of the community?

   - how to identify communities
   - thesaurus problem (aka roget)
   - can apply to navigation?
   - how to handle popularity risk -- brittle can't handle edge cases
   - detect concept rot -- can things stink when they look bad?
   - spam....


Tags Are Fnords!!!!

* Copyright

#+begin_comment
Doesn't belong here
#+end_comment



People conflate many things with ownership

  sovereignty is not some magical power -- it is a recipricol social
  contract, if there are two countries and one believes it has
  sovereignty and the other doesn't, then there is no sovereignty

Copyright is a social contract that states that all creative and
intellectual works belong to the public commons, (public domain) but
in order to encourage the production of creative works, states grant
temporary monopolies on the right to reproduce or copy those materials
to the parties that hold the copyright on those works.  These
monopolies are not absolute -- and there are exceptions -- fair use is
the most important.  But there are others -- for example, in United
States law, copyright wasn't always automatically added -- it had to
be claimed, and two copies of the work had to be given to the library
of congress.

However, some individuals, and corporations believe that copyright =
absolute ownership and are basically screwing over everyone else by
doing all sorts of evil crap to cheat on the social contract that
gives them the monopoly.
