#   -*- mode: org; fill-column: 60 -*-

#+TITLE: The Yellow Brick Road: A Manifesto
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/deploy/deploy-manifesto.org
:Created:   2017-08-24T18:30@Prek Leap (11.642600N-104.919210W)
:ID:        659c2b13-181c-4bab-8f7b-c23033fe6d95
:VER:       556846285.464337387
:GEO:       48P-491193-1287029-15
:BXID:      proj:CCH5-8007
:Class:     deply
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

*  A Manifesto for a Distributed Civilization


#+begin_quote
The Earth is the cradle of the mind, but we cannot live
forever in a cradle. 

-- Konstantin Tsiolkovsky (1857-1935)
#+end_quote


#+begin_quote
You can't cross the sea merely by standing and staring at 
the water.

-- Rabindranath Tagore (1861-1941)
#+end_quote


#+begin_quote
You begin saving the world by saving one man at a time; all
else is grandiose romanticism or politics.

-- Charles Bukowski (1920-1994)
#+end_quote

#+begin_quote
Pass it on .... That's the game I want you to learn to play.
Pass it on.

-- Alan Bennett, /The History Boys/
#+end_quote

* I.  The yellow brick road

Where is everybody?  The question hangs in the air, like a
pregnant pause, everyone holding their breath, straining to
hear in the uncomfortable silence.  But there is no answer,
not yet.

We live in a cosmos made up of hundreds of billions of
galaxies flying apart from the explosion that gave birth to
our universe.  Each galaxy is made up of hundreds of
billions of fireballs burning holes in the fabric of
spacetime as they hurtle around each other.  From time to
time one may collapse into a darkness so absolute that not
even information can escape.  Other times some may explode
and for a brief moment outshine all of the other fireballs
in the galaxy, to become vast gas clouds of astonishing
beauty that become stellar nurseries where new fireballs are
born.

Our star, was born some 13 billion years ago in such a
nursery in an uninteresting part of one of these galaxies.
Orbiting this star are nine planets, including a small rocky
world orbiting close enough to the star for there to be
water in a liquid state.

The more we learn about the universe and our place in it,
the more it's clear that there is nothing special or unique
about us.  We are now discovering, almost every day, the
rocky worlds and gas giants that are orbiting the stars in
our neighborhood. In the coming decades we will have the
ability to learn the composition of the atmospheres of these
worlds.  There is no reason to think that we won't find
other worlds like ours, close enough to to their stars to be
water worlds like ours.

But if there is nothing special about us, then it's
reasonable to expect that life will have evolved on other
planets and might even be relatively common.  And that on
some planets where there is life, that a species has evolved
to build a technological civilization like ours.  

So where is everybody?  This question is known as the Fermi
Paradox.  There is a long list of reasons we haven't yet
found evidence of other technological species, but there is
one reason that haunts the dreams of many scientists.  What
if the reason that we haven't found anyone out there is that
technological civilizations are are by their very nature, so
unstable that they destroy themselves shortly after their
own scientific revolution.

Is this our fate as well?  Are technological species little
more than mayflies that have a brief frantic existence
before falling dead before in the dark hours before dawn?
It's called the Great Filter, the existential moment of
truth that technological species must face after they have
unlocked nuclear forces that power our star, or perhaps what
kills us is learning how to reshape the structure of life
itself as if it were nothing more than a set of lego bricks.
That in our ignorance and immaturity we leverage our new
found technology to do nothing but engulf their planet with
their numbers, exceed it's carrying capacity, collapse
and never recover because we have exhausted all of the
easily exploited resources that made it possible for us to
build an industrial civilization.  If we fall now, there is
no rebuilding, and the surviors will eek out an existence as
best they can until an asteroid or super volcano finally
puts an end to the great human experiment.

The answer to the question, is in our own hands.  If we can
push past /our/ great filter, then it means that, if we are
average, there will be others like us out there.  If we
fail, we may well be gone before we can find out if we were
special only in our own demise.

Our ancestors understood that there were forces in the
universe which even the Gods could not escape which they
they gave names like Fate. Fate could not be petitioned, or
sacrificed to, or even hear us if we did.  The Gods might be
able to intervene in small ways on our behalf, but
ultimately these things were bigger than even the immortals.

It was thought that these forces determined what and how
things happened, but it turned out that fate was nothing
more or less than the physical laws of the universe which
are governed by the complexity of everything interacting
with each other.

You can predict the outcome of simple systems, but once a
system crosses a threshold of complexity, all we have is
statistics.  It's a bit like a game of Go.  With binary,
black and white stones placed on a grid cut into a block of
wood.  We thought that Fate and the Gods moved the stones
around on the board in a dance that we could not understand,
control or predict.  Instead stones are dropped onto the
board at random and you get a Poisson Distribution where you
can predict how many squares on the grid will have how many
stones, but not which square will have which number of
stones.

There is no prayer that can change the certainty of our
uncertainty.  As individuals we must each learn to make
peace with the unknown.  Our consolation is that over time
scales that are beyond living memory, we can collectively
beat fate, pass the test and survive our passing through the
Great Filter but only if enough of us as indivudals decide
to do it.

This is the great task we must choose or perish trying.
This is where we must begin, with a single step, at the
center of a widening path spiraling out into a vast kingdom
that we still know little about.  Each tenuous step forward
often will require to retrace our steps back, but there is
nothing for it but to push on down the yellow brick road to
meet someone or learn something, that can help us.



 - fermi's paradox and the great filter (& drake's equation)
   if we are not exceptional then where is everyone?

 - biosphere
 - savannah
 - extend & externalize
   - mind  : brain, speech, writing (havelock), computer
   - muscle: hand, tool, machine, robot
 - transactive man
 - cooperation & war
 - polis -- the rise of annuals and decline of perennials
 - pace layers

 - cognitive revolution
   - we had to give up our intestines which provided more
     energy for the brain but limited our diet -- so without
     cooking we survive poorly
   - we gave up our hearing to dogs
   - childbirth became quite dangerous
   - children born prematurely -- need long period of care
     but means that children's development can be molded
   - we have more nerve endings in our hands

  - we are the planet's apex predator and keystone species,
    capable of destroying everything, we are close to being
    able to consciously control of our dna not only of our
    selves but all life on the planet, we are also close to
    conquering death, so the only thing left that is certain
    is taxes.

  - stories make cooperation between large groups possible
    -- havelock and homer as oral cultural encyclopedia

  - between 70-30kya sapiens developed speech
  - stories -- gossip makes larger groups possible


* II  Fragility

 - fragility of our biosphere
   - asteroid and comet strikes
   - solar storms
   - super volcanos
   - hothouse coldhouse

 - fragility of our species

 - fragility of our civilization

 - the idea of progress is a recent infection carried by the
   scientific revolution -- it drives us, but it does not
   direct us in the right direction.  the grasping always
   for more has inspired us as a species, but it has also
   blinded us, made us reckless and squander resources as if
   they were infinite, as if our planet didn't have a
   carrying capacity.  But time and time again, human
   civilizations have run up against the carrying capacity
   of their environment and it always ends the same,
   collapse.  But there was always another civilization
   which could pick up the pieces and rebuild.  We've now
   taken this to it's logical conclusion, there is no where
   left on the planet to go, no greener pastures,
   unexploited resources.  We've finally gone so far that we
   are back where we started.

 - centralized

* III Estranged

 - the mind's illusion
 - myth of progress
 - energy
 - estranged from ourselves
   - savannah lost
   
* IV  Storms

 - goods, people and know how
 - population and the great pin -- as child mortality drops,
   and education increases, birthrate falls  -- this could
   well become the mechanism for man to regulate it's own
   population to compensate for our quick rise to becoming
   an apex predator and keystone species,


 - an end to our clement climate

 - the sound of inevitibility -- "you hear that mister anderson, it's
   the sound of inevitability - Smith"

 - disease
 - black swans, collapse, and world killers 

 - singularity or nightfall 

 - chances of survival (Gott)

* V   Maps & Stories

 - climate shapes our relationship with the world, and our worldview
   -- monsters and the critics.  it could be said that most cultural
   differences are derived from the different way we solve problems to
   adapt to the local climate.  temperature, rainfall, proximity to
   rivers or lakes or oceans, length of days and nights are all part
   and parcel of the mechanics of our daily lives -- Tolkien quote.

 - ariadne's Thread -- maps, narratives and territories
 - indistinguishable from magic -- mitigating complexity -- we need
   mythos to map technology so we can relate to it, understand it and
   use it.
 - language & mythos as interface
 - transcending and returning to human scales

* VI  The Window

 - The Window -- 50 years plus or minus 20

 - the only thing that has saved us after we have fouled our
   own beds and made them uninhabitable is that we move on
   to the next place and reduce pressure on our old homes to
   let them heal, if we haven't destroyed it beyond its
   ability to heal.  we expand or we die.

 - but we are now faced with the fact that we have nearly
   exhausted all of the low hanging fruit -- energy and
   natural resources and our population has exceeded the
   carrying capacity of the biosphere.

 - we need to expand into the solar system -- where there is
   no shortage of natural resources and energy

    - all energy is nuclear, be it fossil fuels, wind or
      solar or our own limmited ability to split or fuse the
      atom

    - it is likely that within a lifetime or two at most,
      the majority of energy that mankind uses will be for
      computation -- even today, Google alone represents 1-2
      percent of energy use in the united states.  solar and
      renewables can likely satisfy all of our other energy
      requirements -- but not computation

  - we must bring the savannah with us where ever we go --
    we need to learn to create and manage the biospheres we
    live in, and move to an ecological accounting system
    that really balances

  - the illusion of wilderness -- man has had a far greater
    impact on the planet than we want to admit -- we were in
    large part, responsible for the extinction of a huge
    swath of megafuana around the planet from mastadons, to
    giant slothes -- in north america, austrailia, new
    zeland -- american's like to wax romantic about the
    great untouched wilderness of north america with the
    original people's living there living in harmony with
    nature.  The jaw dropping landscapes of John Muir, the
    thunderous herds of bison numbering in the millions
    didn't exist two hundred years before Muir took up his
    paint brush -- the wilderness had only been untouched by
    man after small pox and the plague wiped out 80-90% of
    the population in the America's when early contact
    between Europe was made with the America's.  The
    pilgrams literally built their colony on the bones of
    the dead.

  - we will need to master of geoengineering -- first, to
    carve out habitable places in the cracks and crevices of
    the solar system, and eventually, to fix the mess we've
    created here on earth.

  - we need to become a truly distributed species

  - the city is not the savannah, and it never can be --
    cities exist because of the limitations of moving goods,
    people and knowledge -- if you can truly distribute
    those three things, then the mega cities we have today
    will no longer be needed.

  - we need to learn to manage the savannah inside us as
    well, our aggressive tendencies, our cognitive biases,
    our innate laziness, greed and tribal territorialism --
    we can no longer afford these luxuries and must set them
    aside as childish things

  - we must stop thinking of ourselves as a single species
    and embrace our transactive nature a broader concept of
    mankind that includes everything from our dogs and
    eventually to ai

  - we must let go of the illusion of the individual --
    homesteaders, doomsday preppers,

    even Thoreau, living his solitary life, relied on tools
    that had been created by an industrial chain that mined
    and refined ore into metals that were turned into tools,
    on textiles that started with farmers growing cotton or
    shearing sheep, which were spun into threads which were
    died different colors and woven into fabrics that were
    fashioned into clothes.  His shoes and boots started
    with the hides cut from megafauna, which was tanned and
    and fashioned into his shoes and boots.  and finally, he
    relied, though it's not certain how much, on food that
    was cooked by his mother (the story of his mother came
    from the permaculture book).

  - we are wired to wander but not be cut adrift as
    individuals but as members of small bands of 10-25
    people.  this is very natural -- children grow up and
    marry into other bands.  bands should be responsible for
    raising children culturally, and economically.  when a
    child is born into a band it is tied as much and perhaps
    even more to the band more than to the parent -- it
    doesn't take a village to raise a child, that's too
    large a cultural construct -- it has always been the
    band.

  - my concept of shops as economic production units that
    are responsible for several extending families is a
    perfect match for this new concept of a band -- perhaps
    the band itself is a legal entity that is also an
    economic entity as well.  the more I think about it,
    this is likely the only way a band could become stable.

  - as our lifespans increase, we will likely change from
    being a species with a single arc of youth, middle age
    and old age, to a very long middle age where we will
    cycle through a cycles of career, and child rearing.
    Each of these cycles might be within the same band, but
    more likely we will form a band to either have a career
    or raise a child, and when that cycle is over when the
    children have grown and gone off you will take a break,
    grow bored and then move on to form another band.  This
    would constitute a kind of rebirth for the individual to
    start fresh and recharged for a new cycle of their
    lives.  perhaps this would even correspond with a
    physical rejuvenation as well -- getting treatment to
    turn back the clock a couple of decades, perhaps
    changing your ethnicity, culture, language, or even
    gender to begin a new cycle.

  - this solves a problem which has bothered me for a long
    time.  rural communities can be both stable, nurturing
    places for people to live, work and raise families.  But
    they also become inbred, and moribund -- economically,
    educationally, and culturally they can get stuck as
    well.

    I've long wondered how the whole town-gown problem could
    be solved, as well as the toxicity and hopelessness of
    small isolated towns.  The answer is not to let children
    have their adventures at college abroad and then come
    back to settle down -- there needs to be a mechanism to
    bring in fresh genes, fresh ideas and experiences.


  - we need to stop thinking of ourselves as being one
    person from birth to death -- we are different people at
    different times in our lives and need to acknowledge
    this fact and reflect it in the way we treat things like
    success and failure and mistakes made.  this is
    especially true when it comes to mistakes -- you make a
    mistake, and should be held accountable for that mistake
    in the arc you are in, but eventually you will evolve
    into a different person and that person should be given
    the chance to start a new arc fresh -- but this will
    take time for us to learn how to do.

  - rituals of divorce -- our cultures are wired for single
    arc lifetimes -- we need to provide stable environments
    for each arc, but when it doesn't work out we must have
    a means of moving on.  Children should be tied to a
    single band until they become adults and ritually leave
    the band to seek their fortunes.  Adults should also be
    able to complete their cycle and move on as well.
    In this way bands will live and breath over time.
    divorce should never be easy -- but it must become part
    of the natural part of our societies, a doorway to a new
    beginning not simply an end.

  - joining a new band will, in many cases happen through
    marriage -- and we can use the ancient japanese
    tradition of men joining a japanese business through
    marriage and actually being adopted and changing their
    names to become part of the family to eventually take
    over the family business.  changing names is very
    important -- a clean slate -- the modern concept of a
    family is quite new, the idea of families going back
    tens or hundreds of generations used to be quite rare.
    family names are a new thing as well -- which was
    imposed by states to make people legible.

  - bands will be corporate entities -- and hold property
    and other assets that are collectively owned by the band
    and stay with the band.  when you leave a band, the band
    finances that person to leave and help found a new band
    or to join another band -- this is not the same as a
    commune, it will be closer to a hamlet.  membership in
    the band will include the concept of equity, but it will
    be equity that is tied up, a prosperous band will be
    able to provide more financing for those leaving the
    band, but beyond that there isn't really much of a
    mechanism or incentive for individuals to become
    independently wealthy or powerful.  how will that play
    out?  will there be bands who are focused on becoming
    wealthy and powerful and become new poltical and
    economic elites?  what about people in between bands?
    will being bandless will be equivilent to being
    stateless?  how can that work?  there is the concept of
    the jack, a person who has finished training under a
    master and travels from place to place getting
    experience before they produce their /master work/ and
    become a master.  this is, in a sense a stage of life,
    and we will need systems to support this.  perhaps each
    band will traditionally keep slots open for jacks, sort
    of in the same way as my family kept a bedroom for the
    local school teacher to live

  - educationally, you complete the trivium while living in
    your birth-band.  Then you either become an apprentice
    in your own band or in another band?  the same mechanism
    will work for jacks.  then when you become a master you
    join or form a band and become a full member.

  - none of this is as speculative as it might sound at
    first, we have effectively nearly doubled our lifetime
    already and we have a prolonged middle age which is
    longer than it takes for a single arc already 

  - how do we kickstart all of this?  the transition will
    not be easy, so we need to provide motivation for people
    to adopt this new, but very old, way of life.  this
    needs to start with social contract -- join the group
    and you will get protections and benifits for life (or
    at least the time that you are in the band).



