#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Globalization
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/deploy/deploy-globalization.org
  :Created:   2017-05-18T17:54@Prek Leap (11.642600N-104.919210W)
  :ID:        ec8d8f98-5f36-46c6-b007-62d9cbe293bd
  :VER:       548376945.759938949
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:NMY4-2473
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

* Towards an antifragile distributed technological civilization

The civilization envisioned aims to be pragmatic, egalitarian and
above all else sustainable economically, culturally, and ecologically.
Rather than proscribing a top-down master-design and plan that is to
be filled in like a child's coloring book, the primer will provide
patterns that can be adapted and combined to set in motion generative
processes that meet sustainable goals over very long time frames.
People don't change much in a lifetime, and societies take many
generations to realize substantive change.  Cities that have been
designed on a city-planner or architect's drafting table are doomed to
failure.  Cities and the infrastructure and buildings and people in
them grow organically over decades and centuries.  What is needed is
an Ent's-eye perspective that can keep long term goals on track over
time frames that span many lifetimes and generations.

The work is meant to be a living document that will changed as new
things are learned and we as individuals, civilization and a species
learn to adapt to future changes that we can't predict or even imagine
today.  But the primer will evolve over time to always address the
needs of the present in context with a history and with an eye fixed
on the future.

* Globalization

  - [[http://www.claremont.org/crb/article/sending-jobs-overseas/][Sending Jobs Overseas]] | CRB
  - [[bib:baldwin:2016great][The Great Convergence: Information Technology and the New
    Globalization]] | Richard Baldwin (2016)
  - [[bib:baldwin:baldwin:2006globalisation][Globalisation: the great unbundling(s)]] | Richard
    Baldwin (2006)


#+begin_quote
Thus globalization’s third unbundling is likely to involve
workers in one nation providing services in another nation
-- including services that today require physical
presence. Or to use the unbundling theme, globalization’s
third unbundling is likely to allow labor services to be
physically unbundled from laborers.

-- [[bib:baldwin:2016great][The Great Convergence]] | Richard Baldwin (2016)
#+end_quote



