#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Shops
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

* Shops
:PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/deploy/deploy-shops.org
  :Created:   2017-03-27T09:38@Prek Leap (11.642600N-104.919210W)
  :ID:        a4eb6dc0-38c3-4838-b671-81fd2210b9c8
  :VER:       551632599.650399380
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:GJL5-1687
  :Class:     deploy
  :Type:      work
  :Status:    wip 
  :Licence:   MIT/CC BY-SA 4.0
  :END:

** Introduction

When I was young, my family visited /Plymouth Plantation/ on Cape Cod
which was a recreation of the original 17th century Puritian
settlement, as well as /Mystic Seaport/ in Mystic Connecticut which
preserved an entire 19th century seafaring village and ships, and
later /Colonial Williamsburg/ which preserved 18th century buildings
as a museum that recreated life in the 18th century.

The thing that struck me about all three was how self-contained these
settlements were.  Almost everything that was needed was produced
locally, including food, building materials, tools, and clothing.
This was done using a handful of semi-specialized shops which provided
a range of goods and services within in a broad specialty.  There were
for example, blacksmiths, coopers, and cobblers.  Each of these shops
required specialized knowledge, tools and workflow that was difficult
for an individual household to do themselves.

These shops depended on each other as well.  A cooper needed wood, but
also metal hoops and tools produced by the blacksmith to produce
barrels.  A coobler needed a source or leather from a Tanner.  Tanning
is a specialty in itself which requires large quantities of chemicals
to tan hides.  The process can be done on a farm, but it's a long
process and the materials to tan hides are not cost effective if you
only have a few hides to tan a year.  A tailor needs woven cloth and
thread, and woven cloth needs dyed threads made from cotton or whool
in various colors.  A printer needed ink, lead type and paper, non of
which was created locally.  But in most small towns, the printer was
also a publisher of the local newspaper, and would sometimes also
publish books which they would have to bind as well as print.

Farms have traditionally been highly generalized enterprises that do
a great deal of fabrication from materials produced on the farm.  In
principle the farm could produce nearly everything themselves from
cloth to tools to tanned leather.  But that would require a great deal
of time and a very large toolchain.  It's much easier to go to the
blacksmith for a new hammer, or to fix something.  The farmer will
still do many tasks that could be done by a blacksmith, but when it
comes to something that is intricate, or requiring specialized tools,
it is better to take it to a specialist.

The system works well for small settlements made up of a few dozen
farms.  Trade between settlements was only done for a relatively small
range of goods because transportation of goods was both difficult and
expensive. 

What is missing from this system is aggregation, which requires
communications between producers, a logistics system to physically
collect things and move them to a centralized warehouse and then
combine and repackage those goods for sale to others.  This is where
middlemen come into the picture who add value by aggregating and
moving goods.

** Notes

  - [[https://en.wikipedia.org/wiki/Workshop][Workshop]]    | Wikipedia
  - [[https://en.wikipedia.org/wiki/Studio][Studio]]      | Wikipedia
  - [[https://en.wikipedia.org/wiki/Laboratory][Laboratory]]  | Wikipedia
  - [[https://en.wikipedia.org/wiki/Hackerspace][Hackerspace]] | Wikipedia

  - the right size
  - standardization
  - modular
  - the new just-in-time


I've certainly been thinking about this a very long time, and yet here
I am trying to write it all out and I'm a little at a loss.

When I say shop here, I don't mean a retail store, though many shops
will also have a retail front end, like a bakery, deli, repair shop.  But
many shops don't premake retail goods.

A shop is a place where things are made, usually with a master and a
small number of employees and a long time ago, apprentices.

Things are produced that are high in quality, often bespoke, and
artisanal.


shops short for workshop.  I like the french word
/atelier/ because of its connotations with being the home of an
alchemist of wizard (wikipedia: studio).

other terms such as studio and laboratory are also shops but don't
have the retail or commercial connotation that shop has.

more recently the term hackspace has emerged -- which is sort of part
workshop, office, and classroom.


** Shops and Labs

Text based on:  NOTES <2015-11-22 Sun 13:33> Modules -- Shops and Institutes

Since we are trying to build a civilization here -- we need to keep
focused on production -- that means we identify professions which are
made up of a number of specialties, processes and outputs.

So in a way we need to start with workshops -- and what each will
produce, what tools they will use, what processes are used to do
production and then what they can output -- and the goal here is for
each shop to support a bootstrap community of 3-5,000 individuals
which are broken into 30 dunbar unit villages.  That's not right --
each dunbar unit should be of working individuals -- and not count
small children, the ill or elderly who are no longer a productive
segment of society.  At any one time it will also include working
individuals who are taking leave for child rearing, or sabbaticals
etc.

So in a sense we are starting with the plan of St Gall -- with all of
the shops and other organization, and use this as a baseline, sort of
like Websters Dict was used by the OED...

  - Bamboo
  - Concrete & Artifical Stones
    - Cements (portand, roman)
    - Pipes, Posts, Beams
    - Slabs
    - Blocks, cinder,

  - Rammed Earth, Clays, Ceramics
    - Walls, floors, footings
    - Bricks & Paving Tiles
    - Firebricks, bricks
    - Roof tiles, glazed tiles
    - Pottery
      - wheels, ropes
      - glazes
      - containers, pots, jars
      - plates, cups
      - pipes
    - Glass


  - Anaerobic Processes
    - Charcoal Production
    - Kilns
    - Gasification
    - Lime?

  - Stone
    - quarried
    - cut
    - crushed
    - carved

--------

  - 3D Scanner -- large format
  - CADD Software OSS
  - Book Scanner
  - CNC Plasma/Laser Cutter
  - CNC Mill

  - IRC Server
  - PNCA Web Site
  - Kinto Web Site
    - NGO Package
    - SMB Package
  - The Knowledge: Applied
    - Essential Tools -- kevin kelly

