#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Climate Change
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/deploy/deploy-climate.org
:Created:   2017-07-11T10:01@Prek Leap (11.642600N-104.919210W)
:ID:        017963a3-bd78-4c92-9004-9133de51a59e
:VER:       553014184.884774753
:GEO:       48P-491193-1287029-15
:BXID:      proj:KGT3-1135
:Class:     deploy
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

Niels Bohr famously said, "Those who are not shocked when they first
come across quantum theory cannot possibly have understood it."
Climate change is the same, if Climate Change doesn't terrify you at
an existential level, you don't understand it.  No, it's not that bad,
it's worse, much worse.

Mankind is playing a very dangerous game that could have as big an
impact on the planet and our species than an all out thermonuclear war
between superpowers.

We have all been taught from childhood to mistrust the veracity of
apocolyptic predictions.  The story of Chicken Little is never far
from our awareness, because we seem to be programed to almost /want/
to believe in the end of the world.  Our religions, mythologies, and
popular culture is packed with epidemics, earthquakes, floods,
asteroids, alien invasions and more recently, zombies.  And in most of
these stories there is a Chicken Little character who heroically tries
to warn people, to no avail and everyone dies.

The Chicken Little story is told to children (and adults) because in
most cases there are no monsters.  It's a coping mechanism, so we
don't get so scared that we turn away and shut down and do nothing.

#+begin_quote
*Newt*: My mommy always said there were no monsters - no real ones -
but there are.

*Ripley*: Yes, there are, aren't there?

*Newt*: Why do they tell little kids that?

*Ripley*: Most of the time it's true. 

-- Aliens (1986)
#+end_quote

And it's all too true that most predictions of the end of the world
are patently absurd, and only believed by the gullible and in times of
great stress, it is comforting to escape into fantasy.  Because the
end of times, as fortold in religious stories is only an apocolypse
for bad people.  The believers are always told that they will either
survive or that they will be rewarded for their belief in an
afterlife.

So when the real monsters do come, as with Hilter, people don't want
to believe that they could exist, so they turn away and shut down
rather than face the truth.  And when cataclysms do happen, such as
earthquakes, volcanos and tsunamis, the survivers rationalize their
survival by believing that it was because of divine intervention, not
wanting to confront the ugly truth that divinity stepped in to save
them, but not the innocents who died next to them.  Cognitive
dissonance is easier to live with than the prospect of a complex
chaotic universe where your fate is governed by blind chance.  People
want meaning beyond the rational observation that survival boils down
to being at the right place at the right time.  More often than not,
we as a species are only sporadically rational beings.  Rationality is
just too damn terrifying for most of us.  And for those who commit to
a rational life, it's... exhausting.

So it's no wonder that there has been so much resistance to accepting
that Climate Change is real and is really scary.  It's easier to
believe in a Biblical Apocolypse in which /they/ will be saved, rather
than the bleak prospect of the entire world becoming uninhabitable in
their children's lifetimes.

It's important to understand that the world is not a Greek Tragedy,
there is no such thing as fate, divine retribution or divine
intervention for that matter.  We are unique as a species in that we
have the power, knowledge, and resources to fix our planet.  But this
won't happen quickly and it won't be easy.  The damage we have done is
on the very edge of being all but irreversible.  But that doesn't mean
that it can't be fixed.

** What Won't work

It's time to not only think clearly about the problem and how it can
be fixed.  The first step is for all of us to stop passing the buck
and personally take responsibility for contributing our part to the
big fix.  And to do that we must be honest about what will work and
what won't.

Climate Change won't be fixed at the ballot box.  Nation States will
/not/ fix things.  There will be calls to conduct Manhattan Project
scale mobilization.  But with no imminent existential threat like war,
or ideological insanity like the cold war or total solutionists that
brought us abominations like the Soviet Union, The Third Reich and the
Khmer Rouge.  There are very real limits on how much change that
people can deal with in a lifetime without destroying them.  And
changes to our base human nature, for good or ill, are doomed to
failure in anything less than scales measured in hundreds or even
thousands of years.  Some changes can only be contemplated on
evolutionary time scales.

Traditional activism, joining green groups, protests and other
feel-good measures will not fix things.  

Calls to individual sacrifice will not fix things.  One household on a
street who has installed a composting toilet and does their own
canning of fruits and vegitables grown in their back yard is laudable,
but it is little more than a lifestyle choice that has no appreciable
impact on the climate. These are superficial changes.  A suburban
house is still tied to the larger infrastructure that is having a
negative impact.

Corporate entities and the market will not fix things.  Modern
corporations exist to make a profit for those who are alive today,
payoffs that don't happen within years will not be invested in.

There is no miracle that will save us.

So what is left?  All of the traditional means of making a real impact
on the climate are non-effectual.



* The Scary Article 

 - [[http://nymag.com/daily/intelligencer/2017/07/climate-change-earth-too-hot-for-humans.html][When Will Climate Change Make the Earth Too Hot For Humans?]] | New
   York Magazine
 - [[https://newrepublic.com/article/143788/power-peril-climate-disaster-porn][The Power and Peril of “Climate Disaster Porn”]] | New Republic
 - [[http://www.slate.com/articles/health_and_science/science/2017/07/we_are_not_alarmed_enough_about_climate_change.html][New York Magazine’s Climate Change Horror Story Isn’t Too
   Scary. It’s Not Scary Enough.]]  | Slate
