#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Creating a Movement
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/deploy-movement.org
  :Created: 2017-03-19T10:57@Prek Leap (11.642600N-104.919210W)
  :ID: 39249880-f014-448f-a57b-54593915d2b2
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction




It's not enough to build something -- you have to put just
as much effort in to getting people to adopt it and then to
act as mid-wife to see it though long enough for it to hit
its tipping point and take on a life of its own.

* Rules for Radicals

  - [[bib:alinsky:1989rules][Rules For Radicals]] | Saul Alinsky (1971)
  - [[https://en.wikipedia.org/wiki/Rules_for_Radicals][Rules for Radicals]] | Wikipedia

#+begin_quote

   1. "Power is not only what you have, but what the enemy
      thinks you have." Power is derived from 2 main sources
      – money and people. "Have-Nots" must build power from
      flesh and blood.
   2. "Never go outside the expertise of your people." It
      results in confusion, fear and retreat. Feeling secure
      adds to the backbone of anyone.
   3. "Whenever possible, go outside the expertise of the
      enemy." Look for ways to increase insecurity, anxiety
      and uncertainty.
   4. "Make the enemy live up to its own book of rules." If
      the rule is that every letter gets a reply, send
      30,000 letters. You can kill them with this because no
      one can possibly obey all of their own rules.
   5. "Ridicule is man's most potent weapon." There is no
      defense. It's irrational. It's infuriating. It also
      works as a key pressure point to force the enemy into
      concessions.
   6. "A good tactic is one your people enjoy." They'll keep
      doing it without urging and come back to do
      more. They're doing their thing, and will even suggest
      better ones.
   7. "A tactic that drags on too long becomes a drag."
      Don't become old news.
   8. "Keep the pressure on. Never let up." Keep trying new
      things to keep the opposition off balance. As the
      opposition masters one approach, hit them from the
      flank with something new.
   9. "The threat is usually more terrifying than the thing
      itself." Imagination and ego can dream up many more
      consequences than any activist.
   10. "The major premise for tactics is the development of
       operations that will maintain a constant pressure
       upon the opposition." It is this unceasing pressure
       that results in the reactions from the opposition
       that are essential for the success of the campaign.
   11. "If you push a negative hard enough, it will push
       through and become a positive." Violence from the
       other side can win the public to your side because
       the public sympathizes with the underdog.
   12. "The price of a successful attack is a constructive
       alternative." Never let the enemy score points
       because you're caught without a solution to the
       problem.
   13. "Pick the target, freeze it, personalize it, and
       polarize it." Cut off the support network and isolate
       the target from sympathy. Go after people and not
       institutions; people hurt faster than institutions.

-- [[https://en.wikipedia.org/wiki/Rules_for_Radicals][Rules for Radicals]] | Wikipedia
#+end_quote


* Stupid TedTalk Video

 - [[http://www.ted.com/talks/derek_sivers_how_to_start_a_movement][Derek Sivers: How to start a movement]] | TED Talk

* Difussion of Innovation

 - [[https://www.ted.com/talks/simon_sinek_how_great_leaders_inspire_action#t-1065553][Simon Sinek: How great leaders inspire action]] | TED Talk
 - [[bib:rogers:2003diffusion][Diffusion of Innovations]] | Everett Rogers, (2003) 5th Ed 
 - [[https://en.wikipedia.org/wiki/Diffusion_of_innovations][Diffusion of innovations]] | Wikipedia
 - [[https://en.wikipedia.org/wiki/Everett_Rogers][Everett Rogers]] | Wikipedia

Why How What

* Tipping Point

- The Tipping Point | Malcom Gladwell

Connectors, Mavens, and Persuaders



* What we can learn from religion

TEDTalk: Alain de Bottom: Atheism 2.0
:url: 

 - [[bib:debottom:2012religion][Religion for Atheists]] | Alain De Botton
 - [[https://www.ted.com/talks/alain_de_botton_atheism_2_0][Alain de Botton: Atheism 2.0]] | TED Talk
 - [[http://www.ted.com/talks/alain_de_botton_atheism_2_0.html][Alain de Botton: Atheism 2.0]] | TED Talk (transcript)


Notes:

  - culture can replace religion
  - sermons -- proactive lectures
  - repetition -- without repetition, people forget
  - structure time -- calendars
  - rituals -- eg. moon festival
  - speak well 
  - physical actions back up ideas
  - art -- art for art's sake is wrong, and artists shouldn't explain
    themselves is wrong. religion uses are as a reminder what there is
    to love, fear and hate. Art should be didactic
  - religions form institutions -- bring in money, are branded,
    organized.

----

  - Religion for Atheists & Sacred Stacks & Anathem
  - Education -- and trivium -- learning to think first
  - catholic monastic orders are based on Epicurean
    communities.  in fact modern religion is in most
    respects providing what in ancient times, was what
    philosophy used to provide -- frameworks for living
    life.
  - liturgy --tightly choreographed ritual-agenda
  - collective meals -- the /agape feast/
  - culture of repetition
  - arrange time -- calendars of events
  - oratory --
  - physically manifest ideas -- eg. baptism
  - art must didactic -- manifest emotions, ideas and stories
  - form institutions -- collaborative, branded,
    disciplined.
  - pilgramage
  - connect to something bigger than ourselves
  - build on top of existing culture and religions --
    christmas was a pagan holiday


--- 

Institutions -- the Guilds offer a lot of opportunities for
this kind of thinking.  Whole communities can be built
around guilds -- some guilds are far more general and others
very narrow and specific.

A scopic guild could for the framework for monastic-like
communities as seen in Anathem -- be the foundation for a
lot of what DeBottom is talking about.  Whole philosophies
could be structured as Guilds in their own right.

In the civilization I am proposing, Guilds are part of a
system with checks and balances, so that Guilds don't become
cults or religions or political movements.  So they can
serve important cultural, and institutional needs without
getting out of hand.

* The Methodic Movement

#+begin_quote
Have you ever wondered, for example, how religious movements
get started? Usually, we think of them as a product of
highly charismatic evangelists, people like the Apostle Paul
or Billy Graham or Brigham Young. But the spread of any new
and contagious ideology also has a lot to do with the
skillful use of group power. In the late eighteenth and
early nineteenth centuries, for example, the Methodist
movement became epidemic in England and North America,
tipping from 20,000 to 90,000 followers in the U.S. in the
space of five or six years in the 1780s. But Methodism’s
founder, John Wesley, was by no means the most charismatic
preacher of his era. That honor belonged to George
Whitfield, an orator of such power and charisma that, it was
said, he once charmed a five pound contribution out of
Benjamin Franklin—who was, of course, the furthest thing
from a churchgoer. Nor was Wesley a great theologian, in the
tradition of, say, John Calvin or Martin Luther. His genius
was organizational. Wesley would travel around England and
North America delivering open air sermons to thousands of
people. But he didn’t just preach. He also stayed long
enough in each town to form the most enthusiastic of his
converts into religious societies, which in turn he
subdivided into smaller classes of a dozen or so
people. Converts were required to attend weekly meetings and
to adhere to a strict code of conduct. If they failed to
live up to Methodist standards, they were expelled from the
group. This was a group, in other words, that stood for
something. Over the course of his life, Wesley traveled
ceaselessly among these groups, covering as much as four
thousand miles a year by horseback, reinforcing the tenets
of Methodist belief. He was a classic Connector. He was a
super Paul Revere. The difference is, though, that he wasn’t
one person with ties to many other people. He was one person
with ties to many groups, which is a small but critical
distinction. Wesley realized that if you wanted to bring
about a fundamental change in people’s belief and behavior,
a change that would persist and serve as an example to
others, you needed to create a community around them, where
those new beliefs could be practiced and expressed and
nurtured.

-- Malcom Gladwell | The Tipping Point
#+end_quote

- [[https://en.wikipedia.org/wiki/George_Whitefield][George Whitefield]] | Wikipedia

* Overton Window

  - [[https://en.wikipedia.org/wiki/Overton_window][Overton window]] | Wikipedia

#+begin_quote
"Many who before regarded legislation on the subject as chimerical,
will now fancy that it is only dangerous, or perhaps not more than
difficult. And so in time it will come to be looked on as among the
things possible, then among the things probable;–and so at last it
will be ranged in the list of those few measures which the country
requires as being absolutely needed. That is the way in which public
opinion is made."

"It is no loss of time," said Phineas, "to have taken the first great
step in making it."

"The first great step was taken long ago," said Mr. Monk,–"taken by
men who were looked upon as revolutionary demagogues, almost as
traitors, because they took it. But it is a great thing to take any
step that leads us onwards."

-- [[https://en.wikipedia.org/wiki/Phineas_Finn][Phineas Finn]] | [[https://en.wikipedia.org/wiki/Anthony_Trollope][Anthony Trollope]]
#+end_quote

* Creeping Normality

Creeping normality if the Overton Window's evil twin.

  - [[https://en.wikipedia.org/wiki/Creeping_normality][Creeping normality - Wikipedia]]
