#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Structures
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/deploy-structures.org
  :Created: 2017-04-03T16:49@Prek Leap (11.642600N-104.919210W)
  :ID: e6e5cf68-ff97-4f81-aee5-5d9bf8ef3a6d
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Scope

* Introduction

Building structures that provide shelter is certainly
nothing unique to our species.  Ants and termites tunnel and
build elaborate colonies, bees build hives.  Birds have been
building nests since they were dinosaurs.  Structures are a
natural extension of basic survival instants.  If there is a
choice of staying out in the rain or in a dry shelter, those
who gravitate for the less hostile environment will have a
better chance of survival.  Most shelters are used primarily
to better the chances of their offspring to survive when
they are young and less able to survive in the open.

Early man was adept at wandering the planet, and the ability
to construct garments which extended environmental extremes
of hot and cold in which man could survive was coupled with
structures that extended that protection even farther and
afforded some protection against predators.

The structures we build are extensions of ourselves as
individuals and culturally as groups.  They play an enormous
role in how we percieve the world around us, and shape what
activities that we are able to conduct from day to day.

It is fair to say that mankind is an indoor species whose
primary activity outside of the structures we build for
outselves is to travel to other structures.  Even
transportation evolved to become essentially moveble
structures, so that some one living in a an extremely hot
and dry climate such as you find in the middle east or
southwest United States spend their days going from an air
conditioned house to an air conditioned car to an air
conditioned shop and back to the air conditioned car and
then to an air conditioned office.


#+begin_quote
... the contrast between these two buildings in fact offers a
brilliantly concrete demonstration of the dual premises that underlie
her book. The first is that architecture possesses what she describes
as a profound capacity to "make a difference"—to exert a fundamental
influence on our quality of life by literally shaping our activities
and experiences. The second is that this capacity is best understood
not in the abstract terms of aesthetics or history but by looking
closely at the actual mechanics of our daily interactions with
buildings; by trying to understand how we live in and move through
them.

- [[http://www.bookforum.com/inprint/024_01/17556][If These Walls Could Talk]] | bookforum.com, Julian Rose, 2017
  book review of You Say to Brick, The Life of Louis Kahn
#+end_quote


#+begin_quote
"You say to brick, 'What do you want, brick?' . . . Brick says to you,
'I like an arch.' If you say to brick, 'Arches are expensive, and I
can use a concrete lintel over an opening. What do you think of that,
brick?' Brick says, 'I like an arch.'"

-- [[https://en.wikipedia.org/wiki/Louis_Kahn][Louis Kahn]] - Wikipedia
#+end_quote

#+begin_quote
Drawing on speeches and letters from Kahn's time in Dhaka supervising
the construction of his design for the National Assembly Building of
Bangladesh, Lesser suggests that he saw the project not merely as
providing a site for the young nation's parliament to meet but as
physically establishing democracy there—as if the spatial
configuration of his building would bear as much responsibility for
good governance as the legal structure of a constitution.

For Kahn, the ultimate source of architecture's power was its ability
to communicate. He believed that buildings are composed of "universal
elements" that have remained essentially unchanged throughout the
ages, and so constitute a kind of ancestral spatial language shared by
all of humanity.

- [[http://www.bookforum.com/inprint/024_01/17556][If These Walls Could Talk]] | bookforum.com, Julian Rose, 2017
  book review of You Say to Brick, The Life of Louis Kahn
#+end_quote

