#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Climate Change
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/deploy/deploy-climate.org
:Created:   2017-07-11T10:01@Prek Leap (11.642600N-104.919210W)
:ID:        017963a3-bd78-4c92-9004-9133de51a59e
:VER:       553014184.884774753
:GEO:       48P-491193-1287029-15
:BXID:      proj:KGT3-1135
:Class:     deploy
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

* Introduction

Niels Bohr famously said, "Those who are not shocked when
they first come across quantum theory cannot possibly have
understood it."  Climate change is the same, if Climate
Change doesn't terrify you at an existential level, you
don't understand it.  No, it's not that bad, it's worse,
much worse.

Mankind is playing a very dangerous game that could have as
big an impact on the planet and our species as an all out
thermonuclear war.  And yet, there are still people, and
people in power who say they don't believe climate change is
real and most people who do, don't believe or comprehend the
magnitude of what could happen.

We have all been taught from childhood to mistrust the
veracity of apocolyptic predictions.  The story of Henny
Penny (Chicken Little in the United States) is never far
from our thoughts, because we intuitively understad that
we're programed to almost /want/ to believe in the end of
the world.  Our religions, mythologies, and popular culture
is packed with epidemics, earthquakes, floods, asteroids,
alien invasions and more recently, zombies.  And in most of
these stories there is a Henny Penny character who
heroically tries to warn people, to no avail and everyone
dies.

The Henny Penny story is told to children (and adults)
because in most cases there are no monsters.  It's a coping
mechanism, so we don't get so scared that we turn away and
shut down and do nothing.

#+begin_quote
*Newt*: My mommy always said there were no monsters - no
real ones - but there are.

*Ripley*: Yes, there are, aren't there?

*Newt*: Why do they tell little kids that?

*Ripley*: Most of the time it's true. 

-- Aliens (1986)
#+end_quote

And it's all too true that most predictions of the end of
the world are patently absurd, and only believed by the
gullible.  In times of great stress, it is comforting to
escape into fantasy.  Because the end of times, as fortold
in religious stories is only an apocolypse for bad people.
The believers are always told that they will either survive
or that they will be rewarded for their belief in an
afterlife.

So when the real monsters do come, as with Hilter, people
don't want to believe that they could exist, so they turn
away and shut down rather than face the truth.  And when
cataclysms do happen, such as earthquakes, volcanos and
tsunamis, the survivers rationalize their survival by
believing that it was because of divine intervention, not
wanting to confront the ugly truth that divinity stepped in
to save them, but not the innocents who died next to them.
Cognitive dissonance is easier to live with than the
prospect of a complex chaotic universe where your fate is
governed by blind chance.  People want meaning beyond the
rational observation that survival boils down to being at
the right place at the right time.  More often than not, we
as a species are only sporadically rational beings.
Rationality is just too damn terrifying for most of us.  And
for those who commit to a rational life, it's... exhausting.

So it's no wonder that there has been so much resistance to
accepting that Climate Change is real and is really scary.
It's easier to believe in a Biblical Apocolypse in which
/they/ will be saved, rather than the bleak prospect of the
entire world becoming uninhabitable in their children's
lifetimes.

It's important to understand that the world is not a Greek
Tragedy, there is no such thing as fate, divine retribution
or divine intervention for that matter.  We are unique as a
species in that we have the power, knowledge, and resources
to fix our planet.  But this won't happen quickly and it
won't be easy.  The damage we have done is on the very edge
of being all but irreversible.  But that doesn't mean that
it can't be fixed.

* What Won't work

It's time to not only think clearly about the problem and
how it can be fixed.  The first step is for all of us to
stop passing the buck and personally take responsibility for
contributing our part to the big fix.  And to do that we
must be honest about what will work and what won't.

Climate Change won't be fixed at the ballot box.  Nation
States will /not/ fix things.  There will be calls to
conduct Manhattan Project scale mobilization.  But with no
imminent existential threat like war, or ideological
insanity like the cold war or total solutionists that
brought us abominations like the Soviet Union, The Third
Reich and the Khmer Rouge.  There are very real limits on
how much change that people can deal with in a lifetime
without destroying them.  And changes to our base human
nature, for good or ill, are doomed to failure in anything
less than scales measured in hundreds or even thousands of
years.  Some changes can only be contemplated on
evolutionary time scales.

Traditional activism, joining green groups, protests and
other feel-good measures will not fix things.

Calls to individual sacrifice will not fix things.  One
household on a street who has installed a composting toilet
and does their own canning of fruits and vegitables grown in
their back yard is laudable, but it is little more than a
lifestyle choice that has no appreciable impact on the
climate. These are superficial changes.  A suburban house is
still tied to the larger infrastructure that is having a
negative impact.

Corporate entities and the market will not fix things.  Modern
corporations exist to make a profit for those who are alive today,
payoffs that don't happen within years will not be invested in.

There is no miracle that will save us.

So what is left?  All of the traditional means of making a
real impact on the climate are non-effectual.



* The Confluence

I find it interesting that all talk of tackling climate
change is based on extrapolating the present with the
assumption that the world will work the same ten years or
fifty years from now as they do today.

** Globalization

It's now 27 years since the second wave of globalization
began in 1990.  In that time the world has been transformed
as dramatically as the first wave of globalization over the
previous XX years.  The first way, which is known as the
Great Unbundling saw the rise of the G7 group of
industrialized nations which controlled most of the
industrial production on the planet.  The north was rich and
the south was poor, and poor countries had little
opportunity to change their lot.  Before 1990 the world was
very much centralized -- with all stages of innovation and
production being localized around manufacturig hubs in the
North.  This was largely possible because of a revolution in
transportation that began with the invention of the steam
engine which powered ships internationally, and trains for
inland transportation.  

The second unbundling, knows as the Global Value Chain (GVC)
leveraged ICT revolution in computing, networking and
telecommunications to unbundle manufacturing hubs, which
were located in industrialized countries with relatively
high labour costs.  A second revolution in transportation of
goods was made possible by modal transport (better known as
the standard shipping container) and palletization of goods
in those containers into smaller units which could be loaded
and offloaded from containers and trucks and moved around
warehouses using a fraction of the labor required
previously.  This made it possible to break up manufacturing
processes into multiple steps located in different
locations.  If labour was cheaper in another country, a
Northern manufacturer could have it made there, using cheap
labour in that country and even cheaper transportation to
move it around the globe. The ICT revolution made
communications between each stage of production almost as
easy as talking to someone in the same building.  This saw
the rise of the so-called Industrialized Six (i6), which
transformed those countries from being poor outsiders, to
being at the heart of various north-south production chains
that shape the world we know today.  This is what most
people think of today when they use the term globalization.
But globalization did not raise all boats equally.  The i6
nations have benifited enormously and are now within sight
of becoming industrialized nations on par with the original
G7.  And we are already seeing wages in those countries rise
to the point where they are no longer as cheap as they once
were.  If this process was to continue, then the i6 would
eventually kickstart other poor countries in turn, by moving
production to where labour was cheap.  And we have seen a
little of that.  A significant amount of textile production
is moving to countries like Nepal, Bangladesh and to a
lesser extent small countries like Cambodia.  But it is
doubtful that we will see a second wave of unbundling take
place before the next stage of globalization takes over.

We are poised to begin a third stage of globalization which
will likely transform the world as much as the first and
second stages combined over the next 10-15 years.  By the
20th aniversery of the iPhone, the world will be almost
unrecognizable from how it is today.

This third stage has the potential of radically changing how
we contribute to climate change.

The first stage of globalization was possible because
transportation became cheap.  The second stage was possible
because of communications, networking and computing.  But
the third factor is the cost of moving people.  In the
second unbundling, moving people was still expensive, which
was likely a major reason that the revolution was limited to
i6 nations.  In the third unbundling, the cost of moving
people will likely remain much the same as it is today.  But
the tasks that required the moving of people, which centered
around coordination costs -- which are all of the middlemen
providing services that make the GVC possible.  It is the
networks that these middlemen control and the relationships
that they have built up that keeps work flowing to the same
handful of i6 nations.  This is poised to radically change
as three technologies mature; artifical intelligence,
trustless transactions using blockchain techology and
robotics combined with AI which will take over from skilled
labour to control machines.

Where the first wave of globalization was centralized, and
the second wave was decentralized, the third wave will be
distributed.  Every time that systems become more efficient,
things get cheaper.  The first and second wave of
globalization only worked at scale -- with the base unit
being the 40' shipping container.  Producers who could
manufacture goods in multiples of 40' containers thrived,
while smaller shops, who might be producing better quality
goods in smaller production runs were cut out of the
benifits.  This is because the coordination costs for a
large production run, was the same as for a small run.  The
larger the production runs, the cheaper the coordination
costs.

But when most of the coordination services become automated,
small production runs will enjoy the same benifits as large
production runs.  An aggregation of many small production
runs in many locations will simply be as efficient and cheap
as large scale production.  At this point, the flexibility
of small production will become apparant.

At the moment, producing an iPhone requires coordinating and
spinning up an enormous number of people.  Keeping those
people busy means that the big factories can not afford any
downtime without costing them enormous amounts of money.  If
coordination, quality control and aggregation was automated,
then large scale production using many small shops, which
each can afford downtime, over the big factories which, like
sharks (the story goes) if they stop swimming they will die.

The second impact will be on labour costs.  A robot is
cheaper and more efficient than cheap labour.  Robots result
in lower waste, consistent quality and a higher standard of
living for those who are employed.  A small shop will in the
third wave will not be the same as small shops today.  They
will leverage the same automation technology and methods as
the big companies, but they will be faster to adapt to
change, and more flexible.  A shop run by 6-10 people will
be able to produce at the same capacity as middle-sized
enterprises do today.

Such a system will make it possible to create a new value
chain for every project, and when one job is finished a shop
can take on another job in a completely different value
chain.

How will this effect climate change and carbon emissions?
This is still early days, but these next generation
companies will largely be new enterprises, who will be
tooling using technologies which won't, as a general rule be
using fossil fuels for energy.  Because they are smaller,
their energy needs will be easier to be met using renewable
energy sources which at smaller scales will very soon be
cheaper than fossil fuel energy production.  It will change
how we think about locating businesses.  A lot of
urbanzation has taken place because jobs were located near
or in urban areas where they could draw on larger labour
pools and proximity to schools and other services.  A
distributed infrastructure may remove many of the incentives
to locating in urban areas that are highly regulated, have
expensive property and rents.  While all of this is still
very much conjecture, what it certain, is that as a large
part of manufacturing and production adapts to the third
wave and will have to retool in order to take advantage of
automation, that there is an enormous opportunity to build
this infrastructure to reduce or eliminate carbon emissions.

This will address many concerns of climate models which
factor in a prolonged period before fossil fuel based
infrastructure is replaced by low or carbon neutral
infrastructure.  This won't happen becuase of climate
change, we will replace the old infrastructure faster
because it will be economically benificial to do so.

The Remote Work trend, where a growing number of people
working in tech are working from home, will be reinforced
and expanded.  Telepresense, high quality teleconferencing,
will make it possible for far more people to join the Remote
workforce.  Even many jobs that might be thought of as being
immune to remote work, just as people managing factory
production processes can just as easily do their jobs from
home as on the factory floor.  It will be interesting to see
how far this can be taken.  Will we see people that manage
office cleaning services to manage fleets of robots from
home, as the robots are transported to office and shopping
centers at night in self driving vehicles, deployed under
direction of a remote operator?

Self driving vehicles and the shift to electric powered
vehicles will radically impact carbon emissions.  It is
hoped that it will massively reduce the need for many
individuals and even families to purchase vehicles, or at
least the need to buy second vehicles.  If nothing else, in
Western countries where drink driving laws have had a major
impact on bars and clubs because people can no longer risk
drinking when they go out if there is no public transport
system that could take them home while under the influence.

** Population

  - [[http://www.worldometers.info/world-population/#table-forecast][World Population Clock: 7.5 Billion People (2017) - Worldometers]]

At the time this is being written, the world population is
estimated to be 7.51 billion with births outpacing deaths at
roughly 2:1.  If this trend continues as is, forecasts
estimate this number rising to 9.7 billion by 2050.  After
that, most population models predict that the population
will drop dramatically untill it as fallen at least back to
today's population levels, with some models predicting drops
down to as low as 3.5 billion.

What's going on here?  The number of children that families
have is directly related to a number of factors.  Children
in poor countries are seen as the only safety net for aging
parents.  Second, children are seen as a means of boosting
the total income a family can produce -- more children means
a higher standard of living, and the loss of any one or two
children will not devastate the income production of the
family.  Next, lower mortality rates, mean that families
don't feel the need to have more children as a hedge when
some of them die.  And finally, educating women has a direct
impact on family size.  When women are literate, they tend
to have smaller families.

It is also a worrying trend that the more advanced an
economy gets, the lower the birthrate.  In fact, in a number
of countries, the birth rate has fallen below the number
needed to maintain it's population.  Rich nations are
literally wiping themselves out.

Furthermore, the birth rate in developing countries is
dropping faster as they develop as they did in the past.  So
the birth rate in Sweeden dropped slower as it developed as
developing countries today. 

As long as we can continue to reduce poverty, child
mortality and educate women this trend will continue.

So 50 years from now there will be less of us on the planet,
who are all living at a relatively high standard of living.
From a carbon emission standpoint it means that if we can
survive the next 30 years with a growing but low carbon
producing population, after that, emissions per person will
drop radically as the population shrinks.

In other words there is light at the end of the tunnel as
far as carbon emissions, but population is a double-edged
sword.

Innovation, and the rate of change is tied to the number
people innovating.  with less people on the planet, there
will be less people to solve problems that our previous
population created -- this will impact us long before the
population begins to drop, because the proportion of elderly
will increase up until the population begins to drop -- as
people get too old to actively take part in the workforce we
will have fewer people to work on problems.

This is where AI and automation will have to come in.  We
will need to maximize the power of a productive working
population that has to take care of an increasing proportion
of elderly people.

** Reduce non-fuel carbon reliance

 - fertilizer
 - plastics

 - stop corn and palm oil reliance
 - increase the biodiversity of cultivated species
 - make megafuana producers not a product
 - encourage seasonal food consumption
 - stop monoculture agriculture

 - reduce or eliminate processed foods
 - reduce plastics by making products that last, can be
   repaired and upgraded

 - replace hedgerow-to-hedgerow with vertical farming for
   staple production for urban populations


**  Carbon Capture

This is pure brainstorming.

Rather than taking carbon out of the atmosphere, we should
be looking at how to take it out of the oceans.  Oceans are
the planet's carbon sink.  But we are pumping so much carbon
into the atmosphere that we are exceeding the abilitiy of
the oceans to absorb it all.

So dual strategy -- stop pumping carbon into the air, and
pull out as much carbon as possible out of the oceans.  I
would imagine that it is easier to pull carbon out of a
liquid than a gas....


* The Scary Article 

 - [[http://nymag.com/daily/intelligencer/2017/07/climate-change-earth-too-hot-for-humans.html][When Will Climate Change Make the Earth Too Hot For Humans?]] | New
   York Magazine
 - [[https://newrepublic.com/article/143788/power-peril-climate-disaster-porn][The Power and Peril of “Climate Disaster Porn”]] | New Republic
 - [[http://www.slate.com/articles/health_and_science/science/2017/07/we_are_not_alarmed_enough_about_climate_change.html][New York Magazine’s Climate Change Horror Story Isn’t Too Scary. It’s Not Scary Enough]]  | Slate
