#   -*- mode: org; fill-column: 60 -*-
#+TITLE: TL:DR
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/deploy/deploy-tldr.org
  :Created:   2017-06-03T18:26@Prek Leap (11.642600N-104.919210W)
  :ID:        198d96e2-74f3-4c37-a3cd-c113f0c04a90
  :VER:       549761253.297109630
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:NAT1-3171
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Cover

    CHENLA
     TL;DR
     2017


by Brad Collins


Chenla Scopic Press
     Prek Leap


* Title Page

Chenla Scopic Press

        &

The Chenla Institute Centre for Distributed Civilization

Prek Leap, Cambodia

Volume 1, Issue 1

..... 1 [ stamp ]

&copy; 2017 The Chenla Institute

Published under a CC attribution, share-alike licence

* Plan of the Work

  [ *Contents* ] 

* Quote Page

I set out now, in a box apon the sea

-- Charles Olson, Maximus Poems


* Preface

TL;DR circa 2017, was a common abbrieviation on the Internet
for "too long; didn't read."  It's an interesting concept,
because it is simular to, but not the same as the older
established terms "executive summary", "synopsis" or "scope
note" which are themselves all slightly different as well.

We have appropriated the term as a name for /Chenla TL;DRs/
which provide a jumping off point for understanding an idea,
work, proposal, design or process and then providing
doorways (links) that allows the reader to dig deeper into
the subject, or not.  In otherwords, TL;DRs are the entrance
to rabbit holes which help you decide if you wish to tumble
down into or not.  An option poor Alice was never afforded.

In a very real sense -- the Chenla Institute's primary
activity is creating entrances to a myriad of rhizomatic
rabbit holes that taken together constitute the knowledge to
build and maintain a distributed technological civilization.

In summary, Chenla TL;DRs are:

  - *stubs* that frame an idea or project that provide enough
    information to get the base idea as well as enough to
    get started learning more.
  - *nested* - so that any part of a TL;DR may become a
    separate independent TL;DR at some time in the future.
    This section is at this stage a preface, but it will be
    expanded and released as it's own TL;DR in the future. 
  - *overlap* -- TL;DRs are not meant to be mutually
    exclusive, they embrace contradiction, duality and
    complexity so are more /messy/ than /cannonical/.
    Cannonical references and works will be defined using
    other mechanisms -- further down different rabbit holes.
  - *imutable* - each TL;DR is an imutable namespace so that
    the TL;DR as a concept is imutable, but the expressions,
    manifestations and instances of the TL;DR are mutable
    over time.  And you will always be able to find the
    latest version of a TL;DR via this imutable namespace.

TL;DRs will be publish digitally as they are completed and
collected together into an annual volume that will be
printed as a physical dead tree book which acts as both
snapshot and physical artifact.

Any TL;DR may or may not be followed up by and expanded as
in-depth proposals, narratives, research, code, designs
etc. but the TL;DR will remain as the portal to all other
work.


 - A Scopic Press

   provenance : all versions

   literate reproducible colophon : 
   everything is released with source, and toolchain for
   building - including the OS, languages, fonts etc.

   everything is indexed and digitally signed
 
   not all form factors are created equal
  
   source, content, surrounding & supporting context

   lod, pov, roc


* TL;TD I : The Yellow Brick Road

** Table of Contents
** Revolutionary Cycles

 - Centralized
 - Decentralized
 - Distributed

 - Timeline

Technological revolutions break up centralized systems into
a distributed system where the power is at the edge of the
networks.  Over time, consolidation occurs into a
decentralized network made up of a large number of medium
sized organizations.  Finally these mid-sized organizations
consolidate into a handful or even a single organization
that monopolizes the network.

As networks consolidate into decentralized and then
centralized systems, innovation slows down, creating a
power-wealth-value imbalance that is not sustainable.

In 2017 the Internet & The Web, which started as a
distributed network, consolidated to the point where the
number of players can almost be counted on one hand.

We are at the beginning of no less than five revolutions;
artificial intelligence, robotics, nanotech, trustless
distributed networks (based on cryptography, hashes, and
distributed ledgers) and a biological revolution based on
gene splicing technologies such as CRSPR.

Any one of these technologies alone would constitute change
at the same scale as Gutenberg's Press, The Industrial
Revolution, The Computer and Internet Revolutions.  Taken
together each of these revolutions will amplify, and
reinforce each other.  The next 5-20 years will
fundamentally reshape business, finance, manufacturing,
transportation, energy, agriculture, medicine, education,
government and the world order.  Simply put, we are seeing
changes that will transform human civilization to the point
that it can be called a Singularity; a future that we can
not predict or even imagine today.


** Towards a Distributed Civilization

 - more than resilient : develop infrastructure that is not
   only resilient to catastrophe, but is anti-fragile, that
   becomes stronger, the more it is challenged.  At the
   heart of this is ensuring that the knowledge and
   experience to build and maintain our civilization is
   distributed as widely, in time and space as possible.
   Publication is not enough, living knowlege and experience
   is as important as any recorded publication.

 - empowering the edges : ensure that everyone has access
   and opportunitiy to use all of these technologies to
   build and maintain a good life for their families and
   future generations.

 - the long now, and big here : thinking and acting over
   very long time frames through the development of
   sustainable and balanced systems that work in the real
   world, not just in academic books and scientific papers.

 - managing climate & ecosystems : unintentionally, man has
   brought the xx millenia of the interglacial period that
   has provided mankind with a mild and hospitible climate.
   Climate change will pose momumental challenges for our
   species and the planet.  We must stop thinking that man
   is not part of the natural world, without the natural
   world, we would be extinct. To this end we must learn to
   become respnsible stewards of the climate and ecosystems
   that give us life.  This goes beyond reversing or just
   mitigating climate change, it has to become a core part
   of our self identity and understanding that our lives
   depend on us getting this right.


* TL;TD II : The Chenla Bluebook

** Table of Contents

** The Chenla Institute

A distributed (as MIT MediaLab puts it) anti-disciplinary
research institute incorporated in Singapore, Germany and
France ??? with it's first campus located at Prek Leap
National College of Agriculture in Cambodia.

The Institute's mandate is to develop, document and deploy
the descriptive and proscriptive information, code, designs,
and ideas needed to establish a highly distributed
civilization for Mankind.

The Institute will work with and help governments, NGOs and
industry to understand and adapt to the radical changes that
will reshape our civilization in the coming decades, and to
spin off commerical and non-profit organizations and
companies that will implement the technologies developed at
the Institute.

The Institute is commited to openess and transparency.  All
works will be released under open source/content/design
licences and made availble as widely as possible.

** Organization

 - organization & legal
    - Administrative office
    - Centre for Distributed Civilization
    - b>i Research Group
    - Chenla Scopic Press
    - Dabbawallah Cluster : computational and storage services

** Facilities

- Viz Centre : collaboration and conference space
- Fab Lab    : tool & machine fabrication
- Map Lab    : content & code
- Wet Lab    : Gene Splicing & Agricultural Biotech
- DataCenter : Containerized Process Cluster

Renovation of existing structures @prekleap 
 - exisiting buildings
 - riverfront erosion control & development
 - modular containerized data center
 - solar & gasification electrical generation

Equipment List
 
 - servers and routers
 - converted 20 foot ISO shipping containers

 - CNC milling, router & plasma cutters
 - 3D Printing
 - Metal/Machine Shop
 - Wood Shop
 - Electrical/Electronics Shop     

 - CRSPR gene splicers
 - tissue culture lab
 - 

** People

  - people:
    - faculty 
    - sabbatical program
    - fellowship program
    - internship program
    - tutorial program

** Events & Publications

  - Conferences, Symposia, & Summits
  - Journal, Books -- original works and reprinting
    important works that are crucial to building and
    maintaining a distributed civilization.

** Financial

While we will actively seek our and apply for grants,
relying on grants for funding, or any one source of revenue
is not sustainable.

  - Corporate Sponsorship
  - Endowments
  - Consulting Services
  - In-Kind Donations

* TL;TD III : Implementation

** Table of Contents
** Introduction

The work of the institute is meant to be both deployable as
well as academic and scientific.  It's been said that it
takes an industrial civilization to build an industrial
civilization.  The same is true for distributed
civilizations as well.  The Institute will build and work
using distributed infrastructure which will be a combination
of existing technologies, as well as our own implementation
of the pieces that are still missing but will be required
for the infrastructure to work in practice as well as it
does in theory.  This section outlines the technologies that
we and the missing pieces that we will complete development at
the Institute.

** A New Distributed Network Layer 

** Interplanetary File System

** Cryptocurrencies

** Neural Nets

** Missing Pieces

- Identity Model
- Fnords: acertaining certainty
- Codex.d: distributed publication
- Sneaker Net of Things (SNOT)

** Implementation
  
 - hoards
 - horcruxes
 - maps
 - duck tests
 - process guilds

* TL;TD IV : The Primer

   Content, Rules & Index  |   Cognitive Back Box   |   Map
   -------------------------------------------------------------
 - Descriptive
 - Proscriptive
 - Tools
 - Materials
 - Structures

* TL;TD V : 2017 Research Themes

 - Tropical Savannah
 - Bamboo Process Guild : OpenDesk and Mark's Bamboo Guy
 - Legible Land  : land titles, and satellite maps
 - Crucial Tools : critical tools and machines : kevin kelly
   & Open Ecology
