#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Goals
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/deploy-goals.org
  :Created: 2017-04-02T18:53@Prek Leap (11.642600N-104.919210W)
  :ID: 25bfd328-058c-41df-96ad-8d1dc797cff4
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

Goals are meaningless unless they have scope with an explicit POV, ROC
and LOD.....


* Big Picture

 #+begin_comment
 from: NOTES <2014-12-01 Mon 19:06> 
 #+end_comment

The Big Picture is outside human scales -- it doesn't fit into what we
are designed to comprehend.  For this reason there won't be a lot of
people who will be able to grok it.  You need a Carl Sagan to even
begin to get these things onto people's radar -- and even then it's
not their immediate radar, but just their adjective radar -- Wow!
Cool! Mind Blowing! that might overwrite some of the religious big
picture stuff in their heads, but little else.  This stuff doesn't
impact many people in a personal and immediate way.  When it does,
people tend to become astronomers (okay scientists), philosophers or
complete nut jobs.  Some go on to form companies like SpaceX or work
for NASA, or become science fiction writers or film makers.

So if you are not one of those listed above, this is not for you.  Go
eat a cupcake, face plant yourself back into facebook, and forget you
ever stumbled in here.

... wait ...

Now for those few of you who are still reading, Now let's continue.


  - drake's equation and the value of L
  - earth has an expiration date -- 1 billion years -- this is the
    ultimate practical scope for humans.
  - our first scope will be for technological civilization to survive
    the 10ky
  - undertake vast million year projects to move both mars and venus
    into better orbits, give them new, large moons and terraform them
    -- the lack of a magnetic field will be tricky though....
  - all heavy industry needs to move off planet, where resources are
    plentiful and energy easier to generate. 
  - establish a time keeping system based on seconds from epoch, which
    we can arbitrarily start from our present year 2000.


We need to spread out throughout the solar system and keep each
settlement small >2M, each has to be energy self-sufficient -- keep
movement to a minimum by making it largely unnecessary -- and maintain
large wilderness buffer zone that helps to regulate climate and
maintain biodiversity.
