#   -*- mode: org; fill-column: 60 -*-

#+TITLE: The Yellow Brick Road: A Manifesto
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/deploy/deploy-manifesto.org
:Created:   2017-08-24T18:30@Prek Leap (11.642600N-104.919210W)
:ID:        659c2b13-181c-4bab-8f7b-c23033fe6d95
:VER:       556846285.464337387
:GEO:       48P-491193-1287029-15
:BXID:      proj:CCH5-8007
:Class:     deply
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* I.  the yellow brick road

 - fermi's paradox and the great filter (& drake's equation)
   if we are not exceptional -- then where is everyone?

 - biosphere
 - savannah
 - extend & externalize -- brain, speech, writing (havelock)
 - transactive man
 - cooperation & war
 - pace layers

* II  Fragility

 - fragility of our civilization
 - centralized

* III Estranged

 - the mind's illusion
 - myth of progress
 - energy
 - estranged from ourselves
   - savannah lost
   
* IV  Storms

 - goods, people and know how
 - population and the great pin
 - an end to our clement climate

* V   Maps & Stories

 - Ariadne's Thread -- maps, narratives and territories
 - mitigating complexity
 - language & mythos as interface
 - transcending and returning to human scales

* VI  Expand or Extinct

 - the only thing that has saved us after we have fouled our own beds
   and made them uninhabitable is that we move on to the next place
   and reduce pressure on our old homes to let them heal, if we
   haven't destroyed it beyond its ability to heal.  we expand or we die.

 - but we are now faced with the fact that we have nearly exhausted
   all of the low hanging fruit -- energy and natural resources and
   our population has exceeded the carrying capacity of the biosphere.

 - we need to expand into the solar system -- where there is no
   shortage of natural resources and energy

    - all energy is nuclear, be it fossil fuels, wind or solar or our
      own limmited ability to split or fuse the atom

    - it is likely that within a lifetime or two at most, the majority
      of energy that mankind uses will be for computation -- even
      today, Google alone represents 1-2 percent of energy use in the
      united states.  solar and renewables can likely satisfy all of
      our other energy requirements -- but not computation

  - we must bring the savannah with us where ever we go -- we need to
    learn to create and manage the biospheres we live in, and move to
    an ecological accounting system that really balances

  - the illusion of wilderness -- man has had a far greater impact on
    the planet than we want to admit -- we were in large part,
    responsible for the extinction of a huge swath of megafuana around
    the planet from mastadons, to giant slothes -- in north america,
    austrailia, new zeland -- american's like to wax romantic about
    the great untouched wilderness of north america with the original
    people's living there living in harmony with nature.  The jaw
    dropping landscapes of John Muir, the thunderous herds of bison
    numbering in the millions didn't exist two hundred years before
    Muir took up his paint brush -- the wilderness had only been
    untouched by man after small pox and the plague wiped out 80-90%
    of the population in the America's when early contact between
    Europe was made with the America's.  The pilgrams literally built
    their colony on the bones of the dead.

  - we will need to master of geoengineering -- first, to carve out
    habitable places in the cracks and crevices of the solar system,
    and eventually, to fix the mess we've created here on earth.

  - we need to become a truly distributed species

  - the city is not the savannah, and it never can be -- cities exist
    because of the limitations of moving goods, people and knowledge
    -- if you can truly distribute those three things, then the mega
    cities we have today will no longer be needed.

  - we need to learn to manage the savannah inside us as well, our
    aggressive tendencies, our cognitive biases, our innate laziness,
    greed and tribal territorialism -- we can no longer afford these
    luxuries and must set them aside as childish things

  - we must stop thinking of ourselves as a single species and embrace
    our transactive nature a broader concept of mankind that includes
    everything from our dogs and eventually to ai

  - we must let go of the illusion of the individual -- homesteaders,
    doomsday preppers, 

    even Thoreau, living his solitary life, relied on tools that had
    been created by an industrial chain that mined and refined ore
    into metals that were turned into tools, on textiles that started
    with farmers growing cotton or shearing sheep, which were spun
    into threads which were died different colors and woven into
    fabrics that were fashioned into clothes.  His shoes and boots
    started with the hides cut from megafauna, which was tanned and
    and fashioned into his shoes and boots.  and finally, he relied,
    though it's not certain how much, on food that was cooked by his
    mother (the story of his mother came from the permaculture book).
