#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Healthcare
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/deploy/deploy-health.org
  :Created:   2017-03-28T10:51@Prek Leap (11.642600N-104.919210W)
  :ID:        68902717-01c2-44ca-b017-b8a3558ae3b9
  :VER:       551631245.465847312
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:ITV0-4435
  :Class:     deploy
  :Type:      work
  :Status:    wip 
  :Licence:   MIT/CC BY-SA 4.0
  :END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

* Introduction

Remember -- no promises -- deliver on day one.

Healthcare is a difficult subject that I've not really begun to tackle
but we need to get started on it asap.

Everyone is entitled to full healthcare from cradle to grave -- no
exceptions.

* Problems

Healthcare is a mess for any number of reasons:

  - it's being done for profit (hospitals, insurance companies & doctors)
  - equipment is made for profit
  - drugs are made for profit
  - it's not evenly distributed
  - little attempt to keep people healthy instead of waiting until
    they get sick -- would save a lot of resouces.
  - governments are inefficient - but are better than for-profit orgs
  - politics, inequality, racism, sexism and religious boneheads
  - patents patents patents

* Brainstorming

The following is nothing more than brainstorming, to come up with
ideas that could be developed further.

The first line of defence is the pharmacies -- add them to the
network, and give them a terminal so they can look up patient records
and make first-pass diagnosis -- should have bloodpressure, heart
monitor, and temp -- patient comes in and takes all three, it's fed
into their record and pharmacist makes decision to provide medication
or send them to clinic.  Collective buys drugs in bulk and sells at
cost to pharmacies -- people are given vouchers for getting free
medications if they go through the testing system first.

Build modular clinics that are distributed around bioregions -- they
are designed to monitor and manage health -- and deal with minor
illness and injury.

If more advanced expertise is required -- tele-presense can bring in
expert consultation.

Small drones can pick up samples and brought to labs for testing.

More advanced testing -- MRIs etc can be brought by drone dropships --
used and then picked up and moved to the next location.

Eventually, surgery will be completely replaced by robots -- robots
will be far better and cheaper than people ever could be.  Robotic
surgeries could even be mobile 


----

The healthcare industry is made up of:

  - people - lot's and lot's of people
  - physical places -- clinics, shops, hospitals etc
  - physical equipment
  - chemicals
  - pharmaceuticals
  - training 
  - insurance
  - payments
  - research
  - publication

People likely make up most of the costs -- and because
medicine is so specialized, there is an enormous amount of
duplicated effort -- doctors, nurses, and techs are required
at every level -- you deal with one at a clinuc, then
another group at a hospital, and another at a specialists
office.

It would be better to have have care givers and nurses that
provide all care, and then just swap in expertise when it is
needed -- so the patient stays and is cared for near or at
home, and telemedicine is used to bring in specialists
remotely, and automated systems bring in specialized
equipment that will be operated locally or remotely.

Care could be organized as it-torrents that organize,
schedule and coordinate diagnosis, and treatment.

This would make expensive equipment cost effective because
it could be used as widely as possible.  A lot of
infrastructure wouldn't be needed.  And you'd need a lot
less nursing and support staff.  

Pharma is enormously fucked up -- and needs to be rethought.
Pharma production needs to become decentralized -- ideally
as much as possible should be produced locally as it is
needed.  But a lot of this can't happen while states allow
private companies to have monopolies on chemical compounds.
And that won't happen until there is a different R&D model
for drugs to be developed.  Market demand is a poor way of
developing drugs.

And none of this will happen until we rethink how drug
trials and approvals take place.  Drug trials need to become
distributed as well -- and this is only possible if the
observation, testing and information gathering that is part
of it becomes distributed.  So, drug trials could also
become it-torrents, with local caregivers getting paid for
participating. 

So infrastructure, large capital equipment costs and the
level of care and training needs to move to the edge of
networks.  A lot of diagnosis will happen by ai before it
get's passed to specialists.  And nursing and caregivers
will be responsible for making sure that all of this is
happening the way it should be, on behalf of the patient.

And of course insurance needs to be rethought so that it is
not thought of as a burden, but part of maintainence that
minimizes down time and systems failures.


* MRI

 - [[http://www.opensourceimaging.org/][Open Source Imaging]] 
 - [[http://hackaday.com/2015/05/04/hackaday-prize-entry-a-low-cost-open-source-mri/][Hackaday Prize Entry: A Low Cost, Open Source MRI]] | Hackaday
 - [[https://hackaday.io/project/5030-low-field-mri][low-field MRI]] | Hackaday.io

 - [[http://www.tricorderproject.org/blog/towards-an-inexpensive-open-source-desktop-ct-scanner/][Towards an inexpensive open-source desktop CT scanner]] | the Tricorder project
