#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Gracefully Degrade
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/deploy-degrade.org
  :Created: 2017-04-23T10:44@Prek Leap (11.642600N-104.919210W)
  :ID: 30823928-8d2a-49da-80aa-b1d6d34b7a4e
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

- [[http://www.catb.org/esr/writings/taoup/html/ch01s06.html][Basics of the Unix Philosophy]]


#+begin_quote
A system that is designed to experience *graceful degradation*, or to
fail soft (used in computing, similar to "fail safe") operates at a
reduced level of performance after some component failures. For
example, a building may operate lighting at reduced levels and
elevators at reduced speeds if grid power fails, rather than either
trapping people in the dark completely or continuing to operate at
full power. In computing an example of graceful degradation is that if
insufficient network bandwidth is available to stream an online video,
a lower-resolution version might be streamed in place of the
high-resolution version. Progressive enhancement is an example in
computing, where web pages are available in a basic functional format
for older, small-screen, or limited-capability web browsers, but in an
enhanced version for browsers capable of handling additional
technologies or that have a larger display available.

-- [[https://en.wikipedia.org/wiki/Fault_tolerance][Fault tolerance]] | Wikipedia
#+end_quote

This is not the same as providing redundancy, or making systems
fault-tolerant which are a means of maintaining operability.

For example, if you have a house full of appliances that are part of
the IOT, and there is a network failure, those devices will no longer
work.  But they could then revert to an 'electronic' level of
functionality so that they continue to work as a basic electronic
device.  But if the electronics are fried from a line spike during an
electrical storm they will no longer work, so they could then revert
to an electrical level which doesn't rely on the electronics and
mechanical switches could then operate the device so long as their is
a current.  Concievably, for some devices, if the electricity goes
down, you could connect the device to a non electrical source of
energy -- such as a bicycle turning a belt.  In this way, the systems
will continue to work, but at increasingly less efficiency, and with
less and less fine-control and ease of use.

* Systems

prinicple of things gracefully degrading

- software interfaces
  - GUI
  - CLI

- Documents
  - Rendered
  - Source (syntax hi-light etc)
  - Plain Text

- Storage
  - Cloud
  - Local

- Network
  - Internet
  - Mesh
  - LAN
  - Sneakernet (point-to-point/store-and-forward)

- Processing
  - cloud - CPU/GPU
  - local
  - device

- Electricity
  - Grid
  - Local
  - Device

* Machines & Devices

Needs to be thought of in terms of shearing layers, in that rather
than replace the whole device you replace different layers of the
device.

  - digital :: 
    - sensor package
    - interface
    - processing
    - network interface
  - electronic :: basic
    - switches
  - electrical ::  
    - power source
  - mechanical :: 
    - moving parts : parts that wear out
    - gears, pumps, fans, bearings, washers, belts, plugs
  - skin :: can be changed frequently 
  - chasis :: lasts lifetime of device

The idea is that if the digital layer breaks, the electronic layer
will still work, if the electronic layer breaks then the electrical
layer will still work, and if the electrical breaks, the mechanical
still works.


* Civilization

  - Digital info-centric technological
  - Industrial Electrical
  - Neo-Edwardian Mechanical/Electrical
  - Pre-Industrial Mechanical
  - Mad Max tool-based hunter-gatherer

* Core devices


  - lamp
  - fan
  - rice cooker/slow cooker/pressure cooker
  - water cooker
  - cooker
  - washing machine
  - refrigerator
