#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Mythos
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:~/proj/chenla/hoard/bib.bib

* Mythos
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/deploy/deploy-mythos.org
:Created:   2017-08-29T14:59@Prek Leap (11.642600N-104.919210W)
:ID:        44223b9b-0a79-4699-87b0-7316af20409a
:VER:       557265616.850694266
:GEO:       48P-491193-1287029-15
:BXID:      proj:EEB0-4821
:Class:     deploy
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

** Table of Contents

 - Nature of Myth
 - Shamanic Interface

** Scope

** TL:DR


** Introduction

 - [[https://en.wikipedia.org/wiki/Intersubjectivity][Intersubjectivity]] | Wikipedia

Myths are not just stories, they provide:

  - communication within and between groups
  - cooperation within and between groups.
  - language, a shared symbol system
  - a cultural encyclopedia (havelock)
  - a collective world view (map)

In a sense all five of these things are different aspects of
the same thing.

We need a way of thinking about all of these aspects:

  - *narrative* -- a thread winding through a map
  - *overlay*   -- a collective map that provides us as a
    group with a shared worldview which we use for
    communication and cooperation.  Mythos is a map.
  - *interface* -- /magic/ is an interface between the
    intersubjective and the objective physical world -- not
    all of the physical world, only the things that we (man)
    can have power over.  Traditionally magic was
    /sympathetic/, /alchemy/ (the foundation for chemistry)
    or /oral/ spells, incantations etc that were based on
    the idea that words had power over the things they
    named.  This is the base concept of programming.  You
    control computational machines using words, magic as
    command line.

The /subjective/ is the map in our head. Mythos and Magic
are a means of pulling together the intersubjective with the
objective.

Speech and writing systems are symbol systems that are
essentially programming languages.

#+begin_quote
According to Albert A. Anderson, a professor of philosophy, the term
mythos appears in the works of Homer and other poets of Homer's
era.[7] In these works, the term had several meanings: conversation,
narrative, speech, story, tale, and word. Like the related term logos,
mythos expresses whatever can be delivered in the form of words.[7]
Anderson contrasts the two terms with ergon, a Greek term for action,
deed, and work.

The term mythos lacks an explicit distinction between true or false
narratives.

-- [[https://en.wikipedia.org/wiki/Myth][Myth]] | Wikipedia
#+end_quote



#+begin_quote
In the debate between cognitive individualism and cognitive
universalism, some aspects of thinking are neither solely personal nor
fully universal. Cognitive sociology proponents argue for
intersubjectivity—an intermediate perspective of social cognition that
provides a balanced view between personal and universal views of our
social cognition. This approach suggests that, instead of being
individual or universal thinkers, human beings subscribe to "thought
communities"—communities of differing beliefs. Thought community
examples include churches, professions, scientific beliefs,
generations, nations, and political movements. This perspective
explains why each individual thinks differently from each another
(individualism): person A may choose to adhere to expiry dates on
foods, but person B may believe that expiry dates are only guidelines
and it is still safe to eat the food days past the expiry date. But
not all human beings think the same way (universalism).

Intersubjectivity argues that each thought community shares social
experiences that are different from the social experiences of other
thought communities, creating differing beliefs among people who
subscribe to different thought communities. These experiences
transcend our subjectivity, which explains why they can be shared by
the entire thought community. Proponents of intersubjectivity
support the view that individual beliefs are often the result of
thought community beliefs, not just personal experiences or universal
and objective human beliefs. Beliefs are recast in terms of standards,
which are set by thought communities.

 -- [[https://en.wikipedia.org/wiki/Intersubjectivity][Intersubjectivity]] | Wikipedia
#+end_quote

 /inter-subjective/



** God Stories

#+begin_quote
Here’s a common story about gods. Our distant ancestors
didn’t understand the world very well, and their minds
contained powerful agent detectors. So they came to see
agents all around them, such as in trees, clouds, mountains,
and rivers. As these natural things vary enormously in size
and power, our ancestors had to admit that such agents
varied greatly in size and power. The big ones were thus
“gods”, and to be feared. While our forager ancestors were
fiercely egalitarian, and should thus naturally resent the
existence of gods, gods were at least useful in limiting
status ambitions of local humans; however big you were, you
weren’t as big as gods. All-seeing powerful gods were also
useful in enforcing norms; norm violators could expect to be
punished by such gods.

However, once farming era war, density, and capital
accumulation allowed powerful human rulers, these rulers
co-opted gods to enforce their rule. Good gods turned
bad. Rulers claimed the support of gods, or claimed to be
gods themselves, allowing their decrees to take priority
over social norms. However, now that we (mostly) know that
there just isn’t a spirit world, and now that we can watch
our rulers much more closely, we know that our rulers are
mere humans without the support of gods. So we much less
tolerate strong rulers, their claims of superiority, or
their norm violations. Yay us.

There are some problems with this story, however. Until the
Axial revolution of about 3500 years ago, most gods were
local to a social group. For our forager ancestors, this
made them VERY local, and thus typically small. Such gods
cared much more that you show them loyalty than what you
believed, and they weren’t very moralizing. Most gods had
limited power; few were all-powerful, all-knowing, and
immortal. People mostly had enough data to see that their
rulers did not have vast personal powers. And finally,
rather than reluctantly submitting to gods out of fear, we
have long seen people quite eager to worship, praise, and
idolize gods, and also their leaders, apparently greatly
enjoying the experience.

Here’s a somewhat different story. Long before they became
humans, our ancestors deeply craved both personal status,
and also personal association with others who have the high
status. This is ancient animal behavior. Forager egalitarian
norms suppressed these urges, via emphasizing the also
ancient envy and resentment of the high status. Foragers
came to distinguish dominance, the bad status that forces
submission via power, from prestige, the good status that
invites you to learn and profit by watching and working with
them. As part of their larger pattern of hidden motives,
foragers often pretended that they liked leaders for their
prestige, even when they really also accepted and even liked
their dominance.

Once foragers believed in spirits, they also wanted to
associate with high status spirits. Spirits increased the
supply of high status others to associate with, which people
liked. But foragers also preferred to associated with local
spirits, to show local loyalties. With farming, social
groups became larger, and status ambitions could also
rise. Egalitarian norms were suppressed. So there came a
demand for larger gods, encompassing the larger groups.

In this story the fact that ancient gods were spirits who
could sometimes violate ordinary physical rules was
incidental, not central. The key driving force was a desire
to associate with high status others. The ability to violate
physical rules did confer status, but it wasn’t a different
kind of status than that held by powerful humans. So very
powerful humans who claimed to be gods weren’t wrong, in
terms of the essential dynamic. People were eager to worship
and praise both kinds of gods, for similar reasons.

Thus today even if we don’t believe in spirts, we can still
have gods, if we have people who can credibly acquire very
high status, via prestige or dominance. High enough to
induce not just grudging admiration, but eager and
emotionally-unreserved submission and worship. And we do in
fact have such people. We have people who are the best in
the world at the abilities that the ancients would recognize
for status, such as physical strength and coordination,
musical or story telling ability, social savvy, and
intelligence. And in addition, technology and social
complexity offer many new ways to be impressive. We can buy
impressive homes, clothes, and plastic surgery, and travel
at impressive speeds via impressive vehicles. We can know
amazing things about the universe, and about our social
world, via science and surveillance.

So we today do in fact have gods, in effect if not in
name. (Though actors who play gods on screen can be seen as
ancient-style gods.) The resurgence of forager values in the
industrial era makes us reluctant to admit it, but a casual
review of celebrity culture makes it very clear, I’d
say. Yes, we mostly admit that our celebrities don’t have
supernatural powers, but that doesn’t much detract from the
very high status that they have achieved, or our inclination
to worship them.

— Robin Hanson "Like the Ancients, We Have Gods. They’ll Get Greater"
  2018-04-3  


#+end_quote

** Shamanic Interface




#+begin_quote
“The shamanic interface is the mechanism for interacting
with the darknet. It’s called the shamanic interface because
it was designed to be comprehensible to all people on earth,
regardless of technological level or cultural background.”
She made a series of precise flourishes with her hands,
leaving behind glowing lines in D-Space that formed an
intricate pattern. As she finished, an unearthly, angelic
voice sounded in the room, like a good spirit.

Sebeck looked around him for the origin of the disembodied
voice.

Riley lowered her hands. “It was a hypersonic sound,
Sergeant. Linked to a macro that I created based on somatic
gestures. But my point is that it looks like magic. Even the
most remote tribes in Papua New Guinea understand the
concept of magic—and that certain rituals must be observed
to invoke it. They believe in a spirit world where ancestors
and supernatural beings watch over them. The shamanic
interface simply connects high technology to that belief
system, granting ‘powers’ and equipment as a reward for
useful, organized activity.”

Sebeck leaned back in his chair. “Useful to whom?”

“Humanity, Sergeant. This is big-picture stuff. Repositories
of human knowledge and technology are being designed and
built by various curator factions around the world. The spec
is simply that these repositories be durable, inspire awe,
and be equipped with automated systems that can teach people
useful knowledge to empower the more rational among the
population so that they can achieve leadership
positions. That way, should human civilization be lost in a
region, this system could put locals back on a path to
regain knowledge in a generation or two. It could also be
useful in resisting a downward spiral to begin with.”

Sebeck looked at the solid walls around them. He looked back
at Riley quizzically.

“Correct. Two-Rivers Hall will be a repository when it’s
finished. That may take many decades.”

“But doesn’t this just spread mysticism? Lies, essentially?”

“You mean fairy tales? Yes, initially. But then, a lot of
parents tell young children that there’s a Santa Claus. It’s
easier than trying to explain the cultural significance of
midwinter celebrations to a three-year-old. If false magic
or a white lie about the god-monster in the mountain will
get people to stop killing one another and learn, then the
truth can wait. When the time is right, it can be replaced
with a reverence for the scientific method.”

“And this is why Sobol created the Daemon?”

She shook her head. “No, this is why they call it the
shamanic interface. Because it resembles sorcery—and might
as well be to low-tech people. But unlike sorcery, it exists
and conveys real power.”

— Freedom cite:suarez:2011freedom
#+end_quote


** References

  - Suarez, D., Freedom (tm) (2011), : Signet.
    cite:suarez:2011freedom
