#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Process Guilds
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/guild-proces.org
  :Created: 2017-04-18T11:06@Prek Leap (11.642600N-104.919210W)
  :ID: e1831a5b-f365-439e-8089-d6df7ca05406
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

* Not In My Backyard

#+begin_comment
This needs to be moved -- to Process Guilds (need to create)

I think it fits with Alexander's idea of communities
requiring that every addition strengthen what is there.  So
no cookie-cutter template chain stores -- don't ban the
chains, but they will have to adapt to local norms, rather
than impose their copies that destroy the surrounding life
of the community.  They have to become part of the community
-- and that goes far deeper than architecture, the chains
will have to learn to become 'local' shops, that don't push
out existing shops and strengthen those shops.

Hardware stores are a better example than coffee shops -- if
a hardware chain moves in, and sells to their competition as
well as sell through their own shops, they have strengthened
the community and gained instant market-share.  It's like
HugeNet in HK -- Metrolink sold routers and terminal servers
to competing ISPs, it didn't hurt our business, and we made
money from our competition.

Remember, AI & Robots will replace a lot of jobs -- so what
you have left is the supply chain, logistics, economy of
scale, and local service.  The last one is the most
important -- everything else becomes a middleman that AI and
the robots will replace.

This doesn't need to be a zero-sum game between the big and
small players.  Perhaps McDonalds could become a supply
chain and network for other restaurants, instead of just
being in the fast-food retailer business.

But actually this is where the "process guild" network comes
in to provide exactly this.  You don't need McDonalds -- you
need infrastructure with AI and robots that provides this as
a public utility....

   utility as a service, monopoly, or a commons?

And then we turn the tables on the big companies and force
them to buy from the guild-nets, to buy locally, and conform
to local packaging -- so they loose their economy of scale
and all is left is branding and marketing....  and they melt
away, "what a world, what a world"....


The girl at i-Cafe with the pig farm -- how cold guild-nets
solve her problem and stave off bastards like CP?
#+end_comment

When people say "not in my backyard" they are playing with
fire.  Everything is in someone's backyard, by pushing
things away that have potential negative side effects we are
passing the buck.  Rather, we need, as a civilization to use
the clout that comes from having something in your backyard
to change it for the better so it does not become a problem.
We need to give people the ability to change what is in
their backyard for the better, but not 100% block anything
they don't like from moving into the neighborhood.  This is
a balance that has been lost.  The fear is understandable,
because corporation and governments often will do things
without transparency or accountability.  If you have those
two things -- so that you say, okay, you can move in, but we
will want voting seats on your board and in return we will
work with you and not against you.  This should work at a
lot of different scales -- it's not just about pipelines,
nuclear power plants, and windfarms -- it's about Starbucks
opening a shop on a street with four existing small coffee
shops -- and the knowledge that Starbucks will likely drive
three of them out of business.  This is not real 
competition, Starbucks will win because they are large and
the smaller shops are not -- but if the price of Starbucks
coming into that neighborhood required it to work with the
smaller shops -- perhaps by handicapping Starbucks in some
way, and forcing them to compete on the local shop's terms,
or forcing Starbucks to provide supplies to those shops at
the same cost of scale that they enjoy -- there could be a
different outcome -- a lot of it depends on the carrying
capacity on the street for coffee shops -- take away
Starbuck's advantage and perhaps only one of the shops goes
out of business....


