#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Bands
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/deploy/social-bands.org
  :Created:   2017-04-26T10:24@Prek Leap (11.642600N-104.919210W)
  :ID:        6c2d004c-57da-40fc-a9b9-aa211027ead0
  :VER:       551748113.477498956
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:CMC2-4711
  :Class:     deploy
  :Type:      work
  :Status:    stub
  :Licence:   MIT/CC BY-SA 4.0
  :END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-stub-CC79A7.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

  - [[https://en.wikipedia.org/wiki/Band_society][Band society]]   | Wikipedia
  - [[https://en.wikipedia.org/wiki/Egalitarianism][Egalitarianism]] | Wikipedia


Bands are an important demarcation, in that they are the
ideal and natural size for egaltarian societies of 100 or
less individuals.


#+begin_quote
In his 1972 study, /The Notion of the Tribe/, Morton Fried
defined bands as small, mobile, and fluid social formations
with weak leadership that do not generate surpluses, pay
taxes nor support a standing army.

Bands are distinguished from tribes in that tribes are
generally larger, consisting of many families. Tribes have
more social institutions, such as a chief, big man, or
elders. Tribes are also more permanent than bands; a band
can cease to exist if only a small group splits off or
dies. Many tribes are sub-divided into bands.  Historically,
some tribes were formed from bands that came together from
time to time for religious ceremonies, hunting, or warfare.

-- Fried, Morton H. 1975. The notion of tribe. Menlo Park,
    Calif: Cummings Pub. Co.
#+end_quote


I'd like to explore how the old new england concept of a
neighborhood compares with bands.  How do members of a bands
identify themselves.  These are groups that depend on each
other for survival.  They identify themselves as members of
the band.  In the same way, new england neighborhoods had
their own cemetaries -- people prefered to be buried there
rather than in remote family plots.  Neighborhoods shared
resources, and pooled resources for large capital
expenditures like farm equipment such as combines.

In a post-nation state, could there be a modern concept of a
band -- which is a legal entity, but not strictly based on
family relationships -- so not a clan, a clan is a band made
up of relatives.

I'm thinking along these lines because a band could
collectively own a number of shops that are interdependent
and would collectively own property and structures.  Joining
or leaving a band would be similar to a business
partnership, but closer to a marriage, because it would
cross many boundries of personal identity, ownership and
family.

So villages would be made up of multiple overlapping bands,
and bands made up of families and shops.  Bands could then
belong to tribes, in the sense of Neal Stephenson's /phyles/
in Diamond Age, Joel Kotkin distributed diaspora.

Tribes are a lot like guilds, but embody distributed
nations.  In many respects there is no real difference -- a
guild might also be a tribe in their own right.

Tribes and guilds are not allowed to form states or the same
powers afforded to Westphalian Nation States.  States, in
turn must allow tribes to be able to purchase or lease
property within their states for the establishment of
enclaves.  Enclaves must be subject to the host States'
judicial and legal system, universal bill of rights, and
provide free travel within it's borders to anyone allowed to
enter the state.  Their currencies must be fully exchangable
with the state's financial network, and are required to
maintain their share of infrastructure costs and
maintainence.  There will also be limitations on rules
imposed on people within enclaves as well -- and children
will be required to complete a base secular trivium, mastery
and global civics studies.

Sounds a lot like Diamond Age -- and it is open to a lot of
problems and potential conflict between different tribes and
states.  But we will need something like this -- separate
nations from states -- states control physical territory and
provide basic governance and infrastructure.  Tribes provide
social structure for people's lives and identity.  Bands
look out for each other, pool resources and provide a safety
net for families.  Cities, towns and villages are part of
states.  States, ideally should encompass a single bioregion
and take part in the global and pan solar governments.


* Bands and shops

It struck me that more and more, my evolving concept of a
/shop/ is in effect a /band/.  So the base unit for what I
am envisioning is a distributed network of bands that each
are made up of 15-25 people or 3-5 families, which
constitute an economic, social and production unit.

You form a band something like a corporation, which will
purchase or lease property (or at least a couple of
buildings) which is owned by the corporation.  When you join
the band you become a shareholder, when you leave the band,
you don't so much divest your shares as much as the band
helps to fund your departure and get started somewhere
else.  In this way children, who marry outside the band, or
want to start a new band are funded by the band that they
came from.

A band is responsible for the children -- the band raises
the children, not just the parents.  The band is responsible
for teaching children the trivium and learning the band's
trade.  If you retire, you can stay in the band until you
die, if you wish and the elderly are cared for like the
children.  This will only work if a band can maintain a
critical number of /productive/ members who will bring in
revenue.  Everyone will participate in economic  activities
either as working in the band's primary or secondary shop.
Or as a remote worker, working for another band.  Each band
will also belong to one or more guilds and maintain living
quarters for a handful of apprentices and or jacks who will
work in the band while working to become masters in their
own right.

---

To jump start the idea of a band we will first need a
network that can link them together and help generate
revenue.  Since it is hoped that the model will work best
when it replaces local value and logistic chains, it will
need to work at least okay in a sparse network where each
node may be arbitrarily far away.  This is how the internet
started.  If it wasn't for the UUCP store and forward
network that piggybacked on the POTS network, TCP/IP
probably wouldn't have taken off the way it had.  But
because of UUCP, major nodes connected to each other using
leased circuits, which then acted as a backbone for UUCP
connections.  Fidonet was a store and forward network that
never had a fast backbone, so it was a very powerful local
network but couldn't scale because long distance telephone
calls were expensive and the bandwidth was limited to what a
phone modem could handle.

For bands/shops to become a working network we will have to
solve the same problem.  Thankfully we have the Internet
which will act as a backbone.  But that is only part of the
problem.  If the whole idea is to create a network of shops
that become value/supply chains then the first nodes will
not have anyone to source or sell to.  So the system will
have to piggyback on top of the existing value/supply chain.
