#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Bands
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/social-bands.org
  :Created: 2017-04-26T10:24@Prek Leap (11.642600N-104.919210W)
  :ID: 6c2d004c-57da-40fc-a9b9-aa211027ead0
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction


  - [[https://en.wikipedia.org/wiki/Band_society][Band society]]   | Wikipedia
  - [[https://en.wikipedia.org/wiki/Egalitarianism][Egalitarianism]] | Wikipedia


Bands are an important demarcation, in that they are the ideal and
natural size for egaltarian societies of 100 or less individuals.


#+begin_quote
In his 1972 study, /The Notion of the Tribe/, Morton Fried defined bands
as small, mobile, and fluid social formations with weak leadership
that do not generate surpluses, pay taxes nor support a standing army.

Bands are distinguished from tribes in that tribes are generally
larger, consisting of many families. Tribes have more social
institutions, such as a chief, big man, or elders. Tribes are also
more permanent than bands; a band can cease to exist if only a small
group splits off or dies. Many tribes are sub-divided into
bands.  Historically, some tribes were formed from bands that came
together from time to time for religious ceremonies, hunting, or
warfare.

-- Fried, Morton H. 1975. The notion of tribe. Menlo Park, Calif:
    Cummings Pub. Co.
#+end_quote


I'd like to explore how the old new england concept of a neighborhood
compares with bands.  How do members of a bands identify themselves.
These are groups that depend on each other for survival.  They
identify themselves as members of the band.  In the same way, new
england neighborhoods had their own cemetaries -- people prefered to
be buried there rather than in remote family plots.  Neighborhoods
shared resources, and pooled resources for large capital expenditures
like farm equipment such as combines.

In a post-nation state, could there be a modern concept of a band --
which is a legal entity, but not strictly based on family
relationships -- so not a clan, a clan is a band made up of relatives.

I'm thinking along these lines because a band could collectively own a
number of shops that are interdependent and would collectively own
property and structures.  Joining or leaving a band would be similar
to a business partnership, but closer to a marriage, because it would
cross many boundries of personal identity, ownership and family.

So villages would be made up of multiple overlapping bands, and bands
made up of families and shops.
