#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Bands
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/social-bands.org
  :Created: 2017-04-26T10:24@Prek Leap (11.642600N-104.919210W)
  :ID: 6c2d004c-57da-40fc-a9b9-aa211027ead0
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction


  - [[https://en.wikipedia.org/wiki/Band_society][Band society]]   | Wikipedia
  - [[https://en.wikipedia.org/wiki/Egalitarianism][Egalitarianism]] | Wikipedia


Bands are an important demarcation, in that they are the ideal and
natural size for egaltarian societies of 100 or less individuals.


#+begin_quote
In his 1972 study, /The Notion of the Tribe/, Morton Fried defined bands
as small, mobile, and fluid social formations with weak leadership
that do not generate surpluses, pay taxes nor support a standing army.

Bands are distinguished from tribes in that tribes are generally
larger, consisting of many families. Tribes have more social
institutions, such as a chief, big man, or elders. Tribes are also
more permanent than bands; a band can cease to exist if only a small
group splits off or dies. Many tribes are sub-divided into
bands.  Historically, some tribes were formed from bands that came
together from time to time for religious ceremonies, hunting, or
warfare.

-- Fried, Morton H. 1975. The notion of tribe. Menlo Park, Calif:
    Cummings Pub. Co.
#+end_quote


I'd like to explore how the old new england concept of a neighborhood
compares with bands.  How do members of a bands identify themselves.
These are groups that depend on each other for survival.  They
identify themselves as members of the band.  In the same way, new
england neighborhoods had their own cemetaries -- people prefered to
be buried there rather than in remote family plots.  Neighborhoods
shared resources, and pooled resources for large capital expenditures
like farm equipment such as combines.

In a post-nation state, could there be a modern concept of a band --
which is a legal entity, but not strictly based on family
relationships -- so not a clan, a clan is a band made up of relatives.

I'm thinking along these lines because a band could collectively own a
number of shops that are interdependent and would collectively own
property and structures.  Joining or leaving a band would be similar
to a business partnership, but closer to a marriage, because it would
cross many boundries of personal identity, ownership and family.

So villages would be made up of multiple overlapping bands, and bands
made up of families and shops.  Bands could then belong to tribes, in
the sense of Neal Stephenson's /phyles/ in Diamond Age, Joel Kotkin
distributed diaspora.

Tribes are a lot like guilds, but embody distributed nations.  In many
respects there is no real difference -- a guild might also be a tribe
in their own right.

Tribes and guilds are not allowed to form states or the same powers
afforded to Westphalian Nation States.  States, in turn must allow
tribes to be able to purchase or lease property within their states
for the establishment of enclaves.  Enclaves must be subject to the
host States' judicial and legal system, universal bill of rights, and
provide free travel within it's borders to anyone allowed to enter the
state.  Their currencies must be fully exchangable with the state's
financial network, and are required to maintain their share of
infrastructure costs and maintainence.  There will also be limitations
on rules imposed on people within enclaves as well -- and children
will be required to complete a base secular trivium, mastery and
global civics studies.

Sounds a lot like Diamond Age -- and it is open to a lot of problems
and potential conflict between different tribes and states.  But we
will need something like this -- separate nations from states --
states control physical territory and provide basic governance and
infrastructure.  Tribes provide social structure for people's lives
and identity.  Bands look out for each other, pool resources and
provide a safety net for families.  Cities, towns and villages are
part of states.  States, ideally should encompass a single bioregion
and take part in the global and pan solar governments.





