#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Tribes
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/deploy/social-tribes.org
  :Created: 2017-04-25T12:15@Prek Leap (11.642600N-104.919210W)
  :ID: 95827bc8-b0ff-42a1-b53b-08d6062d0ad9
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction


#+begin_comment
A million people is not just a million people -- it must include a
whole ecosystem that is complex enough to be able to self-correct,
that includes everything from microbes to mega-fauna -- this will be
the biggest challenge -- the biosphere experiments are many orders of
magnitude too simple.  It's not just creating a pressurized breathable
atmosphere, that is easy at small scales, but it won't scale.  That
was the whole point of Robinson's critique of generation ships -- that
the ecosystems in the ships will be too simple to be antifragile --
there are too many things that will knock them out of wack and cascade
and collapse.  At scale it will all end very badly with the approaches
we are using at the moment.  The sum of our parts is larger than
ourselves, from the microbes in our guts to fucking knows what else.
We need to work out how to bring earth with us everywhere we go and we
simply don't know how to do it.
#+end_comment

#+begin_comment
Our brains have always been black boxes -- just like the emerging AI
systems we are building.   Stop worrying about not knowing what
happens inside the black box so much as worrying about how the black
boxes will externalize and communicate and remember the shit that
comes out of the box.  Treat AI's as the same as our brains and
construct tools that extend those black boxes so that other AIs and
humans can work out what is good and bad and bullshit and the rest.
The collective is the best means of checking and balancing -- not
handicapping.  Shit goes in and shit goes out and you deal with what
comes out and don't work so much about what happens in between.  If
someone goes off the rails then they are cut out.  It's the system
that has to regulate -- there won't be any one AI that could dominate
and do what people are scared of at the moment, unless we don't even
try to pay attention to the shit that comes out.  This is not magic,
it's how everything works in nature.  It's why scientists who work in
biotech aren't worried about gray goo -- nature is far more robust
than we think -- and that's how we have to build AI.

Perhaps that isn't clear -- brains kept externalizing by building
other brains around them, and then we externalized outside the body
with spoken language, then written language, the external cognition
and external muscle.

Each of our brains are black boxes to the the other parts of our brains.

AI's will externalize in the same way -- by building layers on layers
that don't replace the layers beneath them.  These layers should in
principle work as pace layers when they work, and shearing layers when
they don't.

We assume that AIs will be able to replace themselves completely --
but that can't happen because it's not the same as creating whole new
brains that replace the old one -- there is no bridge to make that
happen, so we will end up with crufty AIs that will be complex nested
black boxes that will still have to talk to other black boxes and
we're back to the same messy situation that humans have to deal with
today.

#+end_comment


 - [[https://en.wikipedia.org/wiki/Tribe][Tribe]] | Wikipedia
 - Tribes | Joel Kotkin (1992)
 - [[https://en.wikipedia.org/wiki/Joel_Kotkin][Joel Kotkin]] | Wikipedia
 - The Notion of Tribe | Cummings Pub. (1975)
 - [[https://en.wikipedia.org/wiki/Morton_Fried][Morton Fried]] | Wikipedia

 - Constant Battles: Why We Fight | Steven LeBlanc (2004)

 - How War Began | Keith Otterbein
 - War Before Civilization | Lawrence Keeley
 


 - [[https://en.wikipedia.org/wiki/The_World_Until_Yesterday][The World Until Yesterday]] | Wikipedia
 - [[https://en.wikipedia.org/wiki/Jared_Diamond][Jared Diamond]] | Wikipedia


