#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Mars Notes (expression)
#+STARTUP: showall

#+PROPERTY: filename
  :PROPERTIES:
  :CUSTOM_ID: Mars_Notes_(expr)
  :Name:      /home/deerpig/proj/chenla/deploy/solar-mars.org
  :Created:   2017-04-01T09:28@Prek Leap (11.642600N-104.919210W)
  :ID:        44c96d1e-d1be-432d-8068-efa5040e5094
  :VER:       551458557.325193986
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:DEQ2-0170
  :Class:     deploy
  :Type:      expression
  :Status:    wip 
  :Licence:   MIT/CC BY-SA 4.0
  :END:

  :TREE:
  :UF:
  :BTI+:
  :BTP:   [[hord:LBR3-3530][Mars_Notes_(work)]]
  :RT:
  :END:


[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-expresssion-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

* Introduction

#+begin_quote
“ Designing protocols that work across vast distances like planets
makes it possible for people around the Earth that are in distant
areas far away from the data center to connect as easily and nicely as
people in the nice vast cities like this one. This is what we call the
interplanetary principle. Design things for planets — planetary
scale — and you will do very well on Earth.”

-- Juan Benet
#+end_quote

* Introduction

 - [[http://caseyexaustralia.blogspot.com/2017/05/a-roadmap-to-industrially-self.html?m=1][A roadmap to an industrially self-sufficient Mars base in the minimum time]]
 - [[http://www.caseyhandmer.com/home/mars][Mars is Hard]] | Casey Handmer
 - [[https://plus.google.com/+CaseyHandmer][Casey Handmer]] | Google+


We will not be concerning ourselves with getting to mars, initial
survival on mar or building and maintaining a settlement.  We start
where Musk's first stage finishes and he is now ferrying hundreds of
thousands of people to the planet.

#+BEGIN_QUOTE
  In many ways, the transportation problem of getting us to
  Mars, over the long term is the smallest problem that we
  will be facing.  Transplanting civilization to Mars will
  not be a matter of setting up quonset huts with hydroponic
  farms with people in bubble helmeted suits riding in dune
  buggies off the cover of Amazing Stories or an inspiring
  Robert McCall mural on the wall of the Air and Space
  Museum on the Washington Mall.

  These are visions of exploration and technology, they
  embody the bold confident optimisim of the Apollo program.
  But ultimately they are visions of research stations.
  It's what you have at McMurdy Station in Antarctica.  And
  ultimately it's a thoroughly depressing vision if you
  start thinking about living in these paintings over years
  and decades.  It doesn't age well, it's existence, not
  life.

  We need to start thinking in terms of building a permanent
  civilization on Mars, a home, albeit very different from
  Earth, but still a place that you would want to live.  For
  that we need to be thinking as architects, and community
  planners.

  It will need to be able to cut the cord with Earth, as
  soon as possible if not sooner.  That will mean not only
  building computer chips, but sourcing and refining the
  silica.  It won't only be building systems that produce
  breathable air, potable water and sewage, but public
  utilities that are paid for by something like a tax
  system.

  We don't need to transplant the "American way of life" or
  any other such nonsense.  Rather we need to provide the
  initial conditions for an open economy, with commerce,
  manufacturing and a government to emerge as the colony
  becomes a community.  We have to encourage local
  businesses and startups not just work for the inevitable
  multinationals from the home world who will sponsor many
  parts of the early stages and inevitably pump large
  amounts of money to stake out large corporate claims on
  the planet.

  - I lost the reference to this quote...
#+END_QUOTE

* Musk's Million on Mars

A million people is not just a million people -- it must include a
whole ecosystem that is complex enough to be able to self-correct,
that includes everything from microbes to mega-fauna -- this will be
the biggest challenge -- the biosphere experiments are many orders of
magnitude too simple.  It's not just creating a pressurized breathable
atmosphere, that is easy at small scales, but it won't scale.  That
was the whole point of Robinson's critique of generation ships -- that
the ecosystems in the ships will be too simple to be antifragile --
there are too many things that will knock them out of wack and cascade
and collapse.  At scale it will all end very badly with the approaches
we are using at the moment.  The sum of our parts is larger than
ourselves, from the microbes in our guts to fucking knows what else.
We need to work out how to bring earth with us everywhere we go and we
simply don't know how to do it.


* Notes

** Making Humans a Multi-Planetary Species
:PROPERTIES:
:INTERLEAVE_PDF: ~/proj/chenla/deploy/lib/musk--making_humans_a_interplanetary_species-2017.pdf
:END:


#+begin_src bibtex
@Article{Musk_2017,
  author       = {Musk, Elon},
  title	   = {Making Humans a Multi-Planetary Species},
  year	   = 2017,
  volume       = 5,
  number       = 2,
  month	   = {Jun},
  pages	   = {46–61},
  issn	   = {2168-0264},
  doi	   = {10.1089/space.2017.29009.emu},
  url	   = {http://dx.doi.org/10.1089/space.2017.29009.emu},
  journal      = {New Space},
  publisher    = {Mary Ann Liebert Inc}
}
#+end_src

*** Notes for page 1
:PROPERTIES:
:interleave_page_note: 1
:END:

Musk's goal is to build up a permanent population on Mars of one
million people over 40-100 years.  This will require 10,000 trips
carrying 100 people each.

*** Notes for page 13
:PROPERTIES:
:interleave_page_note: 13
:END:

More notes

* Mars Whitepaper Outline


 - first step towards a long now
 - a distributed civilization
 - mars is a part of that
 - never go full retard

first step is:

 - build platform and infrastructure that people can get
   excited about, join and start building -- in their own
   backyard -- this will become a sustainable network of
   people, ideas, and shops that give people a livelihood
   that works towards a antifragile multiplanet civilization

then we can go retard -- but not full retard.

what is the minimum viable product for SNOT supply-production
chains?

---

** Four Stages

 - get there, establish base
 - sustainable settlement
 - distributed civilization
 - terraform
** Civilization is about specialties
** automation -- ai & robots
** we need an economic model
 - funding must be based on economic model on earth and on
   mars


** It must be distributed
 - heavy industry -- 99% automated and even remote
 - everything else is a fabric of cottage industry that
   leverages ai and robotics to massively multiply
   production
 - we'll be living inside terrariums -- which are
   vulnerable to disease -- can not put everything in one
   basket...
** It will only work on mars if it works on earth
 - 80% of what you do on mars is no different on earth, just
   in extreme cold and indoors and largely underground.
 - build a mars civilization in every backyard on earth
 - people can start shops and join guilds on earth and then
   take what they learn and then to do it on mars.
 - the system will be it's own blockchain based economy,
   establish crypto-credit unions to save money for the trip
   and to get established on mars
** everything is agriculture
 - growing an atmosphere, not air production
 - monocultures the exception not the rule
 - building ecosystems, not farms
 - bugs on mars
 - grow everything - not just food and air - learn to love
   grass
 - animals are not a luxury -- even megafuana -- remember we
   are backing up earth folks, biodiversity is critical
 - replicate multiple climates and bioregions in different
   settlements -- mars is noah's ark with space suits.
 - gmo starts from day one
 - everyone grows stuff, everywhere - no exceptions
** leave all baggage behind
 - plant no flags
 - no earth-based territories or borders
 - earth corporations must assimilate
 - you're all martians now -- that's your new identity
 - assimilate or don't come
 - no room for national identities
 - no room for ideologies (social, religious, economic)
 - no food or clothing ideologies allowed
 - no splinter settlements (at least in the first million)
** open designs & knowledge
 - nothing is proprietary
 - generative designs and plans
 - build structures and things that live
** nothing is disposable
 - build to last
 - interchangable modular everything
 - build to be repairable
 - gracefully degrade
** getting good at living inside
 - we're going to be stuck inside for hundreds of years so
   we better get really really good at it.
 - we have to get really really good at tunneling
** stage everything in antarctica
 - if it can't work there it won't work on mars -- not only
   materially sustainable, but economically.
 - fail fast and often 
 - everyone going to mars must first be done in antarctica
   for anywhere from 6 months to 2 years -- assimilation
   starts there.
 - includes all fuel production, growing food, making
   atmosphere, medicine, electronics, heavy industry etc.
** Education comes first and last
** don't wait to start building solar civilization
 - mars is not an end, it is a gateway to the solar system
 - build heavy industry in asteroid belt
 - get good at moving big rocks and ice
 - process insitu while it's being moved
 - learn to live in big rocks as well as you do on mars or earth


* Economic model for funding and colonizing the solar system 

 - mars is not an end in itself -- the long term goal is to
   make mankind and our civilization anti-fragile which
   means we need to become a distributed civilization.
   keeping today's model and transplanting it to mars will
   not achieve this in a meaningful way -- then we will have
   two fragile planetary civilizations.  we need to make
   civilization on both planets and where ever else man goes
   to be as distributed and resilient as possible.

 - baldwin says it comes down to distance -- and cost of
   moving goods, ideas and people.  when cost of
   transporting goods became cheap with the steam revolution
   it triggered the first globalization revolution, with ICT
   became cheap, ideas (including money) could move anywhere
   on the planet for essentially nothing -- in 1990 this
   triggered what Baldwin called the second unbundling which
   we are now at the tail end of -- which split production
   from where the knowledge was to where the labour was
   cheap, with knowledge still largely being kept by the
   original G7 countries and labour provided by I7. So
   transport is cheap, moving ideas is cheap but moving
   people is still expensive.

 - automation replaces many of the functions required by moving
   people.

 - today know-how is tied up in proprietary IP which rights
   holders will not want to become distributed because it
   effectively takes away the advantages of controlling that
   knowledge.

 - most of this knowledge, since WWII has been for processes
   at scale -- which actually doesn't work at small scales
   as is.  For a truly distributed system, this knowledge
   needs to be adapted to small scale production processes.
   and the only way this can work is if it is all open
   source.  In fact, not just open source but aggressively
   open source.  So in effect, Richard Stallman was right.

 - this will have the effect of opening up production chains
   to developing economies who have been left out of second
   wave globalization.  So, this is perhaps the only means
   of flattening the spikes.

 - mars colonization requires a funding model, and an
   economic model for what is being built on mars.

 - trade between mars and earth will not be viable in the
   foreseeable future, so investment in mars that is based
   on economic return to earth won't work.  There is no
   equiv of England and America, where America had land and
   no people and England had people and no land, that could
   kick start trans-atlantic trade.  So we need a funding
   model which is purely based on emigration.  America was
   settled by self-funded individuals looking to make a new
   home, not by states or corporations looking to expand.

 - if the cost of emigration is reasonable, then this is
   possible, but only if there is an infrastructure to
   provide more than the cost of a ticket.  we will need
   education, training, and staging and a means of
   producing what will be taken to mars to establish
   emigrants.  Families and communities need to support this
   back on earth and provide a stable base for sending those
   who will go to mars.

 - kickstarting a new stage of globalization that will make
   the world less flat can make it possible to provide the
   infrastructure needed to move out into the solar system
   in numbers for us to become a multi-planet species.


