#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Mars Notes (expression)
#+STARTUP: showall

#+PROPERTY: filename


[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-deploy-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-expresssion-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

* Mars Notes (expression)
  :PROPERTIES:
  :CUSTOM_ID: Mars_Notes_(expr)
  :Name:      /home/deerpig/proj/chenla/deploy/solar-mars.org
  :Created:   2017-04-01T09:28@Prek Leap (11.642600N-104.919210W)
  :ID:        44c96d1e-d1be-432d-8068-efa5040e5094
  :VER:       551458557.325193986
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:DEQ2-0170
  :Class:     deploy
  :Type:      expression
  :Status:    wip 
  :Licence:   MIT/CC BY-SA 4.0
  :END:

  :TREE:
  :UF:
  :BTI+:
  :BTP:   [[hord:LBR3-3530][Mars_Notes_(work)]]
  :RT:
  :END:


** Introduction

** an experiment 
:PROPERTIES:
:ID:       e0965a78-6947-428b-bf4f-00d6b7b750dc
:END:

okay -- on mars, what if we try an experiment.  Let's take a
excavated cavern -- X tall and X wide and long.  What can
you build or grow in that space -- what would it produce?
Can it sustain itself?  What kind of biodiversity is
required (big fucking question that) and how many people
would it support.  Then work out how many shops that the
cavern would support.  It would be an underground village.

Lakes and ponds are somewhat closed ecosystems that work in
small spaces -- we're building terrariums that we will live
in.

There will be buildings -- but in a lot of cases we'll be
living in the walls of the cavern, like hobbits.

** Quotes Against Mars
:PROPERTIES:
:ID:       bb3c5ec6-388c-47b3-9603-b751a49ce1c1
:END:


#+begin_quote
*Just Visiting*

“Establishing a colony on Mars is incredibly technically
challenging and expensive,” [[http://clasp.engin.umich.edu/people/ridley/FACULTY][University of Michigan’s Aaron]]
Ridley* told Futurism. He argued that while the red planet is
certainly “scientifically interesting,” the enormous costs
associated with a permanent station make it unlikely,
especially given that establishing a colony wouldn’t be a
solution to a problem like overpopulation.

“We are not going to go to the moon or Mars because of
population pressure,” he explained. “It is really because we
have an innate desire to explore.”

*Amanda Hendrix, a senior scientist at the Planetary Science
Institute*, shares a similar opinion on the prospect of a
permanent Martian settlement. “I think it makes sense to go
to Mars with humans to test technologies and to do
scientific experiments — a short term visit or visits,” she
told Futurism. “I do not think it makes sense to establish a
long-term human settlement on Mars, only because it is not
desirable as a long-term destination due to radiation
concerns.”

*Martian Money*


“I think it would be a natural next step in our human
exploration to visit the Moon and/or Mars, but to stay for
the long term probably requires an economic justification,”
said Hendrix. She added that space tourism is unlikely to
serve this purpose.

*Chris McKay*, a planetary scientist at NASA’s Ames Research
Center, maintains that the only plausible economic
motivation for a Martian colony is for it to serve as a
government base, downplaying the possibility of either
tourism or mining operations playing that role.

“The analogy here is the Antarctic bases from 1955 to about
1990,” he told Futurism. “During this time virtually all
Antarctic bases were [government] science research bases in
accordance with the Antarctic Treaty. After ~1990 tourism
started to grow. Now there are tourist bases in Antarctica
that are not [government] science research bases.”

Settling on Mars isn’t going to make anyone rich, and that’s
going to make it more difficult to accrue the money required
for such an expensive project. Still, despite the fact that
a fully-fledged colony might not be the wisest direction for
a prospective space program, there’s still plenty we could
learn from the planet.

*Mars Over the Moon*

It seems that we’re more likely to establish a base on the
moon before Mars. While this has its own benefits, most
would agree that the red planet is more interesting — even
if it’s harder to reach.

“I would agree that Mars is a much more scientifically
interesting place,” said *Ridley*, although he acknowledges
that he wouldn’t make a beeline for the planet. “I am a big
believer in baby steps, so it makes a lot of sense to try to
do something on the moon, and then move on to Mars.”

“In terms of science, Mars is way more interesting than the
moon,” wrote *McKay*. He listed three main advantages: its
similarity to Earth in terms of planetary processes and
history, the possibility of life, and the potential for
terraforming the planet.

If there were no other considerations to be made, most would
agree that a Mars colony could be a fascinating
project. However, certain endeavors need to be prioritized
over others, and right now it doesn’t seem like a permanent
Martian settlement is the best use of our resources.

-- [[https://futurism.com/humans-shouldnt-colonize-mars-experts/][All the Reasons Why Humans Shouldn't Colonize Mars,
  According to Experts]]
#+end_quote



** The Plan
:PROPERTIES:
:ID:       70de5332-6ec0-449c-ab22-aa7df65b9382
:END:

 - education -- first class of 11 year olds starts in 2020
 - small communities - shops of >15 communities 
   - stage I       :: anywhere onplanet
   - antactica II  :: 
   - mars     III  :: 
 - automatic logisitcs, supply chain, provision and transactions
 - automation -- so each person on mars can oversee multiple
   specialties
 - everything is about building ecosystems, not habitats
   - so everything is agriculture
   - base on perennials not annuals
   - bamboo!
 - everything is open source -- everything

 - [[https://futurism.com/inside-scoop-elon-musks-plan-make-insurance-life-know/][The Inside Scoop on Elon Musk’s Plan to Make “Insurance for Life as We Know It”]]


** UAE Mars Project
:PROPERTIES:
:ID:       66cfd455-c35d-4afb-ba48-79e78b257b56
:END:

 - [[http://mediaoffice.ae/en/media-center/news/14/2/2017/mars.aspx][Vice President, Mohamed bin Zayed unveil “Mars 2117
   Project”]] | Dubai Government Media Office
 - [[https://www.space.com/35817-uae-city-on-mars-2117-project.html][United Arab Emirates Wants to Build a City on Mars]] | Space.com
 - [[https://futurism.com/4-mars-2117-project-the-uae-joins-the-race-for-the-red-planet/][UAE Announces Plans to Have a Human Colony on Mars by
   2117]] | Futurism
 - 

** Boeing 
:PROPERTIES:
:ID:       21fff318-b6ab-4de4-b066-09c28e269431
:END:

 - [[http://www.boeing.com/features/2014/12/bds-path-to-mars-12-04-14.page][The Path to Mars: Deep Space Mission]] | Boeing
 - 

** NASA
:PROPERTIES:
:ID:       7aa53725-95d1-4eb8-a498-51c97b868a63
:END:

 - [[https://www.nasa.gov/sites/default/files/atoms/files/journey-to-mars-next-steps-20151008_508.pdf][NASA's Journey to Mars]] | NASA (2015) [pdf]
